// Code generated by proto2type. DO NOT EDIT.
// source: catalog.proto
// backend: firestore

package _go

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

import "time"

// ModelCatalogEntryFirestore is the Firestore storage representation of test.v1.ModelCatalogEntry.
type ModelCatalogEntryFirestore struct {
	ModelID          string    `firestore:"model_id"`
	Provider         string    `firestore:"provider"`
	DisplayName      string    `firestore:"display_name"`
	InputPerMillion  float64   `firestore:"input_per_million"`
	OutputPerMillion float64   `firestore:"output_per_million"`
	Enabled          bool      `firestore:"enabled"`
	Category         string    `firestore:"category"`
	ContextWindow    int64     `firestore:"context_window"`
	DiscountPercent  float64   `firestore:"discount_percent"`
	Aliases          []string  `firestore:"aliases,omitempty"`
	ProviderModelID  string    `firestore:"provider_model_id"`
	CreatedAt        time.Time `firestore:"created_at,omitempty"`
	UpdatedAt        time.Time `firestore:"updated_at,omitempty"`
	Notes            string    `firestore:"notes"`
	Region           string    `firestore:"region"`
}

// ToProto converts to the protobuf message.
func (d *ModelCatalogEntryFirestore) ToProto() *ModelCatalogEntry {
	if d == nil {
		return nil
	}
	pb := &ModelCatalogEntry{
		ModelId:          d.ModelID,
		Provider:         d.Provider,
		DisplayName:      d.DisplayName,
		InputPerMillion:  d.InputPerMillion,
		OutputPerMillion: d.OutputPerMillion,
		Enabled:          d.Enabled,
		Category:         d.Category,
		ContextWindow:    d.ContextWindow,
		DiscountPercent:  d.DiscountPercent,
		Aliases:          d.Aliases,
		ProviderModelId:  d.ProviderModelID,
		Notes:            d.Notes,
		Region:           d.Region,
	}
	if !d.CreatedAt.IsZero() {
		pb.CreatedAt = timestamppb.New(d.CreatedAt)
	}
	if !d.UpdatedAt.IsZero() {
		pb.UpdatedAt = timestamppb.New(d.UpdatedAt)
	}
	return pb
}

// FromProto populates from a protobuf message.
func (d *ModelCatalogEntryFirestore) FromProto(pb *ModelCatalogEntry) {
	if pb == nil {
		return
	}
	d.ModelID = pb.ModelId
	d.Provider = pb.Provider
	d.DisplayName = pb.DisplayName
	d.InputPerMillion = pb.InputPerMillion
	d.OutputPerMillion = pb.OutputPerMillion
	d.Enabled = pb.Enabled
	d.Category = pb.Category
	d.ContextWindow = pb.ContextWindow
	d.DiscountPercent = pb.DiscountPercent
	d.Aliases = pb.Aliases
	d.ProviderModelID = pb.ProviderModelId
	if pb.CreatedAt != nil {
		d.CreatedAt = pb.CreatedAt.AsTime()
	}
	if pb.UpdatedAt != nil {
		d.UpdatedAt = pb.UpdatedAt.AsTime()
	}
	d.Notes = pb.Notes
	d.Region = pb.Region
}
