// Code generated by proto2type. DO NOT EDIT.
// source: catalog.proto
// backend: mongo

package _go

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

import "time"

// ModelCatalogEntryMongo is the MongoDB storage representation of test.v1.ModelCatalogEntry.
type ModelCatalogEntryMongo struct {
	ModelID          string    `bson:"_id"`
	Provider         string    `bson:"provider"`
	DisplayName      string    `bson:"display_name"`
	InputPerMillion  float64   `bson:"input_per_million"`
	OutputPerMillion float64   `bson:"output_per_million"`
	Enabled          bool      `bson:"enabled"`
	Category         string    `bson:"category"`
	ContextWindow    int64     `bson:"context_window"`
	DiscountPercent  float64   `bson:"discount_percent"`
	Aliases          []string  `bson:"aliases,omitempty"`
	ProviderModelID  string    `bson:"provider_model_id"`
	CreatedAt        time.Time `bson:"created_at,omitempty"`
	UpdatedAt        time.Time `bson:"updated_at,omitempty"`
	Notes            string    `bson:"notes,omitempty"`
	Region           string    `bson:"region"`
}

// ToProto converts to the protobuf message.
func (d *ModelCatalogEntryMongo) ToProto() *ModelCatalogEntry {
	if d == nil {
		return nil
	}
	pb := &ModelCatalogEntry{
		ModelId:          d.ModelID,
		Provider:         d.Provider,
		DisplayName:      d.DisplayName,
		InputPerMillion:  d.InputPerMillion,
		OutputPerMillion: d.OutputPerMillion,
		Enabled:          d.Enabled,
		Category:         d.Category,
		ContextWindow:    d.ContextWindow,
		DiscountPercent:  d.DiscountPercent,
		Aliases:          d.Aliases,
		ProviderModelId:  d.ProviderModelID,
		Notes:            d.Notes,
		Region:           d.Region,
	}
	if !d.CreatedAt.IsZero() {
		pb.CreatedAt = timestamppb.New(d.CreatedAt)
	}
	if !d.UpdatedAt.IsZero() {
		pb.UpdatedAt = timestamppb.New(d.UpdatedAt)
	}
	return pb
}

// FromProto populates from a protobuf message.
func (d *ModelCatalogEntryMongo) FromProto(pb *ModelCatalogEntry) {
	if pb == nil {
		return
	}
	d.ModelID = pb.ModelId
	d.Provider = pb.Provider
	d.DisplayName = pb.DisplayName
	d.InputPerMillion = pb.InputPerMillion
	d.OutputPerMillion = pb.OutputPerMillion
	d.Enabled = pb.Enabled
	d.Category = pb.Category
	d.ContextWindow = pb.ContextWindow
	d.DiscountPercent = pb.DiscountPercent
	d.Aliases = pb.Aliases
	d.ProviderModelID = pb.ProviderModelId
	if pb.CreatedAt != nil {
		d.CreatedAt = pb.CreatedAt.AsTime()
	}
	if pb.UpdatedAt != nil {
		d.UpdatedAt = pb.UpdatedAt.AsTime()
	}
	d.Notes = pb.Notes
	d.Region = pb.Region
}

// ToDomain converts to the domain type.
func (s *ModelCatalogEntryMongo) ToDomain() *ModelCatalogEntry {
	if s == nil {
		return nil
	}
	d := &ModelCatalogEntry{
		ModelID:          s.ModelID,
		Provider:         s.Provider,
		DisplayName:      s.DisplayName,
		InputPerMillion:  s.InputPerMillion,
		OutputPerMillion: s.OutputPerMillion,
		Enabled:          s.Enabled,
		Category:         s.Category,
		ContextWindow:    s.ContextWindow,
		DiscountPercent:  s.DiscountPercent,
		Aliases:          s.Aliases,
		ProviderModelID:  s.ProviderModelID,
		CreatedAt:        s.CreatedAt,
		UpdatedAt:        s.UpdatedAt,
		Notes:            s.Notes,
		Region:           s.Region,
	}
	return d
}

// FromDomain populates from the domain type.
func (s *ModelCatalogEntryMongo) FromDomain(d *ModelCatalogEntry) {
	if d == nil {
		return
	}
	s.ModelID = d.ModelID
	s.Provider = d.Provider
	s.DisplayName = d.DisplayName
	s.InputPerMillion = d.InputPerMillion
	s.OutputPerMillion = d.OutputPerMillion
	s.Enabled = d.Enabled
	s.Category = d.Category
	s.ContextWindow = d.ContextWindow
	s.DiscountPercent = d.DiscountPercent
	s.Aliases = d.Aliases
	s.ProviderModelID = d.ProviderModelID
	s.CreatedAt = d.CreatedAt
	s.UpdatedAt = d.UpdatedAt
	s.Notes = d.Notes
	s.Region = d.Region
}
