// Code generated by proto2type. DO NOT EDIT.
// source: catalog.proto

package _go

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

import "time"

// ModelCatalogEntry is the domain representation of test.v1.ModelCatalogEntry.
//
// ModelCatalogEntry represents a model in the catalog.
type ModelCatalogEntry struct {
	ModelID          string    `json:"model_id,omitempty"`
	Provider         string    `json:"provider,omitempty"`
	DisplayName      string    `json:"display_name,omitempty"`
	InputPerMillion  float64   `json:"input_per_million,omitempty"`
	OutputPerMillion float64   `json:"output_per_million,omitempty"`
	Enabled          bool      `json:"enabled,omitempty"`
	Category         string    `json:"category,omitempty"`
	ContextWindow    int64     `json:"context_window,omitempty"`
	DiscountPercent  float64   `json:"discount_percent,omitempty"`
	Aliases          []string  `json:"aliases,omitempty"`
	ProviderModelID  string    `json:"provider_model_id,omitempty"`
	CreatedAt        time.Time `json:"created_at,omitempty"`
	UpdatedAt        time.Time `json:"updated_at,omitempty"`
	Notes            string    `json:"notes,omitempty"`
	Region           string    `json:"region,omitempty"`
}

// ToProto converts to the protobuf message.
func (m *ModelCatalogEntry) ToProto() *ModelCatalogEntry {
	if m == nil {
		return nil
	}
	pb := &ModelCatalogEntry{
		ModelId:          m.ModelID,
		Provider:         m.Provider,
		DisplayName:      m.DisplayName,
		InputPerMillion:  m.InputPerMillion,
		OutputPerMillion: m.OutputPerMillion,
		Enabled:          m.Enabled,
		Category:         m.Category,
		ContextWindow:    m.ContextWindow,
		DiscountPercent:  m.DiscountPercent,
		Aliases:          m.Aliases,
		ProviderModelId:  m.ProviderModelID,
		Notes:            m.Notes,
		Region:           m.Region,
	}
	if !m.CreatedAt.IsZero() {
		pb.CreatedAt = timestamppb.New(m.CreatedAt)
	}
	if !m.UpdatedAt.IsZero() {
		pb.UpdatedAt = timestamppb.New(m.UpdatedAt)
	}
	return pb
}

// FromProto populates from a protobuf message.
func (m *ModelCatalogEntry) FromProto(pb *ModelCatalogEntry) {
	if pb == nil {
		return
	}
	m.ModelID = pb.ModelId
	m.Provider = pb.Provider
	m.DisplayName = pb.DisplayName
	m.InputPerMillion = pb.InputPerMillion
	m.OutputPerMillion = pb.OutputPerMillion
	m.Enabled = pb.Enabled
	m.Category = pb.Category
	m.ContextWindow = pb.ContextWindow
	m.DiscountPercent = pb.DiscountPercent
	m.Aliases = pb.Aliases
	m.ProviderModelID = pb.ProviderModelId
	if pb.CreatedAt != nil {
		m.CreatedAt = pb.CreatedAt.AsTime()
	}
	if pb.UpdatedAt != nil {
		m.UpdatedAt = pb.UpdatedAt.AsTime()
	}
	m.Notes = pb.Notes
	m.Region = pb.Region
}

// ApplyFieldMaskModelCatalogEntry copies fields from src to dst based on the given paths.
func ApplyFieldMaskModelCatalogEntry(dst, src *ModelCatalogEntry, paths []string) {
	if dst == nil || src == nil {
		return
	}
	for _, path := range paths {
		switch path {
		case "model_id":
			dst.ModelID = src.ModelID
		case "provider":
			dst.Provider = src.Provider
		case "display_name":
			dst.DisplayName = src.DisplayName
		case "input_per_million":
			dst.InputPerMillion = src.InputPerMillion
		case "output_per_million":
			dst.OutputPerMillion = src.OutputPerMillion
		case "enabled":
			dst.Enabled = src.Enabled
		case "category":
			dst.Category = src.Category
		case "context_window":
			dst.ContextWindow = src.ContextWindow
		case "discount_percent":
			dst.DiscountPercent = src.DiscountPercent
		case "aliases":
			dst.Aliases = src.Aliases
		case "provider_model_id":
			dst.ProviderModelID = src.ProviderModelID
		case "created_at":
			dst.CreatedAt = src.CreatedAt
		case "updated_at":
			dst.UpdatedAt = src.UpdatedAt
		case "notes":
			dst.Notes = src.Notes
		case "region":
			dst.Region = src.Region
		}
	}
}
