// Code generated by proto2type. DO NOT EDIT.
// source: user.proto

package _go

import (
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

import "time"

// User is the domain representation of test.v1.User.
//
// User represents a user account.
type User struct {
	ID             string            `json:"id"`
	Email          string            `json:"email"`
	DisplayName    string            `json:"display_name"`
	Active         bool              `json:"active"`
	Age            int32             `json:"age"`
	Roles          []string          `json:"roles,omitempty"`
	Metadata       map[string]string `json:"metadata,omitempty"`
	Address        *Address          `json:"address,omitempty"`
	CreatedAt      time.Time         `json:"created_at,omitempty"`
	SessionTimeout time.Duration     `json:"session_timeout,omitempty"`
	Phone          string            `json:"phone,omitempty"`
}

// ToProto converts to the protobuf message.
func (d *User) ToProto() *User {
	if d == nil {
		return nil
	}
	pb := &User{
		Id:          d.ID,
		Email:       d.Email,
		DisplayName: d.DisplayName,
		Active:      d.Active,
		Age:         d.Age,
		Roles:       d.Roles,
		Metadata:    d.Metadata,
		Address:     d.Address,
		Phone:       d.Phone,
	}
	if !d.CreatedAt.IsZero() {
		pb.CreatedAt = timestamppb.New(d.CreatedAt)
	}
	pb.SessionTimeout = durationpb.New(d.SessionTimeout)
	return pb
}

// FromProto populates from a protobuf message.
func (d *User) FromProto(pb *User) {
	if pb == nil {
		return
	}
	d.ID = pb.Id
	d.Email = pb.Email
	d.DisplayName = pb.DisplayName
	d.Active = pb.Active
	d.Age = pb.Age
	d.Roles = pb.Roles
	d.Metadata = pb.Metadata
	d.Address = pb.Address
	if pb.CreatedAt != nil {
		d.CreatedAt = pb.CreatedAt.AsTime()
	}
	if pb.SessionTimeout != nil {
		d.SessionTimeout = pb.SessionTimeout.AsDuration()
	}
	d.Phone = pb.Phone
}

// ApplyFieldMaskUser copies fields from src to dst based on the given paths.
func ApplyFieldMaskUser(dst, src *User, paths []string) {
	for _, path := range paths {
		switch path {
		case "id":
			dst.ID = src.ID
		case "email":
			dst.Email = src.Email
		case "display_name":
			dst.DisplayName = src.DisplayName
		case "active":
			dst.Active = src.Active
		case "age":
			dst.Age = src.Age
		case "roles":
			dst.Roles = src.Roles
		case "metadata":
			dst.Metadata = src.Metadata
		case "address":
			dst.Address = src.Address
		case "created_at":
			dst.CreatedAt = src.CreatedAt
		case "session_timeout":
			dst.SessionTimeout = src.SessionTimeout
		case "phone":
			dst.Phone = src.Phone
		}
	}
}

// Address is the domain representation of test.v1.Address.
//
// Address is a nested message.
type Address struct {
	Street  string `json:"street"`
	City    string `json:"city"`
	State   string `json:"state"`
	Zip     string `json:"zip"`
	Country string `json:"country"`
}

// ToProto converts to the protobuf message.
func (d *Address) ToProto() *Address {
	if d == nil {
		return nil
	}
	pb := &Address{
		Street:  d.Street,
		City:    d.City,
		State:   d.State,
		Zip:     d.Zip,
		Country: d.Country,
	}
	return pb
}

// FromProto populates from a protobuf message.
func (d *Address) FromProto(pb *Address) {
	if pb == nil {
		return
	}
	d.Street = pb.Street
	d.City = pb.City
	d.State = pb.State
	d.Zip = pb.Zip
	d.Country = pb.Country
}

// ApplyFieldMaskAddress copies fields from src to dst based on the given paths.
func ApplyFieldMaskAddress(dst, src *Address, paths []string) {
	for _, path := range paths {
		switch path {
		case "street":
			dst.Street = src.Street
		case "city":
			dst.City = src.City
		case "state":
			dst.State = src.State
		case "zip":
			dst.Zip = src.Zip
		case "country":
			dst.Country = src.Country
		}
	}
}
