// Code generated by proto2type. DO NOT EDIT.
// source: user.proto
// backend: mongo

package _go

import (
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

import "time"

// UserMongo is the MongoDB storage representation of test.v1.User.
type UserMongo struct {
	ID             string            `bson:"id,omitempty"`
	Email          string            `bson:"email,omitempty"`
	DisplayName    string            `bson:"display_name,omitempty"`
	Active         bool              `bson:"active,omitempty"`
	Age            int32             `bson:"age,omitempty"`
	Roles          []string          `bson:"roles,omitempty"`
	Metadata       map[string]string `bson:"metadata,omitempty"`
	Address        *AddressMongo     `bson:"address,omitempty"`
	CreatedAt      time.Time         `bson:"created_at,omitempty"`
	SessionTimeout time.Duration     `bson:"session_timeout,omitempty"`
	Phone          *string           `bson:"phone,omitempty"`
}

// ToProto converts to the protobuf message.
func (u *UserMongo) ToProto() *User {
	if u == nil {
		return nil
	}
	pb := &User{
		Id:          u.ID,
		Email:       u.Email,
		DisplayName: u.DisplayName,
		Active:      u.Active,
		Age:         u.Age,
		Roles:       u.Roles,
		Metadata:    u.Metadata,
	}
	if u.Address != nil {
		pb.Address = u.Address.ToProto()
	}
	if !u.CreatedAt.IsZero() {
		pb.CreatedAt = timestamppb.New(u.CreatedAt)
	}
	pb.SessionTimeout = durationpb.New(u.SessionTimeout)
	pb.Phone = u.Phone
	return pb
}

// FromProto populates from a protobuf message.
func (u *UserMongo) FromProto(pb *User) {
	if pb == nil {
		return
	}
	u.ID = pb.Id
	u.Email = pb.Email
	u.DisplayName = pb.DisplayName
	u.Active = pb.Active
	u.Age = pb.Age
	u.Roles = pb.Roles
	u.Metadata = pb.Metadata
	if pb.Address != nil {
		u.Address = &AddressMongo{}
		u.Address.FromProto(pb.Address)
	}
	if pb.CreatedAt != nil {
		u.CreatedAt = pb.CreatedAt.AsTime()
	}
	if pb.SessionTimeout != nil {
		u.SessionTimeout = pb.SessionTimeout.AsDuration()
	}
	u.Phone = pb.Phone
}

// ToDomain converts to the domain type.
func (u *UserMongo) ToDomain() *User {
	if u == nil {
		return nil
	}
	d := &User{
		ID:             u.ID,
		Email:          u.Email,
		DisplayName:    u.DisplayName,
		Active:         u.Active,
		Age:            u.Age,
		Roles:          u.Roles,
		Metadata:       u.Metadata,
		CreatedAt:      u.CreatedAt,
		SessionTimeout: u.SessionTimeout,
		Phone:          u.Phone,
	}
	if u.Address != nil {
		d.Address = u.Address.ToDomain()
	}
	return d
}

// FromDomain populates from the domain type.
func (u *UserMongo) FromDomain(d *User) {
	if d == nil {
		return
	}
	u.ID = d.ID
	u.Email = d.Email
	u.DisplayName = d.DisplayName
	u.Active = d.Active
	u.Age = d.Age
	u.Roles = d.Roles
	u.Metadata = d.Metadata
	if d.Address != nil {
		u.Address = &AddressMongo{}
		u.Address.FromDomain(d.Address)
	}
	u.CreatedAt = d.CreatedAt
	u.SessionTimeout = d.SessionTimeout
	u.Phone = d.Phone
}

// AddressMongo is the MongoDB storage representation of test.v1.Address.
type AddressMongo struct {
	Street  string `bson:"street,omitempty"`
	City    string `bson:"city,omitempty"`
	State   string `bson:"state,omitempty"`
	Zip     string `bson:"zip,omitempty"`
	Country string `bson:"country,omitempty"`
}

// ToProto converts to the protobuf message.
func (a *AddressMongo) ToProto() *Address {
	if a == nil {
		return nil
	}
	pb := &Address{
		Street:  a.Street,
		City:    a.City,
		State:   a.State,
		Zip:     a.Zip,
		Country: a.Country,
	}
	return pb
}

// FromProto populates from a protobuf message.
func (a *AddressMongo) FromProto(pb *Address) {
	if pb == nil {
		return
	}
	a.Street = pb.Street
	a.City = pb.City
	a.State = pb.State
	a.Zip = pb.Zip
	a.Country = pb.Country
}

// ToDomain converts to the domain type.
func (a *AddressMongo) ToDomain() *Address {
	if a == nil {
		return nil
	}
	d := &Address{
		Street:  a.Street,
		City:    a.City,
		State:   a.State,
		Zip:     a.Zip,
		Country: a.Country,
	}
	return d
}

// FromDomain populates from the domain type.
func (a *AddressMongo) FromDomain(d *Address) {
	if d == nil {
		return
	}
	a.Street = d.Street
	a.City = d.City
	a.State = d.State
	a.Zip = d.Zip
	a.Country = d.Country
}
