// Code generated by proto2type. DO NOT EDIT.
// source: user.proto
// backend: mongo

package _go

import (
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

import "time"

// UserMongo is the MongoDB storage representation of test.v1.User.
type UserMongo struct {
	ID             string            `bson:"id"`
	Email          string            `bson:"email"`
	DisplayName    string            `bson:"display_name"`
	Active         bool              `bson:"active"`
	Age            int32             `bson:"age"`
	Roles          []string          `bson:"roles,omitempty"`
	Metadata       map[string]string `bson:"metadata,omitempty"`
	Address        *Address          `bson:"address,omitempty"`
	CreatedAt      time.Time         `bson:"created_at,omitempty"`
	SessionTimeout time.Duration     `bson:"session_timeout,omitempty"`
	Phone          string            `bson:"phone,omitempty"`
}

// ToProto converts to the protobuf message.
func (d *UserMongo) ToProto() *User {
	if d == nil {
		return nil
	}
	pb := &User{
		Id:          d.ID,
		Email:       d.Email,
		DisplayName: d.DisplayName,
		Active:      d.Active,
		Age:         d.Age,
		Roles:       d.Roles,
		Metadata:    d.Metadata,
		Address:     d.Address,
		Phone:       d.Phone,
	}
	if !d.CreatedAt.IsZero() {
		pb.CreatedAt = timestamppb.New(d.CreatedAt)
	}
	pb.SessionTimeout = durationpb.New(d.SessionTimeout)
	return pb
}

// FromProto populates from a protobuf message.
func (d *UserMongo) FromProto(pb *User) {
	if pb == nil {
		return
	}
	d.ID = pb.Id
	d.Email = pb.Email
	d.DisplayName = pb.DisplayName
	d.Active = pb.Active
	d.Age = pb.Age
	d.Roles = pb.Roles
	d.Metadata = pb.Metadata
	d.Address = pb.Address
	if pb.CreatedAt != nil {
		d.CreatedAt = pb.CreatedAt.AsTime()
	}
	if pb.SessionTimeout != nil {
		d.SessionTimeout = pb.SessionTimeout.AsDuration()
	}
	d.Phone = pb.Phone
}

// ToDomain converts to the domain type.
func (s *UserMongo) ToDomain() *User {
	if s == nil {
		return nil
	}
	d := &User{
		ID:             s.ID,
		Email:          s.Email,
		DisplayName:    s.DisplayName,
		Active:         s.Active,
		Age:            s.Age,
		Roles:          s.Roles,
		Metadata:       s.Metadata,
		Address:        s.Address,
		CreatedAt:      s.CreatedAt,
		SessionTimeout: s.SessionTimeout,
		Phone:          s.Phone,
	}
	return d
}

// FromDomain populates from the domain type.
func (s *UserMongo) FromDomain(d *User) {
	if d == nil {
		return
	}
	s.ID = d.ID
	s.Email = d.Email
	s.DisplayName = d.DisplayName
	s.Active = d.Active
	s.Age = d.Age
	s.Roles = d.Roles
	s.Metadata = d.Metadata
	s.Address = d.Address
	s.CreatedAt = d.CreatedAt
	s.SessionTimeout = d.SessionTimeout
	s.Phone = d.Phone
}

// AddressMongo is the MongoDB storage representation of test.v1.Address.
type AddressMongo struct {
	Street  string `bson:"street"`
	City    string `bson:"city"`
	State   string `bson:"state"`
	Zip     string `bson:"zip"`
	Country string `bson:"country"`
}

// ToProto converts to the protobuf message.
func (d *AddressMongo) ToProto() *Address {
	if d == nil {
		return nil
	}
	pb := &Address{
		Street:  d.Street,
		City:    d.City,
		State:   d.State,
		Zip:     d.Zip,
		Country: d.Country,
	}
	return pb
}

// FromProto populates from a protobuf message.
func (d *AddressMongo) FromProto(pb *Address) {
	if pb == nil {
		return
	}
	d.Street = pb.Street
	d.City = pb.City
	d.State = pb.State
	d.Zip = pb.Zip
	d.Country = pb.Country
}

// ToDomain converts to the domain type.
func (s *AddressMongo) ToDomain() *Address {
	if s == nil {
		return nil
	}
	d := &Address{
		Street:  s.Street,
		City:    s.City,
		State:   s.State,
		Zip:     s.Zip,
		Country: s.Country,
	}
	return d
}

// FromDomain populates from the domain type.
func (s *AddressMongo) FromDomain(d *Address) {
	if d == nil {
		return
	}
	s.Street = d.Street
	s.City = d.City
	s.State = d.State
	s.Zip = d.Zip
	s.Country = d.Country
}
