// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/proto2type/options.proto

package proto2type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptionalBool int32

const (
	OptionalBool_OPTIONAL_BOOL_UNSPECIFIED OptionalBool = 0
	OptionalBool_OPTIONAL_BOOL_TRUE        OptionalBool = 1
	OptionalBool_OPTIONAL_BOOL_FALSE       OptionalBool = 2
)

// Enum value maps for OptionalBool.
var (
	OptionalBool_name = map[int32]string{
		0: "OPTIONAL_BOOL_UNSPECIFIED",
		1: "OPTIONAL_BOOL_TRUE",
		2: "OPTIONAL_BOOL_FALSE",
	}
	OptionalBool_value = map[string]int32{
		"OPTIONAL_BOOL_UNSPECIFIED": 0,
		"OPTIONAL_BOOL_TRUE":        1,
		"OPTIONAL_BOOL_FALSE":       2,
	}
)

func (x OptionalBool) Enum() *OptionalBool {
	p := new(OptionalBool)
	*p = x
	return p
}

func (x OptionalBool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionalBool) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto2type_options_proto_enumTypes[0].Descriptor()
}

func (OptionalBool) Type() protoreflect.EnumType {
	return &file_proto_proto2type_options_proto_enumTypes[0]
}

func (x OptionalBool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptionalBool.Descriptor instead.
func (OptionalBool) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto2type_options_proto_rawDescGZIP(), []int{0}
}

type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Skip generating types for this message.
	Skip          bool `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_proto_proto2type_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto2type_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_proto_proto2type_options_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mark as document ID field.
	// Firestore: excluded from struct (ID is doc path).
	// Mongo: tagged bson:"_id".
	DocumentId bool `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// Server-managed timestamp (Firestore serverTimestamp).
	ServerTimestamp bool `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	// Override the storage field name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Exclude from generated types entirely.
	Skip bool `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	// Force omitempty behavior.
	Omitempty OptionalBool `protobuf:"varint,5,opt,name=omitempty,proto3,enum=proto2type.OptionalBool" json:"omitempty,omitempty"`
	// Flatten nested message fields into parent (Mongo: bson:",inline").
	Inline bool `protobuf:"varint,6,opt,name=inline,proto3" json:"inline,omitempty"`
	// Store this enum field as its string name instead of int32.
	// Per-field override for the global enum_as_string plugin option.
	EnumAsString  OptionalBool `protobuf:"varint,7,opt,name=enum_as_string,json=enumAsString,proto3,enum=proto2type.OptionalBool" json:"enum_as_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_proto_proto2type_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto2type_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_proto_proto2type_options_proto_rawDescGZIP(), []int{1}
}

func (x *FieldOptions) GetDocumentId() bool {
	if x != nil {
		return x.DocumentId
	}
	return false
}

func (x *FieldOptions) GetServerTimestamp() bool {
	if x != nil {
		return x.ServerTimestamp
	}
	return false
}

func (x *FieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

func (x *FieldOptions) GetOmitempty() OptionalBool {
	if x != nil {
		return x.Omitempty
	}
	return OptionalBool_OPTIONAL_BOOL_UNSPECIFIED
}

func (x *FieldOptions) GetInline() bool {
	if x != nil {
		return x.Inline
	}
	return false
}

func (x *FieldOptions) GetEnumAsString() OptionalBool {
	if x != nil {
		return x.EnumAsString
	}
	return OptionalBool_OPTIONAL_BOOL_UNSPECIFIED
}

var file_proto_proto2type_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         1307,
		Name:          "proto2type.message",
		Tag:           "bytes,1307,opt,name=message",
		Filename:      "proto/proto2type/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         1307,
		Name:          "proto2type.field",
		Tag:           "bytes,1307,opt,name=field",
		Filename:      "proto/proto2type/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional proto2type.MessageOptions message = 1307;
	E_Message = &file_proto_proto2type_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional proto2type.FieldOptions field = 1307;
	E_Field = &file_proto_proto2type_options_proto_extTypes[1]
)

var File_proto_proto2type_options_proto protoreflect.FileDescriptor

const file_proto_proto2type_options_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/proto2type/options.proto\x12\n" +
	"proto2type\x1a google/protobuf/descriptor.proto\"$\n" +
	"\x0eMessageOptions\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\bR\x04skip\"\x92\x02\n" +
	"\fFieldOptions\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\bR\n" +
	"documentId\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\bR\x0fserverTimestamp\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\bR\x04skip\x126\n" +
	"\tomitempty\x18\x05 \x01(\x0e2\x18.proto2type.OptionalBoolR\tomitempty\x12\x16\n" +
	"\x06inline\x18\x06 \x01(\bR\x06inline\x12>\n" +
	"\x0eenum_as_string\x18\a \x01(\x0e2\x18.proto2type.OptionalBoolR\fenumAsString*^\n" +
	"\fOptionalBool\x12\x1d\n" +
	"\x19OPTIONAL_BOOL_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12OPTIONAL_BOOL_TRUE\x10\x01\x12\x17\n" +
	"\x13OPTIONAL_BOOL_FALSE\x10\x02:V\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\x9b\n" +
	" \x01(\v2\x1a.proto2type.MessageOptionsR\amessage:N\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\x9b\n" +
	" \x01(\v2\x18.proto2type.FieldOptionsR\x05fieldB2Z0github.com/protocgen/proto2type/proto/proto2typeb\x06proto3"

var (
	file_proto_proto2type_options_proto_rawDescOnce sync.Once
	file_proto_proto2type_options_proto_rawDescData []byte
)

func file_proto_proto2type_options_proto_rawDescGZIP() []byte {
	file_proto_proto2type_options_proto_rawDescOnce.Do(func() {
		file_proto_proto2type_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto2type_options_proto_rawDesc), len(file_proto_proto2type_options_proto_rawDesc)))
	})
	return file_proto_proto2type_options_proto_rawDescData
}

var file_proto_proto2type_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto2type_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_proto2type_options_proto_goTypes = []any{
	(OptionalBool)(0),                   // 0: proto2type.OptionalBool
	(*MessageOptions)(nil),              // 1: proto2type.MessageOptions
	(*FieldOptions)(nil),                // 2: proto2type.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_proto_proto2type_options_proto_depIdxs = []int32{
	0, // 0: proto2type.FieldOptions.omitempty:type_name -> proto2type.OptionalBool
	0, // 1: proto2type.FieldOptions.enum_as_string:type_name -> proto2type.OptionalBool
	3, // 2: proto2type.message:extendee -> google.protobuf.MessageOptions
	4, // 3: proto2type.field:extendee -> google.protobuf.FieldOptions
	1, // 4: proto2type.message:type_name -> proto2type.MessageOptions
	2, // 5: proto2type.field:type_name -> proto2type.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_proto2type_options_proto_init() }
func file_proto_proto2type_options_proto_init() {
	if File_proto_proto2type_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto2type_options_proto_rawDesc), len(file_proto_proto2type_options_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto2type_options_proto_goTypes,
		DependencyIndexes: file_proto_proto2type_options_proto_depIdxs,
		EnumInfos:         file_proto_proto2type_options_proto_enumTypes,
		MessageInfos:      file_proto_proto2type_options_proto_msgTypes,
		ExtensionInfos:    file_proto_proto2type_options_proto_extTypes,
	}.Build()
	File_proto_proto2type_options_proto = out.File
	file_proto_proto2type_options_proto_goTypes = nil
	file_proto_proto2type_options_proto_depIdxs = nil
}
