package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"

	proto2typepb "github.com/protocgen/proto2type/proto/proto2type"
)

// generateGo generates Go output files for a proto file.
func generateGo(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	// Generate domain types if requested.
	if opts.Domain {
		if err := generateGoDomain(gen, file, opts); err != nil {
			return err
		}
	}

	// Generate storage types if a backend is specified.
	if opts.Backend != "" {
		switch opts.Backend {
		case "firestore":
			return generateGoFirestore(gen, file, opts)
		case "mongo":
			return generateGoMongo(gen, file, opts)
		default:
			return fmt.Errorf("proto2type: unsupported Go backend %q (supported: firestore, mongo)", opts.Backend)
		}
	}

	return nil
}

// generateGoDomain generates a Go domain type file for a proto file.
func generateGoDomain(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, ".type.go")

	// Determine the Go import path and package name for generated types.
	goImportPath := file.GoImportPath
	goPackageName := file.GoPackageName
	if opts.GoPackage != "" {
		// Parse "import/path;package_name" or just "import/path"
		importPath, pkgName := parseGoPackage(opts.GoPackage)
		goImportPath = protogen.GoImportPath(importPath)
		goPackageName = protogen.GoPackageName(pkgName)
		filename = adjustSubdirFilename(filename, string(file.GoImportPath), importPath)
	}

	// Collision check: domain types cannot share the same Go import path as
	// proto types because both define structs with the same name (e.g.,
	// ModelCatalogEntry). This would cause a compile error.
	if goImportPath == file.GoImportPath {
		return fmt.Errorf(
			"proto2type: generated domain types would collide with proto types in package %s\n"+
				"Both define types with the same names (e.g., %s).\n"+
				"Set the go_package option to a different import path, for example:\n"+
				"  opt: go_package=%s/domain;domain",
			string(file.GoImportPath),
			file.Messages[0].GoIdent.GoName,
			string(file.GoImportPath),
		)
	}

	// Build IR from the proto file.
	df := BuildDomainFile(file, opts)

	g := gen.NewGeneratedFile(filename, goImportPath)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", goPackageName)
	g.P()

	if irNeedsTime(df.Messages) {
		g.P(`import "time"`)
		g.P()
	}

	// Build a lookup from FullName -> *protogen.Message for converter generation.
	protoMsgMap := buildProtoMessageMap(file.Messages)

	for _, dm := range df.Messages {
		msg := protoMsgMap[dm.FullName]
		if err := generateGoDomainMessage(g, dm, msg, opts); err != nil {
			return err
		}
	}

	return nil
}

// generateGoDomainMessage generates a Go domain struct and converters for a single message.
func generateGoDomainMessage(g *protogen.GeneratedFile, dm *DomainMessage, msg *protogen.Message, opts *Options) error {
	if dm.Skip {
		return nil
	}

	name := dm.Name

	// Struct definition
	g.P("// ", name, " is the domain representation of ", dm.FullName, ".")
	if dm.Comment != "" {
		g.P("//")
		for _, line := range strings.Split(dm.Comment, "\n") {
			g.P("// ", strings.TrimPrefix(line, " "))
		}
	}
	g.P("type ", name, " struct {")

	for _, f := range dm.Fields {
		fieldName := f.PascalName
		fieldType := goDomainFieldTypeFromIR(f)

		jsonName := f.Name
		jsonTag := jsonName
		if f.Omitempty {
			jsonTag += ",omitempty"
		}

		g.P("\t", fieldName, " ", fieldType, " `json:\"", jsonTag, "\"`")
	}

	g.P("}")
	g.P()

	// Generate ToProto and FromProto converters (still uses *protogen.Message)
	generateConverters(g, msg, "", opts)

	// Generate ApplyFieldMask function
	generateGoFieldMask(g, msg)

	// Generate Clone method (deep copy)
	generateGoClone(g, msg, opts)

	// Generate Equal method (field-by-field comparison)
	generateGoEqual(g, msg, opts)

	// Generate nested messages
	// Build a lookup for nested protogen messages.
	nestedProtoMap := buildProtoMessageMap(msg.Messages)
	for _, nestedDM := range dm.NestedMessages {
		nestedMsg := nestedProtoMap[nestedDM.FullName]
		if err := generateGoDomainMessage(g, nestedDM, nestedMsg, opts); err != nil {
			return err
		}
	}

	return nil
}

// goDomainFieldTypeFromIR returns the Go type for a field using the IR.
func goDomainFieldTypeFromIR(f *DomainField) string {
	// Handle repeated fields
	if f.Repeated {
		return "[]" + goDomainSingularTypeFromIR(f)
	}

	// Handle map fields
	if f.IsMap {
		keyType := goType(f.MapKey.ScalarKind)
		valType := goMapValueTypeFromIR(f.MapValue)
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	}

	return goDomainSingularTypeFromIR(f)
}

// goDomainSingularTypeFromIR returns the Go type for a singular field using the IR.
func goDomainSingularTypeFromIR(f *DomainField) string {
	switch f.Kind {
	case FieldKindTimestamp:
		return "time.Time"
	case FieldKindDuration:
		return "time.Duration"
	case FieldKindMessage:
		return "*" + f.MessageTypeName
	case FieldKindEnum:
		if f.EnumAsString {
			return "string"
		}
		return "int32"
	case FieldKindScalar:
		if f.Optional {
			return "*" + goType(f.ScalarKind)
		}
		return goType(f.ScalarKind)
	}

	// Wrapper types
	if f.Kind.IsWrapper() {
		return wrapperGoTypeFromIR(f.Kind)
	}

	return goType(f.ScalarKind)
}

// wrapperGoTypeFromIR returns the Go pointer type for a wrapper FieldKind.
func wrapperGoTypeFromIR(kind FieldKind) string {
	switch kind {
	case FieldKindWrapperBool:
		return "*bool"
	case FieldKindWrapperInt32:
		return "*int32"
	case FieldKindWrapperInt64:
		return "*int64"
	case FieldKindWrapperUInt32:
		return "*uint32"
	case FieldKindWrapperUInt64:
		return "*uint64"
	case FieldKindWrapperFloat:
		return "*float32"
	case FieldKindWrapperDouble:
		return "*float64"
	case FieldKindWrapperString:
		return "*string"
	case FieldKindWrapperBytes:
		return "*[]byte"
	default:
		return "any"
	}
}

// goMapValueTypeFromIR returns the Go type for a map value using MapTypeInfo.
func goMapValueTypeFromIR(mv *MapTypeInfo) string {
	switch mv.Kind {
	case FieldKindMessage:
		return "*" + mv.MessageTypeName
	case FieldKindEnum:
		return "int32"
	case FieldKindScalar:
		return goType(mv.ScalarKind)
	default:
		return goType(mv.ScalarKind)
	}
}

// irNeedsTime returns true if any message field uses Timestamp or Duration.
func irNeedsTime(msgs []*DomainMessage) bool {
	for _, m := range msgs {
		if m.Skip {
			continue
		}
		for _, f := range m.Fields {
			if f.Kind == FieldKindTimestamp || f.Kind == FieldKindDuration {
				return true
			}
		}
		if irNeedsTime(m.NestedMessages) {
			return true
		}
	}
	return false
}

// buildProtoMessageMap builds a map from FullName to *protogen.Message, recursively.
func buildProtoMessageMap(msgs []*protogen.Message) map[string]*protogen.Message {
	m := make(map[string]*protogen.Message)
	for _, msg := range msgs {
		m[string(msg.Desc.FullName())] = msg
		for k, v := range buildProtoMessageMap(msg.Messages) {
			m[k] = v
		}
	}
	return m
}

// goDomainFieldType returns the Go type for a proto field in a domain struct.
// Used by converter generation (go_clone_equal.go).
func goDomainFieldType(field *protogen.Field, opts *Options) string {
	// Handle repeated fields
	if field.Desc.IsList() {
		return "[]" + goDomainSingularType(field, opts)
	}

	// Handle map fields
	if field.Desc.IsMap() {
		keyType := goType(field.Desc.MapKey().Kind())
		valType := goType(field.Desc.MapValue().Kind())
		if field.Desc.MapValue().Kind() == protoreflect.MessageKind {
			valType = "*" + toPascalCase(string(field.Desc.MapValue().Message().Name()))
		}
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	}

	return goDomainSingularType(field, opts)
}

// goDomainSingularType returns the Go type for a singular (non-repeated, non-map) field.
// Used by converter generation (go_clone_equal.go).
func goDomainSingularType(field *protogen.Field, opts *Options) string {
	// Well-known types
	if isWellKnownTimestamp(field) {
		return "time.Time"
	}
	if isWellKnownDuration(field) {
		return "time.Duration"
	}

	// Well-known wrapper types (e.g. google.protobuf.StringValue -> *string)
	if isWellKnownWrapper(field) {
		return wrapperGoType(field)
	}

	// Message types (nested)
	if field.Desc.Kind() == protoreflect.MessageKind {
		return "*" + toPascalCase(string(field.Desc.Message().Name()))
	}

	// Enum types
	if field.Desc.Kind() == protoreflect.EnumKind {
		if isEnumAsString(field, opts) {
			return "string"
		}
		return "int32"
	}

	// proto3 optional scalars -> pointer types
	if field.Desc.HasOptionalKeyword() {
		return "*" + goType(field.Desc.Kind())
	}

	// Scalar types
	return goType(field.Desc.Kind())
}

// goStorageFieldType returns the Go type for a proto field in a storage struct.
// It appends the given suffix to nested message type names.
func goStorageFieldType(field *protogen.Field, suffix string, opts *Options) string {
	// Handle repeated fields
	if field.Desc.IsList() {
		return "[]" + goStorageSingularType(field, suffix, opts)
	}

	// Handle map fields
	if field.Desc.IsMap() {
		keyType := goType(field.Desc.MapKey().Kind())
		valType := goType(field.Desc.MapValue().Kind())
		if field.Desc.MapValue().Kind() == protoreflect.MessageKind {
			valType = "*" + toPascalCase(string(field.Desc.MapValue().Message().Name())) + suffix
		}
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	}

	return goStorageSingularType(field, suffix, opts)
}

// goStorageSingularType returns the Go type for a singular field in a storage struct,
// appending the given suffix to nested message type names.
func goStorageSingularType(field *protogen.Field, suffix string, opts *Options) string {
	// Well-known types
	if isWellKnownTimestamp(field) {
		return "time.Time"
	}
	if isWellKnownDuration(field) {
		return "time.Duration"
	}

	// Well-known wrapper types (e.g. google.protobuf.StringValue -> *string)
	if isWellKnownWrapper(field) {
		return wrapperGoType(field)
	}

	// Message types (nested) — apply suffix
	if field.Desc.Kind() == protoreflect.MessageKind {
		return "*" + toPascalCase(string(field.Desc.Message().Name())) + suffix
	}

	// Enum types
	if field.Desc.Kind() == protoreflect.EnumKind {
		if isEnumAsString(field, opts) {
			return "string"
		}
		return "int32"
	}

	// proto3 optional scalars -> pointer types
	if field.Desc.HasOptionalKeyword() {
		return "*" + goType(field.Desc.Kind())
	}

	// Scalar types
	return goType(field.Desc.Kind())
}

// shouldOmitempty returns true if a field should have the omitempty tag.
func shouldOmitempty(field *protogen.Field, opts *Options) bool {
	// Check proto2type.field options for explicit omitempty setting.
	switch fieldOmitempty(field) {
	case proto2typepb.OptionalBool_OPTIONAL_BOOL_TRUE:
		return true
	case proto2typepb.OptionalBool_OPTIONAL_BOOL_FALSE:
		return false
	}

	// proto3 optional fields get omitempty
	if field.Desc.HasOptionalKeyword() {
		return true
	}

	// Repeated and map fields get omitempty (empty slice/map)
	if field.Desc.IsList() || field.Desc.IsMap() {
		return true
	}

	// Message fields get omitempty (nil pointer)
	if field.Desc.Kind() == protoreflect.MessageKind {
		return true
	}

	// Default behavior from options
	if opts.OmitemptyDefault {
		return true
	}
	return false
}
