package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"

	proto2typepb "github.com/protocgen/proto2type/proto/proto2type"
)

// generateGo generates Go output files for a proto file.
func generateGo(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	// Generate domain types if requested.
	if opts.Domain {
		if err := generateGoDomain(gen, file, opts); err != nil {
			return err
		}
	}

	// Generate storage types if a backend is specified.
	if opts.Backend != "" {
		switch opts.Backend {
		case "firestore":
			return generateGoFirestore(gen, file, opts)
		case "mongo":
			return generateGoMongo(gen, file, opts)
		default:
			return fmt.Errorf("proto2type: unsupported Go backend %q (supported: firestore, mongo)", opts.Backend)
		}
	}

	return nil
}

// generateGoDomain generates a Go domain type file for a proto file.
func generateGoDomain(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, ".type.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	needsTime := false
	for _, msg := range file.Messages {
		for _, field := range msg.Fields {
			if isWellKnownTimestamp(field) || isWellKnownDuration(field) {
				needsTime = true
				break
			}
		}
	}
	if needsTime {
		g.P(`import "time"`)
		g.P()
	}

	for _, msg := range file.Messages {
		if err := generateGoDomainMessage(g, msg, opts); err != nil {
			return err
		}
	}

	return nil
}

// generateGoDomainMessage generates a Go domain struct and converters for a single message.
func generateGoDomainMessage(g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) error {
	if isMessageSkipped(msg) {
		return nil
	}

	name := msg.GoIdent.GoName

	// Struct definition
	g.P("// ", name, " is the domain representation of ", msg.Desc.FullName(), ".")
	if msg.Comments.Leading != "" {
		g.P("//")
		for _, line := range strings.Split(strings.TrimSpace(string(msg.Comments.Leading)), "\n") {
			g.P("// ", strings.TrimPrefix(line, " "))
		}
	}
	g.P("type ", name, " struct {")

	for _, field := range msg.Fields {
		// Skip oneof synthetic fields (handle the oneof group instead)
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}
		if isFieldSkipped(field) {
			continue
		}

		fieldName := toPascalCase(string(field.Desc.Name()))
		fieldType := goDomainFieldType(field)

		jsonName := string(field.Desc.Name())
		jsonTag := jsonName
		if shouldOmitempty(field, opts) {
			jsonTag += ",omitempty"
		}

		g.P("\t", fieldName, " ", fieldType, " `json:\"", jsonTag, "\"`")
	}

	g.P("}")
	g.P()

	// Generate ToProto and FromProto converters
	generateConverters(g, msg, "")

	// Generate ApplyFieldMask function
	generateGoFieldMask(g, msg)

	// Generate nested messages
	for _, nested := range msg.Messages {
		// Skip map entry messages
		if nested.Desc.IsMapEntry() {
			continue
		}
		if err := generateGoDomainMessage(g, nested, opts); err != nil {
			return err
		}
	}

	return nil
}

// goDomainFieldType returns the Go type for a proto field in a domain struct.
func goDomainFieldType(field *protogen.Field) string {
	// Handle repeated fields
	if field.Desc.IsList() {
		return "[]" + goDomainSingularType(field)
	}

	// Handle map fields
	if field.Desc.IsMap() {
		keyType := goType(field.Desc.MapKey().Kind())
		valType := goType(field.Desc.MapValue().Kind())
		if field.Desc.MapValue().Kind() == protoreflect.MessageKind {
			valType = "*" + toPascalCase(string(field.Desc.MapValue().Message().Name()))
		}
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	}

	return goDomainSingularType(field)
}

// goDomainSingularType returns the Go type for a singular (non-repeated, non-map) field.
func goDomainSingularType(field *protogen.Field) string {
	// Well-known types
	if isWellKnownTimestamp(field) {
		return "time.Time"
	}
	if isWellKnownDuration(field) {
		return "time.Duration"
	}

	// Well-known wrapper types (e.g. google.protobuf.StringValue -> *string)
	if isWellKnownWrapper(field) {
		return wrapperGoType(field)
	}

	// Message types (nested)
	if field.Desc.Kind() == protoreflect.MessageKind {
		return "*" + toPascalCase(string(field.Desc.Message().Name()))
	}

	// Enum types
	if field.Desc.Kind() == protoreflect.EnumKind {
		return "int32" // TODO: support enum_as_string option
	}

	// proto3 optional scalars -> pointer types
	if field.Desc.HasOptionalKeyword() {
		return "*" + goType(field.Desc.Kind())
	}

	// Scalar types
	return goType(field.Desc.Kind())
}

// goStorageFieldType returns the Go type for a proto field in a storage struct.
// It appends the given suffix to nested message type names.
func goStorageFieldType(field *protogen.Field, suffix string) string {
	// Handle repeated fields
	if field.Desc.IsList() {
		return "[]" + goStorageSingularType(field, suffix)
	}

	// Handle map fields
	if field.Desc.IsMap() {
		keyType := goType(field.Desc.MapKey().Kind())
		valType := goType(field.Desc.MapValue().Kind())
		if field.Desc.MapValue().Kind() == protoreflect.MessageKind {
			valType = "*" + toPascalCase(string(field.Desc.MapValue().Message().Name())) + suffix
		}
		return fmt.Sprintf("map[%s]%s", keyType, valType)
	}

	return goStorageSingularType(field, suffix)
}

// goStorageSingularType returns the Go type for a singular field in a storage struct,
// appending the given suffix to nested message type names.
func goStorageSingularType(field *protogen.Field, suffix string) string {
	// Well-known types
	if isWellKnownTimestamp(field) {
		return "time.Time"
	}
	if isWellKnownDuration(field) {
		return "time.Duration"
	}

	// Well-known wrapper types (e.g. google.protobuf.StringValue -> *string)
	if isWellKnownWrapper(field) {
		return wrapperGoType(field)
	}

	// Message types (nested) — apply suffix
	if field.Desc.Kind() == protoreflect.MessageKind {
		return "*" + toPascalCase(string(field.Desc.Message().Name())) + suffix
	}

	// Enum types
	if field.Desc.Kind() == protoreflect.EnumKind {
		return "int32" // TODO: support enum_as_string option
	}

	// proto3 optional scalars -> pointer types
	if field.Desc.HasOptionalKeyword() {
		return "*" + goType(field.Desc.Kind())
	}

	// Scalar types
	return goType(field.Desc.Kind())
}

// shouldOmitempty returns true if a field should have the omitempty tag.
func shouldOmitempty(field *protogen.Field, opts *Options) bool {
	// Check proto2type.field options for explicit omitempty setting.
	switch fieldOmitempty(field) {
	case proto2typepb.OptionalBool_OPTIONAL_BOOL_TRUE:
		return true
	case proto2typepb.OptionalBool_OPTIONAL_BOOL_FALSE:
		return false
	}

	// proto3 optional fields get omitempty
	if field.Desc.HasOptionalKeyword() {
		return true
	}

	// Repeated and map fields get omitempty (empty slice/map)
	if field.Desc.IsList() || field.Desc.IsMap() {
		return true
	}

	// Message fields get omitempty (nil pointer)
	if field.Desc.Kind() == protoreflect.MessageKind {
		return true
	}

	// Default behavior from options
	if opts.OmitemptyDefault {
		return true
	}
	return false
}
