package generator

import (
	"google.golang.org/protobuf/compiler/protogen"
)

// generateGoFirestore generates a Go Firestore storage type file.
func generateGoFirestore(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, "_firestore.type.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: firestore")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	needsTime := false
	for _, msg := range file.Messages {
		for _, field := range msg.Fields {
			if isWellKnownTimestamp(field) || isWellKnownDuration(field) {
				needsTime = true
				break
			}
		}
	}
	if needsTime {
		g.P(`import "time"`)
		g.P()
	}

	for _, msg := range file.Messages {
		generateGoFirestoreMessage(g, msg, opts)
	}

	return nil
}

// generateGoFirestoreMessage generates a Firestore storage struct for a message.
func generateGoFirestoreMessage(g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) {
	name := msg.GoIdent.GoName + "Firestore"

	g.P("// ", name, " is the Firestore storage representation of ", msg.Desc.FullName(), ".")
	g.P("type ", name, " struct {")

	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}

		// TODO: check for document_id option — skip if so (Firestore uses doc path)

		fieldName := toPascalCase(string(field.Desc.Name()))
		fieldType := goDomainFieldType(field)

		// Build firestore tag
		fsName := storageFieldName(string(field.Desc.Name()))
		fsTag := fsName

		// TODO: check for server_timestamp option
		if isWellKnownTimestamp(field) {
			// Default: omitempty for timestamps
			fsTag += ",omitempty"
		} else if shouldOmitempty(field, opts) {
			fsTag += ",omitempty"
		}

		g.P("\t", fieldName, " ", fieldType, " `firestore:\"", fsTag, "\"`")
	}

	g.P("}")
	g.P()

	// Generate ToProto and FromProto converters
	generateConverters(g, msg, "Firestore")

	// Nested messages
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		generateGoFirestoreMessage(g, nested, opts)
	}
}
