package generator

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"

	proto2typepb "github.com/protocgen/proto2type/proto/proto2type"
)

// generateGoFirestore generates a Go Firestore storage type file.
func generateGoFirestore(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, "_firestore.type.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: firestore")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	needsTime := false
	for _, msg := range file.Messages {
		for _, field := range msg.Fields {
			if isWellKnownTimestamp(field) || isWellKnownDuration(field) {
				needsTime = true
				break
			}
		}
	}
	if needsTime {
		g.P(`import "time"`)
		g.P()
	}

	for _, msg := range file.Messages {
		generateGoFirestoreMessage(gen, g, msg, opts)
	}

	return nil
}

// generateGoFirestoreMessage generates a Firestore storage struct for a message.
func generateGoFirestoreMessage(gen *protogen.Plugin, g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) {
	if isMessageSkipped(msg) {
		return
	}

	name := msg.GoIdent.GoName + "Firestore"

	g.P("// ", name, " is the Firestore storage representation of ", msg.Desc.FullName(), ".")
	g.P("type ", name, " struct {")

	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		// Firestore uses the document path as ID — skip document_id fields from struct
		if isDocumentID(field) {
			continue
		}

		fieldName := toPascalCase(string(field.Desc.Name()))
		fieldType := goStorageFieldType(field, "Firestore")

		// Build firestore tag
		fsName := storageFieldName(string(field.Desc.Name()))
		if override := fieldNameOverride(field); override != "" {
			// Validate the override name (SEC-2)
			if errMsg := validateFieldNameOverride(override); errMsg != "" {
				gen.Error(fmt.Errorf("field %s in %s: %s", field.Desc.Name(), msg.Desc.FullName(), errMsg))
				continue
			}
			fsName = override
		}
		fsTag := fsName

		if isServerTimestamp(field) {
			fsTag += ",serverTimestamp"
		} else {
			// Check explicit omitempty option first
			switch fieldOmitempty(field) {
			case proto2typepb.OptionalBool_OPTIONAL_BOOL_TRUE:
				fsTag += ",omitempty"
			case proto2typepb.OptionalBool_OPTIONAL_BOOL_FALSE:
				// Explicit false: no omitempty
			default:
				if isWellKnownTimestamp(field) {
					// Default: omitempty for timestamps
					fsTag += ",omitempty"
				} else if shouldOmitempty(field, opts) {
					fsTag += ",omitempty"
				}
			}
		}

		g.P("\t", fieldName, " ", fieldType, " `firestore:\"", fsTag, "\"`")
	}

	g.P("}")
	g.P()

	// Generate ToProto and FromProto converters
	generateConverters(g, msg, "Firestore")

	// Generate ToDomain and FromDomain converters
	generateDomainConverters(g, msg, "Firestore")

	// Nested messages
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		generateGoFirestoreMessage(gen, g, nested, opts)
	}
}
