package generator

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateGoFirestore generates a Go Firestore storage type file.
func generateGoFirestore(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, "_firestore.type.go")

	goImportPath := file.GoImportPath
	goPackageName := file.GoPackageName
	if opts.GoPackage != "" {
		importPath, pkgName := parseGoPackage(opts.GoPackage)
		goImportPath = protogen.GoImportPath(importPath)
		goPackageName = protogen.GoPackageName(pkgName)
		filename = adjustSubdirFilename(filename, string(file.GoImportPath), importPath)
	}
	g := gen.NewGeneratedFile(filename, goImportPath)

	// Build IR for import scanning.
	df := BuildDomainFile(file, opts)

	// Build a lookup from FullName -> *protogen.Message for converter generation.
	protoMsgMap := buildProtoMessageMap(file.Messages)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: firestore")
	g.P()
	g.P("package ", goPackageName)
	g.P()

	if irNeedsTime(df.Messages) {
		g.P(`import "time"`)
		g.P()
	}

	for _, dm := range df.Messages {
		msg := protoMsgMap[dm.FullName]
		if msg == nil {
			return fmt.Errorf("proto2type: no protogen.Message found for IR message %q", dm.FullName)
		}
		generateGoFirestoreMessage(gen, g, dm, msg, protoMsgMap, opts)
	}

	return nil
}

// generateGoFirestoreMessage generates a Firestore storage struct for a message.
func generateGoFirestoreMessage(gen *protogen.Plugin, g *protogen.GeneratedFile, dm *DomainMessage, msg *protogen.Message, protoMsgMap map[string]*protogen.Message, opts *Options) {
	if dm.Skip {
		return
	}

	name := dm.Name + "Firestore"

	g.P("// ", name, " is the Firestore storage representation of ", dm.FullName, ".")
	g.P("type ", name, " struct {")

	for _, f := range dm.Fields {
		if f.IsOneof {
			continue
		}
		// Firestore uses the document path as ID — skip document_id fields from struct
		if f.DocID {
			continue
		}

		fieldName := f.PascalName
		fieldType := goStorageFieldTypeFromIR(f, "Firestore")

		// Build firestore tag
		fsName := storageFieldName(f.Name)
		if f.NameOverride != "" {
			// Validate the override name (SEC-2)
			if errMsg := validateFieldNameOverride(f.NameOverride); errMsg != "" {
				gen.Error(fmt.Errorf("field %s in %s: %s", f.Name, dm.FullName, errMsg))
				continue
			}
			fsName = f.NameOverride
		}
		fsTag := fsName

		if f.ServerTimestamp {
			fsTag += ",serverTimestamp"
		} else if f.Omitempty {
			fsTag += ",omitempty"
		}

		g.P("\t", fieldName, " ", fieldType, " `firestore:\"", fsTag, "\"`")
	}

	g.P("}")
	g.P()

	// Generate ToProto and FromProto converters
	generateConverters(g, msg, "Firestore", opts)

	// Generate ToDomain and FromDomain converters
	generateDomainConverters(g, msg, "Firestore")

	// Nested messages
	for _, nested := range dm.NestedMessages {
		nestedMsg := protoMsgMap[nested.FullName]
		if nestedMsg == nil {
			gen.Error(fmt.Errorf("proto2type: no proto message found for nested %s", nested.FullName))
			continue
		}
		generateGoFirestoreMessage(gen, g, nested, nestedMsg, protoMsgMap, opts)
	}
}
