package generator

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"

	proto2typepb "github.com/protocgen/proto2type/proto/proto2type"
)

// generateGoMongo generates a Go MongoDB storage type file.
func generateGoMongo(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, "_mongo.type.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: mongo")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	needsTime := false
	for _, msg := range file.Messages {
		for _, field := range msg.Fields {
			if isWellKnownTimestamp(field) || isWellKnownDuration(field) {
				needsTime = true
				break
			}
		}
	}
	if needsTime {
		g.P(`import "time"`)
		g.P()
	}

	for _, msg := range file.Messages {
		generateGoMongoMessage(gen, g, msg, opts)
	}

	return nil
}

// generateGoMongoMessage generates a MongoDB storage struct for a message.
func generateGoMongoMessage(gen *protogen.Plugin, g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) {
	if isMessageSkipped(msg) {
		return
	}

	name := msg.GoIdent.GoName + "Mongo"

	g.P("// ", name, " is the MongoDB storage representation of ", msg.Desc.FullName(), ".")
	g.P("type ", name, " struct {")

	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}
		if isFieldSkipped(field) {
			continue
		}

		fieldName := toPascalCase(string(field.Desc.Name()))
		fieldType := goStorageFieldType(field, "Mongo")

		// Build bson tag
		var bsonTag string
		if isDocumentID(field) {
			bsonTag = "_id"
		} else if isInline(field) {
			bsonTag = ",inline"
		} else {
			bsonName := storageFieldName(string(field.Desc.Name()))
			if override := fieldNameOverride(field); override != "" {
				// Validate the override name (SEC-2)
				if errMsg := validateFieldNameOverride(override); errMsg != "" {
					gen.Error(fmt.Errorf("field %s in %s: %s", field.Desc.Name(), msg.Desc.FullName(), errMsg))
					continue
				}
				bsonName = override
			}
			bsonTag = bsonName

			// Check explicit omitempty option first
			switch fieldOmitempty(field) {
			case proto2typepb.OptionalBool_OPTIONAL_BOOL_TRUE:
				bsonTag += ",omitempty"
			case proto2typepb.OptionalBool_OPTIONAL_BOOL_FALSE:
				// Explicit false: no omitempty
			default:
				if shouldOmitempty(field, opts) {
					bsonTag += ",omitempty"
				}
			}
		}

		g.P("\t", fieldName, " ", fieldType, " `bson:\"", bsonTag, "\"`")
	}

	g.P("}")
	g.P()

	// Generate ToProto and FromProto converters
	generateConverters(g, msg, "Mongo")

	// Generate ToDomain and FromDomain converters
	generateDomainConverters(g, msg, "Mongo")

	// Nested messages
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		generateGoMongoMessage(gen, g, nested, opts)
	}
}
