package generator

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateGoMongo generates a Go MongoDB storage type file.
func generateGoMongo(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, "_mongo.type.go")

	goImportPath := file.GoImportPath
	goPackageName := file.GoPackageName
	if opts.GoPackage != "" {
		importPath, pkgName := parseGoPackage(opts.GoPackage)
		goImportPath = protogen.GoImportPath(importPath)
		goPackageName = protogen.GoPackageName(pkgName)
		filename = adjustSubdirFilename(filename, string(file.GoImportPath), importPath)
	}
	g := gen.NewGeneratedFile(filename, goImportPath)

	// Build IR for import scanning.
	df := BuildDomainFile(file, opts)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: mongo")
	g.P()
	g.P("package ", goPackageName)
	g.P()

	if irNeedsTime(df.Messages) {
		g.P(`import "time"`)
		g.P()
	}

	for _, dm := range df.Messages {
		generateGoMongoMessage(gen, g, dm, opts)
	}

	return nil
}

// generateGoMongoMessage generates a MongoDB storage struct for a message.
func generateGoMongoMessage(gen *protogen.Plugin, g *protogen.GeneratedFile, dm *DomainMessage, opts *Options) {
	if dm.Skip {
		return
	}

	name := dm.Name + "Mongo"

	g.P("// ", name, " is the MongoDB storage representation of ", dm.FullName, ".")
	g.P("type ", name, " struct {")

	for _, f := range dm.Fields {
		if f.IsOneof {
			continue
		}

		fieldName := f.PascalName
		fieldType := goStorageFieldTypeFromIR(f, "Mongo")

		// Build bson tag
		var bsonTag string
		if f.DocID {
			bsonTag = "_id"
		} else if f.Inline {
			bsonTag = ",inline"
		} else {
			bsonName := storageFieldName(f.Name)
			if f.NameOverride != "" {
				// Validate the override name (SEC-2)
				if errMsg := validateFieldNameOverride(f.NameOverride); errMsg != "" {
					gen.Error(fmt.Errorf("field %s in %s: %s", f.Name, dm.FullName, errMsg))
					continue
				}
				bsonName = f.NameOverride
			}
			bsonTag = bsonName

			if f.Omitempty {
				bsonTag += ",omitempty"
			}
		}

		g.P("\t", fieldName, " ", fieldType, " `bson:\"", bsonTag, "\"`")
	}

	g.P("}")
	g.P()

	// Generate ToProto and FromProto converters
	generateConverters(g, dm, "Mongo", opts)

	// Generate ToDomain and FromDomain converters
	generateDomainConverters(g, dm, "Mongo")

	// Nested messages
	for _, nested := range dm.NestedMessages {
		generateGoMongoMessage(gen, g, nested, opts)
	}
}
