package generator

import (
	"google.golang.org/protobuf/compiler/protogen"
)

// generateGoMongo generates a Go MongoDB storage type file.
func generateGoMongo(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, "_mongo.type.go")
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: mongo")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	needsTime := false
	for _, msg := range file.Messages {
		for _, field := range msg.Fields {
			if isWellKnownTimestamp(field) || isWellKnownDuration(field) {
				needsTime = true
				break
			}
		}
	}
	if needsTime {
		g.P(`import "time"`)
		g.P()
	}

	for _, msg := range file.Messages {
		generateGoMongoMessage(g, msg, opts)
	}

	return nil
}

// generateGoMongoMessage generates a MongoDB storage struct for a message.
func generateGoMongoMessage(g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) {
	name := msg.GoIdent.GoName + "Mongo"

	g.P("// ", name, " is the MongoDB storage representation of ", msg.Desc.FullName(), ".")
	g.P("type ", name, " struct {")

	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}

		fieldName := toPascalCase(string(field.Desc.Name()))
		fieldType := goDomainFieldType(field)

		// Build bson tag
		bsonName := storageFieldName(string(field.Desc.Name()))
		bsonTag := bsonName

		// TODO: check for document_id option — use "_id" if so

		if shouldOmitempty(field, opts) {
			bsonTag += ",omitempty"
		}

		g.P("\t", fieldName, " ", fieldType, " `bson:\"", bsonTag, "\"`")
	}

	g.P("}")
	g.P()

	// Nested messages
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		generateGoMongoMessage(g, nested, opts)
	}
}
