package generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateGoPostgresSearchIndex generates HAPI-style search index extraction
// functions for FHIR resources. Given a proto message (e.g. Patient), it
// produces an Extract<Name>Indexes() function that walks the proto fields
// and emits rows for the 8 spidx_* tables (token, string, date, quantity,
// reference, uri, present, number).
//
// This mode is activated via:
//
//	opt:
//	  - backend=postgres
//	  - postgres_mode=search_index
//	  - postgres_search_params=fhir/r4/search-parameters.json
func (gg *goGenerator) generateGoPostgresSearchIndex(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename, err := outputFilename(file.GeneratedFilenamePrefix, "_search_index.go")
	if err != nil {
		return err
	}

	goImportPath := file.GoImportPath
	goPackageName := file.GoPackageName
	if opts.GoPackage != "" {
		importPath, pkgName := parseGoPackage(opts.GoPackage)
		goImportPath = protogen.GoImportPath(importPath)
		goPackageName = protogen.GoPackageName(pkgName)
		filename = filepath.Base(filename)
	}
	g := gen.NewGeneratedFile(filename, goImportPath)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: postgres")
	g.P("// mode: search_index")
	g.P()
	g.P("package ", goPackageName)
	g.P()
	g.P(`import (`)
	g.P(`	"fmt"`)
	g.P(`	"strings"`)
	g.P(`	"time"`)
	g.P(``)
	g.P(`	proto "google.golang.org/protobuf/proto"`)
	g.P(`)`)
	g.P()

	// Generate the search index row types (shared across all resources in the same Go package)
	if !gg.emittedSearchIndexTypes[goImportPath] {
		gg.emittedSearchIndexTypes[goImportPath] = true
		generateSearchIndexTypes(g)
	}

	// Suppress unused import warnings in this file
	g.P("var (")
	g.P("	_ = strings.ToLower")
	g.P("	_ = time.Now")
	g.P("	_ = proto.Marshal")
	g.P("	_ = fmt.Sprintf")
	g.P(")")
	g.P()

	// Load search params once if configured
	var spIndex SearchParamIndex
	if opts.PostgresSearchParams != "" {
		var err error
		spIndex, err = LoadSearchParams(opts.PostgresSearchParams)
		if err != nil {
			return fmt.Errorf("loading search params: %w", err)
		}
	}

	// Generate extraction functions for each top-level message
	for _, msg := range file.Messages {
		if err := generateSearchIndexExtractor(gen, g, msg, opts, spIndex); err != nil {
			return err
		}
	}

	return nil
}

// generateSearchIndexTypes emits the shared spidx_* row structs.
func generateSearchIndexTypes(g *protogen.GeneratedFile) {
	g.P("// SearchIndexes holds all extracted search parameter index rows for a resource.")
	g.P("type SearchIndexes struct {")
	g.P("	Tokens     []SpidxToken")
	g.P("	Strings    []SpidxString")
	g.P("	Dates      []SpidxDate")
	g.P("	Quantities []SpidxQuantity")
	g.P("	References []SpidxReference")
	g.P("	URIs       []SpidxURI")
	g.P("}")
	g.P()

	g.P("// SpidxToken represents a row in the spidx_token table.")
	g.P("type SpidxToken struct {")
	g.P("	TenantID  string `db:\"tenant_id\"`")
	g.P("	ResType   string `db:\"res_type\"`")
	g.P("	ResID     string `db:\"res_id\"`")
	g.P("	SpName    string `db:\"sp_name\"`")
	g.P("	SpSystem  string `db:\"sp_system\"`")
	g.P("	SpValue   string `db:\"sp_value\"`")
	g.P("}")
	g.P()

	g.P("// SpidxString represents a row in the spidx_string table.")
	g.P("type SpidxString struct {")
	g.P("	TenantID  string `db:\"tenant_id\"`")
	g.P("	ResType   string `db:\"res_type\"`")
	g.P("	ResID     string `db:\"res_id\"`")
	g.P("	SpName    string `db:\"sp_name\"`")
	g.P("	SpValue   string `db:\"sp_value\"`")
	g.P("}")
	g.P()

	g.P("// SpidxDate represents a row in the spidx_date table.")
	g.P("type SpidxDate struct {")
	g.P("	TenantID  string    `db:\"tenant_id\"`")
	g.P("	ResType   string    `db:\"res_type\"`")
	g.P("	ResID     string    `db:\"res_id\"`")
	g.P("	SpName    string    `db:\"sp_name\"`")
	g.P("	SpLow     time.Time `db:\"sp_low\"`")
	g.P("	SpHigh    time.Time `db:\"sp_high\"`")
	g.P("}")
	g.P()

	g.P("// SpidxQuantity represents a row in the spidx_quantity table.")
	g.P("type SpidxQuantity struct {")
	g.P("	TenantID  string  `db:\"tenant_id\"`")
	g.P("	ResType   string  `db:\"res_type\"`")
	g.P("	ResID     string  `db:\"res_id\"`")
	g.P("	SpName    string  `db:\"sp_name\"`")
	g.P("	SpSystem  string  `db:\"sp_system\"`")
	g.P("	SpCode    string  `db:\"sp_code\"`")
	g.P("	SpValue   float64 `db:\"sp_value\"`")
	g.P("}")
	g.P()

	g.P("// SpidxReference represents a row in the spidx_reference table.")
	g.P("type SpidxReference struct {")
	g.P("	TenantID   string `db:\"tenant_id\"`")
	g.P("	ResType    string `db:\"res_type\"`")
	g.P("	ResID      string `db:\"res_id\"`")
	g.P("	SpName     string `db:\"sp_name\"`")
	g.P("	TargetType string `db:\"target_type\"`")
	g.P("	TargetID   string `db:\"target_id\"`")
	g.P("}")
	g.P()

	g.P("// SpidxURI represents a row in the spidx_uri table.")
	g.P("type SpidxURI struct {")
	g.P("	TenantID  string `db:\"tenant_id\"`")
	g.P("	ResType   string `db:\"res_type\"`")
	g.P("	ResID     string `db:\"res_id\"`")
	g.P("	SpName    string `db:\"sp_name\"`")
	g.P("	SpValue   string `db:\"sp_value\"`")
	g.P("}")
	g.P()
}

// generateSearchIndexExtractor generates an Extract<Name>Indexes function
// for a proto message. When postgres_search_params is provided, it uses
// SearchParameter definitions to generate precise FHIRPath-compiled extraction.
// Otherwise, it falls back to a naive field walk as a starting point.
func generateSearchIndexExtractor(gen *protogen.Plugin, g *protogen.GeneratedFile, msg *protogen.Message, opts *Options, spIndex SearchParamIndex) error {
	msgName := msg.GoIdent.GoName
	resType := msgName // e.g. "Patient"

	// Select search params for this resource type from the loaded index
	var searchParams []SearchParam
	if spIndex != nil {
		searchParams = spIndex[resType]
	}

	g.P(fmt.Sprintf("// Extract%sIndexes extracts HAPI-style search index rows from a %s proto.", msgName, msgName))
	g.P("// Each SearchParameter expression is compiled to a direct proto field accessor.")
	g.P(fmt.Sprintf("func Extract%sIndexes(tenantID string, r *%s) *SearchIndexes {", msgName, g.QualifiedGoIdent(msg.GoIdent)))
	g.P("	if r == nil {")
	g.P("		return &SearchIndexes{}")
	g.P("	}")
	g.P()
	g.P("	idx := &SearchIndexes{}")
	g.P("	resID := \"\"")
	g.P("	_ = resID")
	g.P()

	// Find the ID field — google/fhir wraps it in a message
	for _, field := range msg.Fields {
		if strings.ToLower(string(field.Desc.Name())) == "id" {
			g.P("	// Extract resource ID")
			g.P(fmt.Sprintf("	if r.Get%s() != nil {", field.GoName))

			// Check if the field is a message (wrapped primitive like Id{Value: "..."})
			if field.Desc.Kind().String() == "message" {
				g.P(fmt.Sprintf("		resID = r.Get%s().GetValue()", field.GoName))
			} else {
				g.P(fmt.Sprintf("		resID = r.Get%s()", field.GoName))
			}

			g.P("	}")
			g.P()
			break
		}
	}

	// Use SearchParameter-driven extraction if search params are loaded
	if len(searchParams) > 0 {
		if err := emitSearchIndexExtraction(g, msg, searchParams, resType); err != nil {
			return err
		}
	} else if spIndex == nil {
		// Fallback: naive field walk for wrapped string fields (no search params JSON provided)
		for _, field := range msg.Fields {
			fieldName := string(field.Desc.Name())
			goGetter := fmt.Sprintf("Get%s()", field.GoName)

			if isWrappedStringField(field) {
				spName := toSearchParamName(fieldName)
				if field.Desc.IsList() {
					g.P(fmt.Sprintf("	// SearchParameter: %s (%s)", spName, resType+"."+fieldName))
					g.P(fmt.Sprintf("	for _, v := range r.%s {", goGetter))
					g.P("		if v != nil && v.GetValue() != \"\" {")
					g.P("			idx.Strings = append(idx.Strings, SpidxString{")
					g.P("				TenantID: tenantID,")
					g.P(fmt.Sprintf("				ResType:  %q,", resType))
					g.P("				ResID:    resID,")
					g.P(fmt.Sprintf("				SpName:   %q,", spName))
					g.P("				SpValue:  strings.ToLower(v.GetValue()),")
					g.P("			})")
					g.P("		}")
					g.P("	}")
					g.P()
				} else {
					g.P(fmt.Sprintf("	// SearchParameter: %s (%s)", spName, resType+"."+fieldName))
					g.P(fmt.Sprintf("	if r.%s != nil && r.%s.GetValue() != \"\" {", goGetter, goGetter))
					g.P("		idx.Strings = append(idx.Strings, SpidxString{")
					g.P("			TenantID: tenantID,")
					g.P(fmt.Sprintf("			ResType:  %q,", resType))
					g.P("			ResID:    resID,")
					g.P(fmt.Sprintf("			SpName:   %q,", spName))
					g.P(fmt.Sprintf("			SpValue:  strings.ToLower(r.%s.GetValue()),", goGetter))
					g.P("		})")
					g.P("	}")
					g.P()
				}
			}
		}
	}

	g.P("	return idx")
	g.P("}")
	g.P()

	return nil
}

// isWrappedStringField returns true if the field is a google/fhir wrapped string
// (a message with a "value" field of type string).
func isWrappedStringField(field *protogen.Field) bool {
	if field.Desc.Kind().String() != "message" {
		return false
	}
	if field.Message == nil {
		return false
	}
	// Check if the message has a "value" field of type string
	for _, f := range field.Message.Fields {
		if string(f.Desc.Name()) == "value" && f.Desc.Kind().String() == "string" {
			return true
		}
	}
	return false
}

// toSearchParamName converts a proto field name to a FHIR SearchParameter name.
// e.g. "birth_date" -> "birthdate", "managing_organization" -> "organization"
func toSearchParamName(protoName string) string {
	// Remove underscores and lowercase (simplified — full mapping from search-parameters.json)
	return strings.ReplaceAll(strings.ToLower(protoName), "_", "")
}
