package generator

import (
	"strings"
	"testing"
)

// TestSearchIndexGeneration_Integration runs the full search index generator
// against the fhir_patient.proto test file with search params JSON and verifies
// the generated Go code contains the expected patterns.
func TestSearchIndexGeneration_Integration(t *testing.T) {
	fds := buildFileDescriptorSet(t)
	gen := newPlugin(t, fds, []string{"fhir_patient.proto"})

	opts := &Options{
		Lang:                 "go",
		Backend:              "postgres",
		PostgresMode:         "search_index",
		PostgresSearchParams: "../testdata/proto/fhir_search_params.json",
		Domain:               false,
	}

	runner := NewRunner()
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		if err := runner.GenerateFile(gen, f, opts); err != nil {
			t.Fatalf("GenerateFile: %v", err)
		}
	}

	// Collect generated content
	resp := gen.Response()
	if len(resp.File) == 0 {
		t.Fatal("no files generated")
	}

	var output string
	for _, f := range resp.File {
		t.Logf("Generated file: %s", f.GetName())
		output += f.GetContent()
	}

	// Verify struct types
	assertContains(t, output, "type SearchIndexes struct")
	assertContains(t, output, "type SpidxToken struct")
	assertContains(t, output, "type SpidxString struct")
	assertContains(t, output, "type SpidxDate struct")
	assertContains(t, output, "type SpidxReference struct")

	// Verify extraction function signature
	assertContains(t, output, "func ExtractPatientIndexes(tenantID string")

	// Verify string search params
	assertContains(t, output, `SpName:   "family"`)
	assertContains(t, output, `SpName:   "given"`)
	assertContains(t, output, `SpName:   "address-city"`)

	// Verify token search params
	assertContains(t, output, `SpName:   "gender"`)
	assertContains(t, output, `SpName:   "active"`)
	assertContains(t, output, `SpName:   "identifier"`)

	// Verify where() filter for email/phone
	assertContains(t, output, `SpName:   "email"`)
	assertContains(t, output, `SpName:   "phone"`)

	// Verify reference search params
	assertContains(t, output, `SpName:     "organization"`)
	assertContains(t, output, `SpName:     "general-practitioner"`)

	// Verify date search param
	assertContains(t, output, `SpName:   "birthdate"`)

	// Verify exists() pattern
	assertContains(t, output, `SpName:   "deceased"`)
	assertContains(t, output, `"true"`) // exists() emits "true"

	// Verify choice type comment
	assertContains(t, output, "Choice type")

	// Verify language (nested token)
	assertContains(t, output, `SpName:   "language"`)

	// Verify resType is set correctly
	assertContains(t, output, `ResType:  "Patient"`)

	// Verify wrapped primitive handling (GetValue())
	assertContains(t, output, "GetValue()")

	// Verify it's a valid Go file header
	assertContains(t, output, "// Code generated by proto2type. DO NOT EDIT.")
	assertContains(t, output, "// mode: search_index")

	t.Logf("Generated %d bytes of search index code", len(output))
}

// TestSearchIndexGeneration_NoSearchParams verifies the fallback naive
// field walk when no search params JSON is provided.
func TestSearchIndexGeneration_NoSearchParams(t *testing.T) {
	fds := buildFileDescriptorSet(t)
	gen := newPlugin(t, fds, []string{"fhir_patient.proto"})

	opts := &Options{
		Lang:         "go",
		Backend:      "postgres",
		PostgresMode: "search_index",
		// No PostgresSearchParams — triggers fallback
		Domain: false,
	}

	runner := NewRunner()
	for _, f := range gen.Files {
		if !f.Generate {
			continue
		}
		if err := runner.GenerateFile(gen, f, opts); err != nil {
			t.Fatalf("GenerateFile: %v", err)
		}
	}

	resp := gen.Response()
	if len(resp.File) == 0 {
		t.Fatal("no files generated")
	}

	var output string
	for _, f := range resp.File {
		output += f.GetContent()
	}

	// Should still generate extraction function
	assertContains(t, output, "func ExtractPatientIndexes(tenantID string")
	// Should still have struct types
	assertContains(t, output, "type SearchIndexes struct")
}

// TestSearchParamsLoad_Integration verifies loading the test search params JSON.
func TestSearchParamsLoad_Integration(t *testing.T) {
	index, err := LoadSearchParams("../testdata/proto/fhir_search_params.json")
	if err != nil {
		t.Fatalf("LoadSearchParams: %v", err)
	}

	patient := index["Patient"]
	if len(patient) == 0 {
		t.Fatal("no Patient search params loaded")
	}

	t.Logf("Loaded %d Patient search params", len(patient))

	// Verify specific params exist
	found := map[string]bool{}
	for _, sp := range patient {
		found[sp.Name] = true
		t.Logf("  %s (%s): %s", sp.Name, sp.Type, sp.Expression)
	}

	for _, name := range []string{"family", "given", "birthdate", "gender", "identifier", "email", "phone", "organization", "deceased"} {
		if !found[name] {
			t.Errorf("expected search param %q not found", name)
		}
	}
}

func assertContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("generated output does not contain %q\nFirst 500 chars:\n%s", needle, truncate(haystack, 500))
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
