package generator

import (
	"fmt"
	"strings"
	"unicode"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateKotlin generates Kotlin output files for a proto file.
func generateKotlin(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	if opts.Domain {
		return generateKotlinDomain(gen, file, opts)
	}
	// No storage backends yet.
	return nil
}

// generateKotlinDomain generates a Kotlin domain type file from the IR.
func generateKotlinDomain(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	ir := BuildDomainFile(file, opts)

	filename := outputFilename(file.GeneratedFilenamePrefix, ".type.kt")
	g := gen.NewGeneratedFile(filename, "")

	// --- Header ---
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// proto2type v", Version)
	g.P("// source: ", ir.SourcePath)
	g.P()

	// --- Package ---
	pkg := ir.Package
	if pkg != "" {
		g.P("package ", pkg)
		g.P()
	}

	// --- Scan for needed imports ---
	needsSerializable := false
	needsSerialName := false
	needsInstant := false
	needsDuration := false
	needsContextual := false

	for _, e := range ir.Enums {
		needsSerializable = true
		// Enum values always get @SerialName
		if len(e.Values) > 0 {
			needsSerialName = true
		}
	}

	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		needsSerializable = true
		scanKotlinImports(m, &needsSerialName, &needsInstant, &needsDuration, &needsContextual)
	}

	// --- Emit imports ---
	if needsInstant {
		g.P("import kotlinx.datetime.Instant")
	}
	if needsSerialName {
		g.P("import kotlinx.serialization.SerialName")
	}
	if needsSerializable {
		g.P("import kotlinx.serialization.Serializable")
	}
	if needsContextual {
		g.P("import kotlinx.serialization.Contextual")
	}
	if needsDuration {
		g.P("import kotlin.time.Duration")
	}
	if needsSerializable || needsInstant || needsDuration {
		g.P()
	}

	// --- Top-level enums ---
	for _, enum := range ir.Enums {
		writeKotlinEnum(g, enum)
	}

	// --- Messages ---
	for _, msg := range ir.Messages {
		if msg.Skip {
			continue
		}
		writeKotlinMessage(g, msg)
	}

	return nil
}

// scanKotlinImports recursively scans a DomainMessage for import requirements.
func scanKotlinImports(msg *DomainMessage, needsSerialName, needsInstant, needsDuration, needsContextual *bool) {
	for _, f := range msg.Fields {
		scanKotlinFieldImports(f, needsSerialName, needsInstant, needsDuration, needsContextual)
	}

	// Oneofs always need @SerialName for variants.
	if len(msg.Oneofs) > 0 {
		*needsSerialName = true
	}

	for _, oneof := range msg.Oneofs {
		for _, v := range oneof.Variants {
			if v.Kind == FieldKindTimestamp {
				*needsInstant = true
			}
			if v.Kind == FieldKindDuration {
				*needsDuration = true
			}
		}
		// The oneof field name itself may need @SerialName on the parent message field.
		camel := escapeKotlinKeyword(toCamelCase(oneof.FieldName))
		if camel != oneof.FieldName {
			*needsSerialName = true
		}
	}

	for _, ne := range msg.NestedEnums {
		if len(ne.Values) > 0 {
			*needsSerialName = true
		}
	}

	for _, nested := range msg.NestedMessages {
		if nested.Skip {
			continue
		}
		scanKotlinImports(nested, needsSerialName, needsInstant, needsDuration, needsContextual)
	}
}

// scanKotlinFieldImports checks a single field for import requirements.
func scanKotlinFieldImports(f *DomainField, needsSerialName, needsInstant, needsDuration, needsContextual *bool) {
	if f.Kind == FieldKindTimestamp {
		*needsInstant = true
		*needsContextual = true
	}
	if f.Kind == FieldKindDuration {
		*needsDuration = true
		*needsContextual = true
	}

	// Map values may be timestamps/durations too.
	if f.IsMap {
		if f.MapValue != nil {
			if f.MapValue.Kind == FieldKindTimestamp {
				*needsInstant = true
			}
			if f.MapValue.Kind == FieldKindDuration {
				*needsDuration = true
			}
		}
	}

	// Check if field name needs @SerialName (camelCase differs from snake_case).
	camel := escapeKotlinKeyword(toCamelCase(f.Name))
	if camel != f.Name {
		*needsSerialName = true
	}
}

// writeKotlinEnum writes a Kotlin enum class to the generated file.
func writeKotlinEnum(g *protogen.GeneratedFile, enum *DomainEnum) {
	// Doc comment.
	if enum.Comment != "" {
		g.P("/** ", enum.Comment, " */")
	}

	g.P("@Serializable")
	g.P("enum class ", enum.Name, " {")

	for i, v := range enum.Values {
		kotlinName := pascalToUpperSnake(v.Name)
		sep := ","
		if i == len(enum.Values)-1 {
			sep = ";"
		}
		g.P("    @SerialName(\"", v.ProtoName, "\") ", kotlinName, sep)
	}

	g.P()
	g.P("    companion object {")
	g.P("        fun fromValue(value: Int): ", enum.Name, "? = when(value) {")
	for _, v := range enum.Values {
		kotlinName := pascalToUpperSnake(v.Name)
		g.P("            ", v.Number, " -> ", kotlinName)
	}
	g.P("            else -> null")
	g.P("        }")
	g.P("    }")
	g.P("}")
	g.P()
}

// writeKotlinMessage writes a Kotlin data class (and its oneofs/nested types) to the generated file.
func writeKotlinMessage(g *protogen.GeneratedFile, msg *DomainMessage) {
	// Nested enums first.
	for _, ne := range msg.NestedEnums {
		writeKotlinEnum(g, ne)
	}

	// Oneofs as sealed classes before the data class.
	for _, oneof := range msg.Oneofs {
		writeKotlinOneof(g, oneof)
	}

	// Doc comment.
	if msg.Comment != "" {
		g.P("/** ", msg.Comment, " */")
	}

	g.P("@Serializable")

	// Build field lines.
	type fieldLine struct {
		serialName string // empty if not needed
		decl       string
		contextual bool   // emit @Contextual annotation
		comment    string // optional comment above the field
	}
	var lines []fieldLine

	for _, f := range msg.Fields {
		if f.IsOneof {
			camel := escapeKotlinKeyword(toCamelCase(f.Name))
			typ := kotlinOneofFieldType(f.OneofTypeName)
			def := "null"

			sn := ""
			if camel != f.Name {
				sn = f.Name
			}

			lines = append(lines, fieldLine{
				serialName: sn,
				decl:       fmt.Sprintf("val %s: %s = %s", camel, typ, def),
			})
			continue
		}

		camel := escapeKotlinKeyword(toCamelCase(f.Name))
		typ := kotlinFieldType(*f)
		def := kotlinDefaultValue(*f)

		sn := ""
		if camel != f.Name {
			sn = f.Name
		}

		contextual := f.Kind == FieldKindTimestamp || f.Kind == FieldKindDuration

		var comment string
		if f.Kind == FieldKindScalar && f.ScalarKind == protoreflect.BytesKind {
			comment = "// Note: ByteArray uses referential equality. Override equals()/hashCode() if needed."
		}

		lines = append(lines, fieldLine{
			serialName: sn,
			decl:       fmt.Sprintf("val %s: %s = %s", camel, typ, def),
			contextual: contextual,
			comment:    comment,
		})
	}

	if len(lines) == 0 {
		g.P("data class ", msg.Name, "()")
	} else {
		g.P("data class ", msg.Name, "(")
		for i, line := range lines {
			trailingComma := ","
			if i == len(lines)-1 {
				trailingComma = ""
			}
			if line.comment != "" {
				g.P("    ", line.comment)
			}
			prefix := ""
			if line.contextual {
				prefix = "@Contextual "
			}
			if line.serialName != "" {
				g.P("    ", prefix, "@SerialName(\"", line.serialName, "\") ", line.decl, trailingComma)
			} else {
				g.P("    ", prefix, line.decl, trailingComma)
			}
		}
		g.P(")")
	}
	g.P()

	// Nested messages.
	for _, nested := range msg.NestedMessages {
		if nested.Skip {
			continue
		}
		writeKotlinMessage(g, nested)
	}
}

// writeKotlinOneof writes a sealed class for a oneof group.
func writeKotlinOneof(g *protogen.GeneratedFile, oneof *DomainOneof) {
	g.P("/**")
	g.P(" * Oneof group: ", oneof.FieldName, ".")
	g.P(" * Serialized using kotlinx.serialization polymorphic format (not protobuf JSON).")
	g.P(" */")
	g.P("@Serializable")
	g.P("sealed class ", oneof.Name, " {")

	for _, v := range oneof.Variants {
		variantType := kotlinOneofVariantType(v)
		g.P("    @Serializable")
		g.P("    @SerialName(\"", v.ProtoName, "\")")
		g.P("    data class ", v.Name, "(val value: ", variantType, ") : ", oneof.Name, "()")
	}

	g.P("}")
	g.P()
}

// pascalToUpperSnake converts a PascalCase string to UPPER_SNAKE_CASE.
// e.g., "Active" → "ACTIVE", "Unspecified" → "UNSPECIFIED",
// "InProgress" → "IN_PROGRESS".
func pascalToUpperSnake(s string) string {
	if s == "" {
		return s
	}
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if unicode.IsUpper(r) && i > 0 {
			prev := runes[i-1]
			if unicode.IsLower(prev) {
				b.WriteRune('_')
			} else if i+1 < len(runes) && unicode.IsLower(runes[i+1]) {
				b.WriteRune('_')
			}
		}
		b.WriteRune(unicode.ToUpper(r))
	}
	return b.String()
}
