package generator

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generatePython generates Python/Pydantic output for a proto file.
func generatePython(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	applyPythonPreset(opts)

	ir := BuildDomainFile(file, opts)

	// Flatten nested messages into the top-level list so the topological
	// sort sees every type and emits definitions in dependency order.
	ir.Messages = flattenMessages(ir.Messages)

	// Topologically sort messages so dependencies come first.
	ir.Messages = topologicalSortMessages(ir.Messages)

	// Scan what imports are needed.
	imports := scanPythonImports(ir, opts)

	// Determine output filename.
	outFile := pythonOutputFilename(file.Desc.Path(), opts)
	g := gen.NewGeneratedFile(outFile, "")

	writePythonFile(g, ir, opts, imports)
	return nil
}

// applyPythonPreset sets default options based on the chosen preset.
func applyPythonPreset(opts *Options) {
	if opts.PythonPreset == "a2a" {
		if opts.PythonAliasGenerator == "" {
			opts.PythonAliasGenerator = "camel"
		}
		if opts.PythonEnumStyle == "" {
			opts.PythonEnumStyle = "raw"
		}
	}
}

// pythonImports tracks which Python imports are needed.
type pythonImports struct {
	needsDatetime      bool
	needsTimedelta     bool
	needsAny           bool
	needsBase64        bool
	needsEnum          bool // true when the file has enum definitions
	hasTimestampFields bool // models with datetime fields need model_rebuild()
	hasBytesFields     bool
	timestampModels    []string // model names that have timestamp fields
	bytesModels        []string // model names that have bytes fields
}

func scanPythonImports(ir *DomainFile, opts *Options) *pythonImports {
	imps := &pythonImports{}
	if len(ir.Enums) > 0 {
		imps.needsEnum = true
	}
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		scanPythonImportsMessage(m, imps, opts)
	}
	return imps
}

func scanPythonImportsMessage(m *DomainMessage, imps *pythonImports, opts *Options) {
	if len(m.NestedEnums) > 0 {
		imps.needsEnum = true
	}
	var hasTS, hasBytes bool
	for _, f := range m.Fields {
		scanPythonImportsField(f, imps)
		if f.Kind == FieldKindTimestamp {
			hasTS = true
		}
		if f.Kind == FieldKindScalar && f.ScalarKind == protoreflect.BytesKind {
			hasBytes = true
		}
	}
	for _, o := range m.Oneofs {
		for _, v := range o.Variants {
			if v.Kind == FieldKindTimestamp {
				imps.needsDatetime = true
				hasTS = true
			}
			if v.Kind == FieldKindDuration {
				imps.needsTimedelta = true
			}
			if v.Kind == FieldKindStruct || v.Kind == FieldKindValue {
				imps.needsAny = true
			}
		}
	}
	if hasTS {
		imps.hasTimestampFields = true
		imps.timestampModels = append(imps.timestampModels, m.Name)
	}
	if hasBytes {
		imps.hasBytesFields = true
		imps.needsBase64 = true
		imps.bytesModels = append(imps.bytesModels, m.Name)
	}
	for _, nested := range m.NestedMessages {
		if !nested.Skip {
			scanPythonImportsMessage(nested, imps, opts)
		}
	}
}

func scanPythonImportsField(f *DomainField, imps *pythonImports) {
	applyWKTImportFlags(f.Kind, imps)
	if f.IsMap && f.MapValue != nil {
		applyWKTImportFlags(f.MapValue.Kind, imps)
	}
}

// applyWKTImportFlags sets import flags based on a field kind. Used for both
// top-level fields and map value types to keep the logic in one place.
//
// SYNC: when adding a new FieldKind here, also update wktPythonType in
// python_types.go to return the corresponding Python type string.
func applyWKTImportFlags(kind FieldKind, imps *pythonImports) {
	switch kind {
	case FieldKindTimestamp:
		imps.needsDatetime = true
	case FieldKindDuration:
		imps.needsTimedelta = true
	case FieldKindStruct, FieldKindValue, FieldKindAny, FieldKindListValue:
		imps.needsAny = true
	}
}

// writePythonFile writes the complete Python file.
func writePythonFile(g *protogen.GeneratedFile, ir *DomainFile, opts *Options, imps *pythonImports) {
	// Module docstring.
	if opts.PythonDescription != "" {
		g.P(`"""`, opts.PythonDescription, `."""`)
	} else {
		g.P(`"""Generated by proto2type from `, ir.SourcePath, `. DO NOT EDIT."""`)
	}
	g.P()

	// Future annotations for forward references.
	g.P("from __future__ import annotations")
	g.P()

	// Stdlib imports.
	if imps.needsBase64 {
		g.P("import base64")
	}
	if imps.needsEnum {
		g.P("from enum import Enum")
	}

	// typing imports.
	var typingImports []string
	if imps.needsAny {
		typingImports = append(typingImports, "Any")
	}
	if len(typingImports) > 0 {
		sort.Strings(typingImports)
		g.P("from typing import ", strings.Join(typingImports, ", "))
	}

	// datetime/timedelta imports (real imports, not TYPE_CHECKING).
	if imps.needsDatetime || imps.needsTimedelta {
		var dtImports []string
		if imps.needsDatetime {
			dtImports = append(dtImports, "datetime")
		}
		if imps.needsTimedelta {
			dtImports = append(dtImports, "timedelta")
		}
		g.P("from datetime import ", strings.Join(dtImports, ", "))
	}
	g.P()

	// Pydantic imports.
	hasCustomBase := opts.PythonBaseClass != "BaseModel" && opts.PythonBaseClass != ""
	var pydanticParts []string
	if !hasCustomBase {
		pydanticParts = append(pydanticParts, "BaseModel")
		pydanticParts = append(pydanticParts, "ConfigDict")
	}
	pydanticParts = append(pydanticParts, "Field")
	if imps.hasTimestampFields || imps.hasBytesFields {
		pydanticParts = append(pydanticParts, "field_serializer")
	}
	sort.Strings(pydanticParts)
	g.P("from pydantic import ", strings.Join(pydanticParts, ", "))

	// Alias generator import.
	if opts.PythonAliasGenerator != "" && !hasCustomBase {
		funcName, modPath := pythonAliasFuncName(opts.PythonAliasGenerator)
		if modPath != "" {
			g.P("from ", modPath, " import ", funcName)
		}
	}

	// Custom base class import.
	if hasCustomBase {
		if idx := strings.LastIndex(opts.PythonBaseClass, "."); idx > 0 {
			modPath := opts.PythonBaseClass[:idx]
			className := opts.PythonBaseClass[idx+1:]
			g.P("from ", modPath, " import ", className)
		}
	}

	g.P()
	g.P()

	// Enums.
	for _, e := range ir.Enums {
		writePythonEnum(g, e, opts)
	}

	// Messages (flattened and topologically sorted; nested enums emitted inline).
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		// Write nested enums before the message itself.
		for _, ne := range m.NestedEnums {
			writePythonEnum(g, ne, opts)
		}
		writePythonModel(g, m, opts)
	}

	// model_rebuild() for forward reference resolution.
	writePythonModelRebuilds(g, ir)

	// __all__ exports.
	writePythonAllExports(g, ir)
}

func writePythonEnum(g *protogen.GeneratedFile, e *DomainEnum, opts *Options) {
	g.P("class ", e.Name, "(str, Enum):")
	if e.Comment != "" {
		g.P(`    """`, ensurePythonTrailingPeriod(e.Comment), `"""`)
	}
	g.P()

	if len(e.Values) == 0 {
		g.P("    pass")
		g.P()
		g.P()
		return
	}

	for _, v := range e.Values {
		if opts.PythonEnumStyle == "raw" {
			// Raw: preserve original proto names including UNSPECIFIED.
			g.P("    ", v.ProtoName, " = '", v.ProtoName, "'")
		} else {
			// Default: skip UNSPECIFIED, use prefix-stripped lowercase names.
			if v.IsDefault && strings.HasSuffix(v.ProtoName, "_UNSPECIFIED") {
				continue
			}
			lowerName := strings.ToLower(v.Name)
			g.P("    ", lowerName, " = '", lowerName, "'")
		}
	}
	g.P()
	g.P()
}

// flattenMessages recursively collects all nested messages into a single flat
// slice. After flattening, NestedMessages is cleared on each parent so we
// don't double-emit.
func flattenMessages(msgs []*DomainMessage) []*DomainMessage {
	var flat []*DomainMessage
	var collect func(m *DomainMessage)
	collect = func(m *DomainMessage) {
		// Depth-first: process children before parent so the topo sort
		// preserves the correct definition order.
		for _, nested := range m.NestedMessages {
			if !nested.Skip {
				collect(nested)
			}
		}
		m.NestedMessages = nil
		flat = append(flat, m)
	}
	for _, m := range msgs {
		if !m.Skip {
			collect(m)
		}
	}
	return flat
}

func writePythonModel(g *protogen.GeneratedFile, m *DomainMessage, opts *Options) {
	// Determine base class.
	baseClass := "BaseModel"
	if opts.PythonBaseClass != "" && opts.PythonBaseClass != "BaseModel" {
		// Use just the class name, not the full module path.
		if idx := strings.LastIndex(opts.PythonBaseClass, "."); idx > 0 {
			baseClass = opts.PythonBaseClass[idx+1:]
		} else {
			baseClass = opts.PythonBaseClass
		}
	}
	hasCustomBase := baseClass != "BaseModel"

	g.P("class ", m.Name, "(", baseClass, "):")
	if m.Comment != "" {
		g.P(`    """`, ensurePythonTrailingPeriod(m.Comment), `"""`)
	}

	hasContent := false

	// model_config — always emit populate_by_name=True so keyword-escaped
	// fields (e.g. type_ with alias='type') can be set by field name.
	if !hasCustomBase {
		var configParts []string
		configParts = append(configParts, "populate_by_name=True")
		if opts.PythonAliasGenerator != "" {
			funcName, _ := pythonAliasFuncName(opts.PythonAliasGenerator)
			configParts = append(configParts, "alias_generator="+funcName)
		}
		if len(configParts) == 1 {
			g.P("    model_config = ConfigDict(", configParts[0], ")")
		} else {
			g.P("    model_config = ConfigDict(")
			for _, part := range configParts {
				g.P("        ", part, ",")
			}
			g.P("    )")
		}
		g.P()
		hasContent = true
	}

	// Regular fields.
	for _, f := range m.Fields {
		if f.FieldSkip {
			continue
		}
		if f.IsOneof {
			continue // handled below
		}
		writePythonField(g, f, opts)
		hasContent = true
	}

	// Oneof fields.
	for _, o := range m.Oneofs {
		unionType := pythonOneofUnionType(o, opts)
		fieldName := toSnakeCase(o.FieldName)
		escaped, alias := escapePythonKeyword(fieldName)
		if alias != "" {
			g.P("    ", escaped, ": ", unionType, " = Field(default=None, alias='", alias, "')")
		} else {
			g.P("    ", escaped, ": ", unionType, " = None")
		}
		hasContent = true
	}

	// to_proto_json() method.
	if opts.PythonAliasGenerator != "" {
		g.P()
		g.P("    def to_proto_json(self) -> dict:")
		g.P("        return self.model_dump(by_alias=True, exclude_none=True)")
		hasContent = true
	}

	// Timestamp field serializer.
	var tsFields []string
	for _, f := range m.Fields {
		if f.Kind == FieldKindTimestamp && !f.FieldSkip {
			name, _ := escapePythonKeyword(f.Name)
			tsFields = append(tsFields, "'"+name+"'")
		}
	}
	if len(tsFields) > 0 {
		g.P()
		g.P("    @field_serializer(", strings.Join(tsFields, ", "), ")")
		g.P("    def _serialize_datetime(self, v: datetime, _info: object) -> str | None:")
		g.P("        if v is None:")
		g.P("            return None")
		g.P("        if v.tzinfo is not None:")
		g.P("            from datetime import timezone")
		g.P("            v = v.astimezone(timezone.utc)")
		g.P("        return v.strftime('%Y-%m-%dT%H:%M:%S.') + f'{v.microsecond // 1000:03d}' + 'Z'")
		hasContent = true
	}

	// Bytes field serializer.
	var bytesFields []string
	for _, f := range m.Fields {
		if f.Kind == FieldKindScalar && f.ScalarKind == protoreflect.BytesKind && !f.FieldSkip {
			name, _ := escapePythonKeyword(f.Name)
			bytesFields = append(bytesFields, "'"+name+"'")
		}
	}
	if len(bytesFields) > 0 {
		g.P()
		g.P("    @field_serializer(", strings.Join(bytesFields, ", "), ")")
		g.P("    def _serialize_bytes(self, v: bytes, _info: object) -> str | None:")
		g.P("        if v is None:")
		g.P("            return None")
		g.P("        return base64.b64encode(v).decode('ascii')")
		hasContent = true
	}

	if !hasContent {
		g.P("    pass")
	}

	g.P()
	g.P()
}

func writePythonField(g *protogen.GeneratedFile, f *DomainField, opts *Options) {
	// Get field name and handle keyword escaping.
	fieldName := f.Name
	escaped, alias := escapePythonKeyword(fieldName)

	// Get type annotation.
	typeStr := pythonFieldType(f, opts)

	// Add optionality.
	needsOptional := pythonTypeNeedsOptional(f)
	defaultValue := pythonDefaultValue(f, opts)
	// Also need | None if default is None but type doesn't include it.
	if defaultValue == "None" {
		needsOptional = true
	}
	if needsOptional && !strings.Contains(typeStr, "| None") {
		typeStr = typeStr + " | None"
	}

	// Determine if we need Field() or simple default.
	isRequired := f.IsRequired() || (f.ValidateConstraints != nil && f.ValidateConstraints.Required)
	isOutputOnly := f.IsOutputOnly()
	hasConstraints := f.ValidateConstraints != nil && f.ValidateConstraints.HasConstraints()
	hasDescription := f.Comment != ""
	isRepeated := f.Repeated
	isMap := f.IsMap

	// Build Field() args.
	needsField := isRequired || isOutputOnly || hasConstraints || hasDescription || alias != "" || isRepeated || isMap

	if !needsField && defaultValue != "" {
		// Simple form: field_name: type = default
		g.P("    ", escaped, ": ", typeStr, " = ", defaultValue)
		return
	}

	// Field() form.
	var args []string
	if isRequired {
		args = append(args, "...")
	} else if isRepeated {
		args = append(args, "default_factory=list")
	} else if isMap {
		args = append(args, "default_factory=dict")
	} else if defaultValue != "" {
		args = append(args, "default="+defaultValue)
	} else {
		args = append(args, "default=None")
	}

	// Constraint args.
	if f.ValidateConstraints != nil {
		args = append(args, f.ValidateConstraints.ToPydanticArgs()...)
	}

	// OUTPUT_ONLY.
	if isOutputOnly {
		args = append(args, "exclude=True")
	}

	// Alias.
	if alias != "" {
		args = append(args, fmt.Sprintf("alias='%s'", alias))
	}

	// Description.
	if hasDescription {
		desc := escapePythonString(f.Comment)
		if strings.Contains(desc, "'") {
			args = append(args, fmt.Sprintf(`description="%s"`, desc))
		} else {
			args = append(args, fmt.Sprintf("description='%s'", desc))
		}
	}

	g.P("    ", escaped, ": ", typeStr, " = Field(", strings.Join(args, ", "), ")")
}

func writePythonAllExports(g *protogen.GeneratedFile, ir *DomainFile) {
	var names []string
	for _, e := range ir.Enums {
		names = append(names, e.Name)
	}
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		// Nested enums (messages are already flattened).
		for _, ne := range m.NestedEnums {
			names = append(names, ne.Name)
		}
		names = append(names, m.Name)
	}
	sort.Strings(names)

	g.P("__all__ = [")
	for _, name := range names {
		g.P("    '", name, "',")
	}
	g.P("]")
	g.P()
}

// writePythonModelRebuilds emits Model.model_rebuild() for every non-skipped
// model at the end of the file. This resolves forward references for
// self-referencing and mutually-recursive Pydantic models.
func writePythonModelRebuilds(g *protogen.GeneratedFile, ir *DomainFile) {
	var names []string
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		names = append(names, m.Name)
	}
	if len(names) > 0 {
		g.P()
		for _, name := range names {
			g.P(name, ".model_rebuild()")
		}
		g.P()
	}
}

// ensurePythonTrailingPeriod adds a trailing period for PEP 257 docstrings.
func ensurePythonTrailingPeriod(s string) string {
	if s == "" {
		return s
	}
	last := s[len(s)-1]
	if last != '.' && last != '?' && last != '!' {
		return s + "."
	}
	return s
}

// escapePythonString escapes characters that would break a Python single-line string.
func escapePythonString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	return s
}

// pythonAliasFuncName resolves the alias generator option into the Python
// function name and its import module path. Returns (funcName, modPath).
// modPath is empty for plain names that don't need an import.
func pythonAliasFuncName(aliasGen string) (funcName, modPath string) {
	if aliasGen == "camel" {
		return "to_camel", "pydantic.alias_generators"
	}
	if idx := strings.LastIndex(aliasGen, "."); idx > 0 {
		return aliasGen[idx+1:], aliasGen[:idx]
	}
	return aliasGen, ""
}
