package generator

import (
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generatePython generates Python/Pydantic output for a proto file.
func generatePython(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	applyPythonPreset(opts)

	ir := BuildDomainFile(file, opts)

	// Topologically sort messages so dependencies come first.
	ir.Messages = topologicalSortMessages(ir.Messages)

	// Scan what imports are needed.
	imports := scanPythonImports(ir, opts)

	// Determine output filename.
	outFile := pythonOutputFilename(file.Desc.Path(), opts)
	g := gen.NewGeneratedFile(outFile, "")

	writePythonFile(g, ir, opts, imports)
	return nil
}

// applyPythonPreset sets default options based on the chosen preset.
func applyPythonPreset(opts *Options) {
	if opts.PythonPreset == "a2a" {
		if opts.PythonAliasGenerator == "" {
			opts.PythonAliasGenerator = "camel"
		}
		if opts.PythonEnumStyle == "" {
			opts.PythonEnumStyle = "raw"
		}
	}
}

// pythonImports tracks which Python imports are needed.
type pythonImports struct {
	needsDatetime      bool
	needsTimedelta     bool
	needsAny           bool
	needsBase64        bool
	hasTimestampFields bool // models with datetime fields need model_rebuild()
	hasBytesFields     bool
	timestampModels    []string // model names that have timestamp fields
	bytesModels        []string // model names that have bytes fields
}

func scanPythonImports(ir *DomainFile, opts *Options) *pythonImports {
	imps := &pythonImports{}
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		scanPythonImportsMessage(m, imps, opts)
	}
	return imps
}

func scanPythonImportsMessage(m *DomainMessage, imps *pythonImports, opts *Options) {
	var hasTS, hasBytes bool
	for _, f := range m.Fields {
		scanPythonImportsField(f, imps)
		if f.Kind == FieldKindTimestamp {
			hasTS = true
		}
		if f.Kind == FieldKindScalar && f.ScalarKind == protoreflect.BytesKind {
			hasBytes = true
		}
	}
	for _, o := range m.Oneofs {
		for _, v := range o.Variants {
			if v.Kind == FieldKindTimestamp {
				imps.needsDatetime = true
				hasTS = true
			}
			if v.Kind == FieldKindDuration {
				imps.needsTimedelta = true
			}
			if v.Kind == FieldKindStruct || v.Kind == FieldKindValue {
				imps.needsAny = true
			}
		}
	}
	if hasTS {
		imps.hasTimestampFields = true
		imps.timestampModels = append(imps.timestampModels, m.Name)
	}
	if hasBytes {
		imps.hasBytesFields = true
		imps.needsBase64 = true
		imps.bytesModels = append(imps.bytesModels, m.Name)
	}
	for _, nested := range m.NestedMessages {
		if !nested.Skip {
			scanPythonImportsMessage(nested, imps, opts)
		}
	}
}

func scanPythonImportsField(f *DomainField, imps *pythonImports) {
	switch f.Kind {
	case FieldKindTimestamp:
		imps.needsDatetime = true
	case FieldKindDuration:
		imps.needsTimedelta = true
	case FieldKindStruct, FieldKindValue, FieldKindAny, FieldKindListValue:
		imps.needsAny = true
	}
	if f.IsMap && f.MapValue != nil {
		if f.MapValue.Kind == FieldKindStruct || f.MapValue.Kind == FieldKindValue {
			imps.needsAny = true
		}
	}
}

// writePythonFile writes the complete Python file.
func writePythonFile(g *protogen.GeneratedFile, ir *DomainFile, opts *Options, imps *pythonImports) {
	// Module docstring.
	if opts.PythonDescription != "" {
		g.P(`"""`, opts.PythonDescription, `."""`)
	} else {
		g.P(`"""Generated by proto2type from `, ir.SourcePath, `. DO NOT EDIT."""`)
	}
	g.P()

	// Future annotations for forward references.
	g.P("from __future__ import annotations")
	g.P()

	// Stdlib imports.
	if imps.needsBase64 {
		g.P("import base64")
	}
	g.P("from enum import Enum")

	// typing imports.
	var typingImports []string
	if imps.needsDatetime || imps.needsTimedelta {
		typingImports = append(typingImports, "TYPE_CHECKING")
	}
	if imps.needsAny {
		typingImports = append(typingImports, "Any")
	}
	if len(typingImports) > 0 {
		sort.Strings(typingImports)
		g.P("from typing import ", strings.Join(typingImports, ", "))
	}
	g.P()

	// TYPE_CHECKING block for datetime/timedelta.
	if imps.needsDatetime || imps.needsTimedelta {
		g.P("if TYPE_CHECKING:")
		var dtImports []string
		if imps.needsDatetime {
			dtImports = append(dtImports, "datetime")
		}
		if imps.needsTimedelta {
			dtImports = append(dtImports, "timedelta")
		}
		g.P("    from datetime import ", strings.Join(dtImports, ", "))
		g.P()
	}

	// Pydantic imports.
	hasCustomBase := opts.PythonBaseClass != "BaseModel" && opts.PythonBaseClass != ""
	var pydanticParts []string
	if !hasCustomBase {
		pydanticParts = append(pydanticParts, "BaseModel")
	}
	pydanticParts = append(pydanticParts, "Field")
	if imps.hasTimestampFields || imps.hasBytesFields {
		pydanticParts = append(pydanticParts, "field_serializer")
	}
	if opts.PythonAliasGenerator != "" && !hasCustomBase {
		pydanticParts = append(pydanticParts, "ConfigDict")
	}
	sort.Strings(pydanticParts)
	g.P("from pydantic import ", strings.Join(pydanticParts, ", "))

	// Alias generator import.
	if opts.PythonAliasGenerator == "camel" && !hasCustomBase {
		g.P("from pydantic.alias_generators import to_camel")
	} else if opts.PythonAliasGenerator != "" && opts.PythonAliasGenerator != "camel" && !hasCustomBase {
		// Custom dotted path: "module.func" -> from module import func
		if idx := strings.LastIndex(opts.PythonAliasGenerator, "."); idx > 0 {
			modPath := opts.PythonAliasGenerator[:idx]
			funcName := opts.PythonAliasGenerator[idx+1:]
			g.P("from ", modPath, " import ", funcName)
		}
	}

	// Custom base class import.
	if hasCustomBase {
		if idx := strings.LastIndex(opts.PythonBaseClass, "."); idx > 0 {
			modPath := opts.PythonBaseClass[:idx]
			className := opts.PythonBaseClass[idx+1:]
			g.P("from ", modPath, " import ", className)
		}
	}

	g.P()
	g.P()

	// Enums.
	for _, e := range ir.Enums {
		writePythonEnum(g, e, opts)
	}

	// Messages (including nested enums and nested messages as top-level classes).
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		writePythonMessageRecursive(g, m, opts)
	}

	// __all__ exports.
	writePythonAllExports(g, ir)

	// model_rebuild() for TYPE_CHECKING forward refs.
	writePythonModelRebuilds(g, imps)
}

func writePythonEnum(g *protogen.GeneratedFile, e *DomainEnum, opts *Options) {
	g.P("class ", e.Name, "(str, Enum):")
	if e.Comment != "" {
		g.P(`    """`, ensurePythonTrailingPeriod(e.Comment), `"""`)
	}
	g.P()

	if len(e.Values) == 0 {
		g.P("    pass")
		g.P()
		g.P()
		return
	}

	for _, v := range e.Values {
		if opts.PythonEnumStyle == "raw" {
			// Raw: preserve original proto names including UNSPECIFIED.
			g.P("    ", v.ProtoName, " = '", v.ProtoName, "'")
		} else {
			// Default: skip UNSPECIFIED, use prefix-stripped lowercase names.
			if v.IsDefault && strings.HasSuffix(v.ProtoName, "_UNSPECIFIED") {
				continue
			}
			lowerName := strings.ToLower(v.Name)
			g.P("    ", lowerName, " = '", lowerName, "'")
		}
	}
	g.P()
	g.P()
}

// writePythonMessageRecursive writes nested enums and nested messages (as top-level
// Python classes) before the parent message. Python has no nested data class concept
// like Kotlin, so everything is emitted at module level.
func writePythonMessageRecursive(g *protogen.GeneratedFile, m *DomainMessage, opts *Options) {
	// Write nested enums before the message.
	for _, ne := range m.NestedEnums {
		writePythonEnum(g, ne, opts)
	}
	// Write nested messages before the parent (depth-first).
	for _, nested := range m.NestedMessages {
		if nested.Skip {
			continue
		}
		writePythonMessageRecursive(g, nested, opts)
	}
	// Write the message itself.
	writePythonModel(g, m, opts)
}

func writePythonModel(g *protogen.GeneratedFile, m *DomainMessage, opts *Options) {
	// Determine base class.
	baseClass := "BaseModel"
	if opts.PythonBaseClass != "" && opts.PythonBaseClass != "BaseModel" {
		// Use just the class name, not the full module path.
		if idx := strings.LastIndex(opts.PythonBaseClass, "."); idx > 0 {
			baseClass = opts.PythonBaseClass[idx+1:]
		} else {
			baseClass = opts.PythonBaseClass
		}
	}
	hasCustomBase := baseClass != "BaseModel"

	g.P("class ", m.Name, "(", baseClass, "):")
	if m.Comment != "" {
		g.P(`    """`, ensurePythonTrailingPeriod(m.Comment), `"""`)
	}

	hasContent := false

	// model_config for alias generation.
	if opts.PythonAliasGenerator != "" && !hasCustomBase {
		aliasFunc := "to_camel"
		if opts.PythonAliasGenerator != "camel" {
			if idx := strings.LastIndex(opts.PythonAliasGenerator, "."); idx > 0 {
				aliasFunc = opts.PythonAliasGenerator[idx+1:]
			} else {
				aliasFunc = opts.PythonAliasGenerator
			}
		}
		g.P("    model_config = ConfigDict(")
		g.P("        populate_by_name=True,")
		g.P("        alias_generator=", aliasFunc, ",")
		g.P("    )")
		g.P()
		hasContent = true
	}

	// Regular fields.
	for _, f := range m.Fields {
		if f.FieldSkip {
			continue
		}
		if f.IsOneof {
			continue // handled below
		}
		writePythonField(g, f, opts)
		hasContent = true
	}

	// Oneof fields.
	for _, o := range m.Oneofs {
		unionType := pythonOneofUnionType(o, opts)
		fieldName := toSnakeCase(o.FieldName)
		escaped, alias := escapePythonKeyword(fieldName)
		if alias != "" {
			g.P("    ", escaped, ": ", unionType, " = Field(default=None, alias='", alias, "')")
		} else {
			g.P("    ", escaped, ": ", unionType, " = None")
		}
		hasContent = true
	}

	// to_proto_json() method.
	if opts.PythonAliasGenerator != "" {
		g.P()
		g.P("    def to_proto_json(self) -> dict:")
		g.P("        return self.model_dump(by_alias=True, exclude_none=True)")
		hasContent = true
	}

	// Timestamp field serializer.
	var tsFields []string
	for _, f := range m.Fields {
		if f.Kind == FieldKindTimestamp && !f.FieldSkip {
			name, _ := escapePythonKeyword(f.Name)
			tsFields = append(tsFields, "'"+name+"'")
		}
	}
	if len(tsFields) > 0 {
		g.P()
		g.P("    @field_serializer(", strings.Join(tsFields, ", "), ")")
		g.P("    def _serialize_datetime(self, v: datetime, _info: object) -> str | None:")
		g.P("        if v is None:")
		g.P("            return None")
		g.P("        return v.strftime('%Y-%m-%dT%H:%M:%S.') + f'{v.microsecond // 1000:03d}' + 'Z'")
		hasContent = true
	}

	// Bytes field serializer.
	var bytesFields []string
	for _, f := range m.Fields {
		if f.Kind == FieldKindScalar && f.ScalarKind == protoreflect.BytesKind && !f.FieldSkip {
			name, _ := escapePythonKeyword(f.Name)
			bytesFields = append(bytesFields, "'"+name+"'")
		}
	}
	if len(bytesFields) > 0 {
		g.P()
		g.P("    @field_serializer(", strings.Join(bytesFields, ", "), ")")
		g.P("    def _serialize_bytes(self, v: bytes, _info: object) -> str | None:")
		g.P("        if v is None:")
		g.P("            return None")
		g.P("        return base64.b64encode(v).decode('ascii')")
		hasContent = true
	}

	if !hasContent {
		g.P("    pass")
	}

	g.P()
	g.P()
}

func writePythonField(g *protogen.GeneratedFile, f *DomainField, opts *Options) {
	// Get field name and handle keyword escaping.
	fieldName := f.Name
	escaped, alias := escapePythonKeyword(fieldName)

	// Get type annotation.
	typeStr := pythonFieldType(f, opts)

	// Add optionality.
	needsOptional := pythonTypeNeedsOptional(f)
	defaultValue := pythonDefaultValue(f, opts)
	// Also need | None if default is None but type doesn't include it.
	if defaultValue == "None" {
		needsOptional = true
	}
	if needsOptional && !strings.Contains(typeStr, "| None") {
		typeStr = typeStr + " | None"
	}

	// Determine if we need Field() or simple default.
	isRequired := f.IsRequired() || (f.ValidateConstraints != nil && f.ValidateConstraints.Required)
	isOutputOnly := f.IsOutputOnly()
	hasConstraints := f.ValidateConstraints != nil && f.ValidateConstraints.HasConstraints()
	hasDescription := f.Comment != ""

	// Build Field() args.
	needsField := isRequired || isOutputOnly || hasConstraints || hasDescription || alias != ""

	if !needsField && defaultValue != "" {
		// Simple form: field_name: type = default
		g.P("    ", escaped, ": ", typeStr, " = ", defaultValue)
		return
	}

	// Field() form.
	var args []string
	if isRequired {
		args = append(args, "...")
	} else if defaultValue != "" {
		args = append(args, "default="+defaultValue)
	} else {
		args = append(args, "default=None")
	}

	// Constraint args.
	if f.ValidateConstraints != nil {
		args = append(args, f.ValidateConstraints.ToPydanticArgs()...)
	}

	// OUTPUT_ONLY.
	if isOutputOnly {
		args = append(args, "exclude=True")
	}

	// Alias.
	if alias != "" {
		args = append(args, fmt.Sprintf("alias='%s'", alias))
	}

	// Description.
	if hasDescription {
		desc := escapePythonString(f.Comment)
		if strings.Contains(desc, "'") {
			args = append(args, fmt.Sprintf(`description="%s"`, desc))
		} else {
			args = append(args, fmt.Sprintf("description='%s'", desc))
		}
	}

	g.P("    ", escaped, ": ", typeStr, " = Field(", strings.Join(args, ", "), ")")
}

func writePythonAllExports(g *protogen.GeneratedFile, ir *DomainFile) {
	var names []string
	for _, e := range ir.Enums {
		names = append(names, e.Name)
	}
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		collectPythonExportNames(m, &names)
	}
	sort.Strings(names)

	g.P("__all__ = [")
	for _, name := range names {
		g.P("    '", name, "',")
	}
	g.P("]")
	g.P()
}

// collectPythonExportNames recursively collects export names from a message
// and its nested enums and nested messages.
func collectPythonExportNames(m *DomainMessage, names *[]string) {
	// Nested enums.
	for _, ne := range m.NestedEnums {
		*names = append(*names, ne.Name)
	}
	// Nested messages (recursive).
	for _, nested := range m.NestedMessages {
		if nested.Skip {
			continue
		}
		collectPythonExportNames(nested, names)
	}
	// The message itself.
	*names = append(*names, m.Name)
}

func writePythonModelRebuilds(g *protogen.GeneratedFile, imps *pythonImports) {
	if !imps.hasTimestampFields && !imps.hasBytesFields {
		return
	}
	// Collect unique model names.
	seen := make(map[string]bool)
	var models []string
	for _, name := range imps.timestampModels {
		if !seen[name] {
			seen[name] = true
			models = append(models, name)
		}
	}
	g.P()
	for _, name := range models {
		g.P(name, ".model_rebuild()")
	}
}

// ensurePythonTrailingPeriod adds a trailing period for PEP 257 docstrings.
func ensurePythonTrailingPeriod(s string) string {
	if s == "" {
		return s
	}
	last := s[len(s)-1]
	if last != '.' && last != '?' && last != '!' {
		return s + "."
	}
	return s
}

// escapePythonString escapes characters that would break a Python single-line string.
func escapePythonString(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	return s
}
