package generator

import (
	"os"
	"regexp"
	"strings"
	"testing"
)

// TestGoldenRoundTripConsistency verifies that generated SQLite golden files
// have structurally consistent to_domain / from_domain / into_domain / from_row
// methods, and that known anti-patterns (e.g. unwrap_or_default on fallible
// deserialization) are absent.
func TestGoldenRoundTripConsistency(t *testing.T) {
	files := []string{
		"../testdata/golden/rust/gen/user_sqlite.type.rs",
		"../testdata/golden/rust/gen/catalog_sqlite.type.rs",
	}
	for _, f := range files {
		t.Run(f, func(t *testing.T) {
			content, err := os.ReadFile(f)
			if err != nil {
				t.Skipf("golden file not found: %s", f)
				return
			}
			src := string(content)

			// ── Required functions ──────────────────────────────────────
			requiredFuncs := []string{
				"fn to_domain",
				"fn from_domain",
				"fn into_domain",
				"fn from_row",
			}
			for _, fn := range requiredFuncs {
				if !strings.Contains(src, fn) {
					t.Errorf("missing required function: %s", fn)
				}
			}

			// ── Required infrastructure ────────────────────────────────
			if !strings.Contains(src, "pub enum ConversionError") {
				t.Error("missing ConversionError enum")
			}
			if !strings.Contains(src, "impl std::fmt::Display for ConversionError") {
				t.Error("missing Display impl for ConversionError")
			}
			if !strings.Contains(src, "impl std::error::Error for ConversionError") {
				t.Error("missing Error impl for ConversionError")
			}

			// ── Anti-pattern checks ────────────────────────────────────
			// P0 fix: serde_json should use ? operator, never unwrap_or_default
			re := regexp.MustCompile(`serde_json::from_str.*unwrap_or_default`)
			if re.MatchString(src) {
				t.Error("found serde_json unwrap_or_default — should use ? operator")
			}

			// Timestamp conversion should return Result, not unwrap
			reTimestamp := regexp.MustCompile(`from_timestamp_millis.*unwrap_or_default`)
			if reTimestamp.MatchString(src) {
				t.Error("found timestamp unwrap_or_default — should return Result")
			}

			// ── to_domain / into_domain field parity ───────────────────
			// Both functions should reference the same domain struct fields.
			toDomainFields := extractFunctionFields(src, "fn to_domain")
			intoDomainFields := extractFunctionFields(src, "fn into_domain")
			if len(toDomainFields) > 0 && len(intoDomainFields) > 0 {
				if len(toDomainFields) != len(intoDomainFields) {
					t.Errorf("to_domain has %d field assignments but into_domain has %d",
						len(toDomainFields), len(intoDomainFields))
				}
			}

			// ── from_domain field parity ────────────────────────────────
			fromDomainFields := extractFunctionFields(src, "fn from_domain")
			if len(toDomainFields) > 0 && len(fromDomainFields) > 0 {
				if len(toDomainFields) != len(fromDomainFields) {
					t.Errorf("to_domain has %d field assignments but from_domain has %d",
						len(toDomainFields), len(fromDomainFields))
				}
			}

			// ── No unwrap() in conversion functions ────────────────────
			// All conversions should use ? or explicit error handling.
			reUnwrap := regexp.MustCompile(`\.unwrap\(\)`)
			for _, fn := range []string{"fn to_domain", "fn from_domain", "fn into_domain"} {
				body := extractFunctionBody(src, fn)
				if reUnwrap.MatchString(body) {
					t.Errorf("found .unwrap() in %s — should use ? operator or explicit handling", fn)
				}
			}
		})
	}
}

// TestGoldenDomainTypesExist verifies that domain type golden files contain
// expected struct definitions and derive attributes.
func TestGoldenDomainTypesExist(t *testing.T) {
	files := []string{
		"../testdata/golden/rust/gen/user.type.rs",
		"../testdata/golden/rust/gen/catalog.type.rs",
	}
	for _, f := range files {
		t.Run(f, func(t *testing.T) {
			content, err := os.ReadFile(f)
			if err != nil {
				t.Skipf("golden file not found: %s", f)
				return
			}
			src := string(content)

			// Must have at least one pub struct
			if !strings.Contains(src, "pub struct ") {
				t.Error("no pub struct found in domain type file")
			}

			// Must have serde derives
			if !strings.Contains(src, "Serialize") || !strings.Contains(src, "Deserialize") {
				t.Error("missing Serialize/Deserialize derives")
			}

			// Must be generated code
			if !strings.Contains(src, "Code generated by proto2type. DO NOT EDIT.") {
				t.Error("missing generated code header")
			}
		})
	}
}

// TestGoldenKotlinDomainTypesExist verifies that Kotlin domain type golden files
// contain expected data class definitions and kotlinx.serialization annotations.
func TestGoldenKotlinDomainTypesExist(t *testing.T) {
	files := []string{
		"../testdata/golden/kotlin/gen/user.type.kt",
		"../testdata/golden/kotlin/gen/catalog.type.kt",
		"../testdata/golden/kotlin/gen/keywords.type.kt",
	}
	for _, f := range files {
		t.Run(f, func(t *testing.T) {
			content, err := os.ReadFile(f)
			if err != nil {
				t.Skipf("golden file not found: %s", f)
				return
			}
			src := string(content)

			// Must be generated code
			if !strings.Contains(src, "Code generated by proto2type. DO NOT EDIT.") {
				t.Error("missing generated code header")
			}

			// Must have @Serializable
			if !strings.Contains(src, "@Serializable") {
				t.Error("missing @Serializable annotation")
			}

			// Must have at least one data class
			if !strings.Contains(src, "data class ") {
				t.Error("no data class found in domain type file")
			}
		})
	}
}

// extractFunctionFields extracts field assignment names (e.g. "id:", "email:")
// from the first occurrence of a function. Returns the field names found.
func extractFunctionFields(src, funcSig string) []string {
	body := extractFunctionBody(src, funcSig)
	if body == "" {
		return nil
	}
	re := regexp.MustCompile(`(?m)^\s+(\w+)[:\s]`)
	matches := re.FindAllStringSubmatch(body, -1)
	var fields []string
	for _, m := range matches {
		fields = append(fields, m[1])
	}
	return fields
}

// extractFunctionBody extracts the body of a function by matching braces.
func extractFunctionBody(src, funcSig string) string {
	idx := strings.Index(src, funcSig)
	if idx < 0 {
		return ""
	}
	// Find opening brace
	braceStart := strings.Index(src[idx:], "{")
	if braceStart < 0 {
		return ""
	}
	start := idx + braceStart
	depth := 0
	for i := start; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return src[start : i+1]
			}
		}
	}
	return ""
}
