package generator

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateRustBuffa generates a Rust buffa (ConnectRPC proto) conversion file for a proto file.
func generateRustBuffa(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	if opts.BufModule == "" {
		return fmt.Errorf("proto2type: buffa backend requires buffa_module option (e.g. buffa_module=crate::proto::my::package::v1)")
	}

	filename := outputFilename(file.GeneratedFilenamePrefix, "_buffa.type.rs")

	g := gen.NewGeneratedFile(filename, "")

	// Build IR from the proto file.
	df := BuildDomainFile(file, opts)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// proto2type v", Version)
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: buffa")
	g.P()

	// Scan IR for needed imports.
	needsChrono := irNeedsChronoBuffa(df.Messages)

	// Emit use statements
	g.P("use super::*;")
	if needsChrono {
		g.P("use chrono::{DateTime, Utc};")
	}
	g.P()

	// Module alias for buffa proto types
	g.P("use ", opts.BufModule, " as __buffa_mod;")
	g.P()

	// Emit ConversionError type
	generateBuffaConversionError(g, needsChrono)

	// Generate timestamp helpers if needed
	if needsChrono {
		generateBuffaTimestampHelpers(g)
	}

	// Build proto message lookup
	protoMsgMap := buildProtoMessageMap(file.Messages)

	for _, dm := range df.Messages {
		msg := protoMsgMap[dm.FullName]
		if msg == nil {
			return fmt.Errorf("proto2type: no protogen.Message found for IR message %q", dm.FullName)
		}
		generateRustBuffaMessage(g, dm, msg, protoMsgMap, opts)
	}

	return nil
}

// irNeedsChronoBuffa returns true if any non-skipped, non-docID field is a Timestamp.
func irNeedsChronoBuffa(msgs []*DomainMessage) bool {
	for _, m := range msgs {
		if m.Skip {
			continue
		}
		for _, f := range m.Fields {
			if f.DocID {
				continue
			}
			if f.Kind == FieldKindTimestamp {
				return true
			}
		}
		// Check oneof variants for timestamps
		for _, o := range m.Oneofs {
			for _, v := range o.Variants {
				if v.Kind == FieldKindTimestamp {
					return true
				}
			}
		}
		if irNeedsChronoBuffa(m.NestedMessages) {
			return true
		}
	}
	return false
}

// generateBuffaConversionError emits the ConversionError enum for buffa conversions.
func generateBuffaConversionError(g *protogen.GeneratedFile, needsChrono bool) {
	g.P("#[derive(Debug)]")
	g.P("pub enum ConversionError {")
	if needsChrono {
		g.P("    InvalidTimestamp { seconds: i64, nanos: i32 },")
	}
	g.P("    InvalidEnumValue(i32),")
	g.P("}")
	g.P()
	g.P("impl std::fmt::Display for ConversionError {")
	g.P("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
	g.P("        match self {")
	if needsChrono {
		g.P(`            Self::InvalidTimestamp { seconds, nanos } => write!(f, "invalid timestamp: {seconds}s {nanos}ns"),`)
	}
	g.P(`            Self::InvalidEnumValue(v) => write!(f, "invalid enum value: {v}"),`)
	g.P("        }")
	g.P("    }")
	g.P("}")
	g.P()
	g.P("impl std::error::Error for ConversionError {}")
	g.P()
}

// generateBuffaTimestampHelpers emits chrono↔buffa timestamp conversion functions.
func generateBuffaTimestampHelpers(g *protogen.GeneratedFile) {
	g.P("/// Converts a chrono DateTime<Utc> to a buffa protobuf Timestamp.")
	g.P("#[allow(dead_code)]")
	g.P("fn chrono_to_buffa_timestamp(dt: &DateTime<Utc>) -> buffa_types::google::protobuf::Timestamp {")
	g.P("    let mut ts = buffa_types::google::protobuf::Timestamp::default();")
	g.P("    ts.seconds = dt.timestamp();")
	g.P("    ts.nanos = dt.timestamp_subsec_nanos() as i32;")
	g.P("    ts")
	g.P("}")
	g.P()
	g.P("/// Converts a buffa protobuf Timestamp to a chrono DateTime<Utc>.")
	g.P("#[allow(dead_code)]")
	g.P("fn buffa_timestamp_to_chrono(")
	g.P("    ts: &buffa_types::google::protobuf::Timestamp,")
	g.P(") -> Result<DateTime<Utc>, ConversionError> {")
	g.P("    DateTime::from_timestamp(ts.seconds, ts.nanos as u32)")
	g.P("        .ok_or(ConversionError::InvalidTimestamp {")
	g.P("            seconds: ts.seconds,")
	g.P("            nanos: ts.nanos,")
	g.P("        })")
	g.P("}")
	g.P()
}

// generateRustBuffaMessage generates From and TryFrom impls for a single message.
func generateRustBuffaMessage(g *protogen.GeneratedFile, dm *DomainMessage, msg *protogen.Message, protoMsgMap map[string]*protogen.Message, opts *Options) {
	if dm.Skip {
		return
	}

	domainName := dm.Name
	bufName := "__buffa_mod::" + domainName

	// --- From<&DomainType> for __buffa_mod::ProtoType (domain → buffa) ---
	g.P("#[allow(clippy::field_reassign_with_default)]")
	g.P("impl From<&", domainName, "> for ", bufName, " {")
	g.P("    fn from(d: &", domainName, ") -> Self {")
	g.P("        let mut b = Self::default();")

	for _, f := range dm.Fields {
		if f.DocID {
			continue
		}
		rustFieldName := escapeRustKeyword(toSnakeCase(f.Name))

		if f.IsOneof {
			// Find the matching oneof definition
			for _, o := range dm.Oneofs {
				if o.FieldName == f.Name {
					generateBuffaDomainToBufOneof(g, o, rustFieldName, domainName)
					break
				}
			}
			continue
		}

		expr := rustBuffaDomainToBufExpr(f, rustFieldName)
		g.P("        b.", rustFieldName, " = ", expr, ";")
	}

	g.P("        b")
	g.P("    }")
	g.P("}")
	g.P()

	// --- TryFrom<&__buffa_mod::ProtoType> for DomainType (buffa → domain) ---
	g.P("impl TryFrom<&", bufName, "> for ", domainName, " {")
	g.P("    type Error = ConversionError;")
	g.P()
	g.P("    fn try_from(b: &", bufName, ") -> Result<Self, Self::Error> {")
	g.P("        Ok(Self {")

	for _, f := range dm.Fields {
		if f.DocID {
			continue
		}
		rustFieldName := escapeRustKeyword(toSnakeCase(f.Name))

		if f.IsOneof {
			for _, o := range dm.Oneofs {
				if o.FieldName == f.Name {
					generateBuffaBufToDomainOneof(g, o, rustFieldName, domainName)
					break
				}
			}
			continue
		}

		expr := rustBuffaBufToDomainExpr(f, rustFieldName)
		g.P("            ", rustFieldName, ": ", expr, ",")
	}

	g.P("        })")
	g.P("    }")
	g.P("}")
	g.P()

	// Nested messages
	for _, nested := range dm.NestedMessages {
		nestedMsg := protoMsgMap[nested.FullName]
		if nestedMsg == nil {
			continue
		}
		generateRustBuffaMessage(g, nested, nestedMsg, protoMsgMap, opts)
	}
}

// rustBuffaDomainToBufExpr returns the expression to convert a domain field to a buffa field.
func rustBuffaDomainToBufExpr(f *DomainField, fieldName string) string {
	// Handle repeated fields first
	if f.Repeated {
		switch f.Kind {
		case FieldKindMessage:
			return fmt.Sprintf("d.%s.iter().map(Into::into).collect()", fieldName)
		case FieldKindScalar:
			if f.ScalarKind == protoreflect.StringKind {
				return fmt.Sprintf("d.%s.iter().map(|s| s.clone().into()).collect()", fieldName)
			}
			return fmt.Sprintf("d.%s.clone()", fieldName)
		case FieldKindEnum:
			return fmt.Sprintf("d.%s.iter().map(|v| *v as i32).collect()", fieldName)
		default:
			return fmt.Sprintf("d.%s.clone()", fieldName)
		}
	}

	// Handle map fields
	if f.IsMap {
		return fmt.Sprintf("d.%s.clone()", fieldName)
	}

	switch f.Kind {
	case FieldKindTimestamp:
		if f.Optional {
			return fmt.Sprintf("match &d.%s { Some(dt) => buffa::MessageField::some(chrono_to_buffa_timestamp(dt)), None => buffa::MessageField::none() }", fieldName)
		}
		return fmt.Sprintf("buffa::MessageField::some(chrono_to_buffa_timestamp(&d.%s))", fieldName)

	case FieldKindMessage:
		if f.Optional || !f.Repeated {
			// Singular message fields are always Option<T> or Option<Box<T>> in domain
			if f.NeedsBox {
				return fmt.Sprintf("match &d.%s { Some(v) => buffa::MessageField::some(v.as_ref().into()), None => buffa::MessageField::none() }", fieldName)
			}
			return fmt.Sprintf("match &d.%s { Some(v) => buffa::MessageField::some(v.into()), None => buffa::MessageField::none() }", fieldName)
		}
		return fmt.Sprintf("d.%s.iter().map(Into::into).collect()", fieldName)

	case FieldKindEnum:
		if f.Optional {
			return fmt.Sprintf("d.%s.map(|v| v as i32)", fieldName)
		}
		return fmt.Sprintf("d.%s as i32", fieldName)

	case FieldKindScalar:
		return rustBuffaDomainToBufScalar(f, fieldName)

	case FieldKindDuration:
		return fmt.Sprintf("d.%s", fieldName)

	default:
		if f.Kind.IsWrapper() {
			return fmt.Sprintf("d.%s", fieldName)
		}
		return fmt.Sprintf("d.%s.clone().into()", fieldName)
	}
}

// rustBuffaDomainToBufScalar handles scalar field domain→buffa conversion.
func rustBuffaDomainToBufScalar(f *DomainField, fieldName string) string {
	switch f.ScalarKind {
	case protoreflect.StringKind:
		if f.Optional {
			return fmt.Sprintf("d.%s.as_deref().map(Into::into)", fieldName)
		}
		return fmt.Sprintf("d.%s.clone().into()", fieldName)

	case protoreflect.BytesKind:
		return fmt.Sprintf("d.%s.clone()", fieldName)

	default:
		return fmt.Sprintf("d.%s", fieldName)
	}
}

// rustBuffaBufToDomainExpr returns the expression to convert a buffa field to a domain field.
func rustBuffaBufToDomainExpr(f *DomainField, fieldName string) string {
	// Handle repeated fields first
	if f.Repeated {
		switch f.Kind {
		case FieldKindMessage:
			return fmt.Sprintf("b.%s.iter().map(|v| v.try_into()).collect::<Result<Vec<_>, _>>()?", fieldName)
		case FieldKindScalar:
			if f.ScalarKind == protoreflect.StringKind {
				return fmt.Sprintf("b.%s.iter().map(|s| s.to_string()).collect()", fieldName)
			}
			return fmt.Sprintf("b.%s.clone()", fieldName)
		case FieldKindEnum:
			enumType := f.EnumTypeName
			return fmt.Sprintf("b.%s.iter().map(|v| %s::from_i32(*v).ok_or(ConversionError::InvalidEnumValue(*v))).collect::<Result<Vec<_>, _>>()?", fieldName, enumType)
		default:
			return fmt.Sprintf("b.%s.clone()", fieldName)
		}
	}

	// Handle map fields
	if f.IsMap {
		return fmt.Sprintf("b.%s.clone()", fieldName)
	}

	switch f.Kind {
	case FieldKindTimestamp:
		if f.Optional {
			return fmt.Sprintf("match b.%s.as_ref() { Some(ts) => Some(buffa_timestamp_to_chrono(ts)?), None => None }", fieldName)
		}
		return fmt.Sprintf("buffa_timestamp_to_chrono(b.%s.as_ref().unwrap_or(&Default::default()))?", fieldName)

	case FieldKindMessage:
		if f.Optional || !f.Repeated {
			if f.NeedsBox {
				return fmt.Sprintf("match b.%s.as_ref() { Some(v) => Some(Box::new(v.try_into()?)), None => None }", fieldName)
			}
			return fmt.Sprintf("match b.%s.as_ref() { Some(v) => Some(v.try_into()?), None => None }", fieldName)
		}
		return fmt.Sprintf("b.%s.iter().map(|v| v.try_into()).collect::<Result<Vec<_>, _>>()?", fieldName)

	case FieldKindEnum:
		enumType := f.EnumTypeName
		if f.Optional {
			return fmt.Sprintf("b.%s.map(|v| %s::from_i32(v).ok_or(ConversionError::InvalidEnumValue(v))).transpose()?", fieldName, enumType)
		}
		return fmt.Sprintf("%s::from_i32(b.%s).ok_or(ConversionError::InvalidEnumValue(b.%s))?", enumType, fieldName, fieldName)

	case FieldKindScalar:
		return rustBuffaBufToDomainScalar(f, fieldName)

	case FieldKindDuration:
		return fmt.Sprintf("b.%s", fieldName)

	default:
		if f.Kind.IsWrapper() {
			return fmt.Sprintf("b.%s", fieldName)
		}
		return fmt.Sprintf("b.%s.clone().into()", fieldName)
	}
}

// rustBuffaBufToDomainScalar handles scalar field buffa→domain conversion.
func rustBuffaBufToDomainScalar(f *DomainField, fieldName string) string {
	switch f.ScalarKind {
	case protoreflect.StringKind:
		if f.Optional {
			return fmt.Sprintf("b.%s.as_ref().map(|s| s.to_string())", fieldName)
		}
		return fmt.Sprintf("b.%s.to_string()", fieldName)

	case protoreflect.BytesKind:
		if f.Optional {
			return fmt.Sprintf("b.%s.clone()", fieldName)
		}
		return fmt.Sprintf("b.%s.to_vec()", fieldName)

	default:
		return fmt.Sprintf("b.%s", fieldName)
	}
}

// generateBuffaDomainToBufOneof generates the domain→buffa oneof conversion.
func generateBuffaDomainToBufOneof(g *protogen.GeneratedFile, o *DomainOneof, fieldName, parentMsg string) {
	oneofPascal := toPascalCase(o.FieldName)

	g.P("        b.", fieldName, " = d.", fieldName, ".as_ref().map(|v| match v {")
	for _, v := range o.Variants {
		variantFieldName := escapeRustKeyword(toSnakeCase(v.ProtoName))
		variantPascal := v.Name

		switch v.Kind {
		case FieldKindMessage:
			g.P("            ", o.Name, "::", variantPascal, "(inner) => {")
			if v.NeedsBox {
				g.P("                let converted: __buffa_mod::", v.TypeName, " = inner.as_ref().into();")
			} else {
				g.P("                let converted: __buffa_mod::", v.TypeName, " = inner.into();")
			}
			g.P("                __buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(Box::new(converted))")
			g.P("            }")

		case FieldKindScalar:
			if v.ScalarKind == protoreflect.StringKind {
				g.P("            ", o.Name, "::", variantPascal, " { ", variantFieldName, " } => {")
				g.P("                __buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(", variantFieldName, ".clone().into())")
				g.P("            }")
			} else {
				g.P("            ", o.Name, "::", variantPascal, " { ", variantFieldName, " } => {")
				g.P("                __buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(*", variantFieldName, ")")
				g.P("            }")
			}

		case FieldKindEnum:
			g.P("            ", o.Name, "::", variantPascal, " { ", variantFieldName, " } => {")
			g.P("                __buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(*", variantFieldName, " as i32)")
			g.P("            }")

		default:
			g.P("            ", o.Name, "::", variantPascal, " { ", variantFieldName, " } => {")
			g.P("                __buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(", variantFieldName, ".clone().into())")
			g.P("            }")
		}
	}
	g.P("        });")
}

// generateBuffaBufToDomainOneof generates the buffa→domain oneof conversion.
func generateBuffaBufToDomainOneof(g *protogen.GeneratedFile, o *DomainOneof, fieldName, parentMsg string) {
	oneofPascal := toPascalCase(o.FieldName)

	g.P("            ", fieldName, ": match &b.", fieldName, " {")
	for _, v := range o.Variants {
		variantFieldName := escapeRustKeyword(toSnakeCase(v.ProtoName))
		variantPascal := v.Name

		switch v.Kind {
		case FieldKindMessage:
			g.P("                Some(__buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(inner)) => {")
			if v.NeedsBox {
				g.P("                    Some(", o.Name, "::", variantPascal, "(Box::new(inner.as_ref().try_into()?)))")
			} else {
				g.P("                    Some(", o.Name, "::", variantPascal, "(inner.as_ref().try_into()?))")
			}
			g.P("                }")

		case FieldKindScalar:
			if v.ScalarKind == protoreflect.StringKind {
				g.P("                Some(__buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(v)) => {")
				g.P("                    Some(", o.Name, "::", variantPascal, " { ", variantFieldName, ": v.to_string() })")
				g.P("                }")
			} else {
				g.P("                Some(__buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(v)) => {")
				g.P("                    Some(", o.Name, "::", variantPascal, " { ", variantFieldName, ": *v })")
				g.P("                }")
			}

		case FieldKindEnum:
			enumType := v.TypeName
			g.P("                Some(__buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(v)) => {")
			g.P("                    Some(", o.Name, "::", variantPascal, " { ", variantFieldName, ": ", enumType, "::from_i32(*v).ok_or(ConversionError::InvalidEnumValue(*v))? })")
			g.P("                }")

		default:
			g.P("                Some(__buffa_mod::oneof::", toSnakeCase(parentMsg), "::", oneofPascal, "::", variantPascal, "(v)) => {")
			g.P("                    Some(", o.Name, "::", variantPascal, " { ", variantFieldName, ": v.clone().into() })")
			g.P("                }")
		}
	}
	g.P("                None => None,")
	g.P("            },")
}
