package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

// generateRust generates Rust output files for a proto file.
func generateRust(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	// Generate domain types if requested.
	if opts.Domain {
		if err := generateRustDomain(gen, file, opts); err != nil {
			return err
		}
	}

	// Generate storage types if a backend is specified.
	if opts.Backend != "" {
		switch opts.Backend {
		case "sqlite":
			return generateRustSqlite(gen, file, opts)
		default:
			return fmt.Errorf("proto2type: unsupported Rust backend %q (supported: sqlite)", opts.Backend)
		}
	}

	return nil
}

// generateRustDomain generates a Rust domain type file for a proto file.
func generateRustDomain(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, ".type.rs")

	g := gen.NewGeneratedFile(filename, "")

	// Build IR from the proto file.
	df := BuildDomainFile(file, opts)

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// proto2type v", Version)
	g.P("// source: ", file.Desc.Path())
	g.P()

	// Scan IR for what use statements are needed
	needsChrono := false
	needsHashMap := false
	needsSerde := false
	needsSerdeJSON := false

	for _, dm := range df.Messages {
		if dm.Skip {
			continue
		}
		needsSerde = true
		irScanRustImports(dm, &needsChrono, &needsHashMap, &needsSerdeJSON)
	}

	// Check if file has enums (need serde for enums too)
	if len(df.Enums) > 0 {
		needsSerde = true
	}

	// Check for oneofs that need serde
	for _, dm := range df.Messages {
		if dm.Skip {
			continue
		}
		if len(dm.Oneofs) > 0 {
			needsSerde = true
		}
	}

	// Emit use statements
	if needsSerde {
		g.P("use serde::{Deserialize, Serialize};")
	}
	if needsChrono {
		g.P("use chrono::{DateTime, Utc};")
	}
	if needsHashMap {
		g.P("use std::collections::HashMap;")
	}
	if needsSerdeJSON {
		g.P("use serde_json;")
	}
	g.P()

	// Generate top-level enums from IR
	for _, de := range df.Enums {
		generateRustEnumFromIR(g, de)
	}

	for _, dm := range df.Messages {
		if err := generateRustDomainMessageFromIR(g, dm, opts); err != nil {
			return err
		}
	}

	return nil
}

// irScanRustImports scans a DomainMessage (and its nested messages) for types that require imports.
func irScanRustImports(dm *DomainMessage, needsChrono, needsHashMap, needsSerdeJSON *bool) {
	if dm.Skip {
		return
	}
	for _, f := range dm.Fields {
		if f.Kind == FieldKindTimestamp {
			*needsChrono = true
		}
		if f.IsMap {
			*needsHashMap = true
		}
		if f.Kind == FieldKindStruct || f.Kind == FieldKindValue ||
			f.Kind == FieldKindListValue || f.Kind == FieldKindAny {
			*needsSerdeJSON = true
		}
	}
	for _, nested := range dm.NestedMessages {
		irScanRustImports(nested, needsChrono, needsHashMap, needsSerdeJSON)
	}
}

// generateRustEnumFromIR generates a Rust enum type from a DomainEnum.
func generateRustEnumFromIR(g *protogen.GeneratedFile, de *DomainEnum) {
	// Doc comment
	if de.Comment != "" {
		for _, line := range strings.Split(de.Comment, "\n") {
			g.P("/// ", strings.TrimPrefix(line, " "))
		}
	}

	g.P("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]")
	g.P("#[repr(i32)]")
	g.P("pub enum ", de.Name, " {")

	for _, val := range de.Values {
		if val.Comment != "" {
			for _, line := range strings.Split(val.Comment, "\n") {
				g.P("    /// ", strings.TrimPrefix(line, " "))
			}
		}

		if val.IsDefault {
			g.P("    #[default]")
		}
		g.P("    ", val.Name, " = ", val.Number, ",")
	}

	g.P("}")
	g.P()

	// from_i32 impl
	g.P("impl ", de.Name, " {")
	g.P("    pub fn from_i32(value: i32) -> Option<Self> {")
	g.P("        match value {")
	for _, val := range de.Values {
		g.P("            ", val.Number, " => Some(Self::", val.Name, "),")
	}
	g.P("            _ => None,")
	g.P("        }")
	g.P("    }")
	g.P("}")
	g.P()

	// Display impl
	g.P("impl std::fmt::Display for ", de.Name, " {")
	g.P("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
	g.P("        match self {")
	for _, val := range de.Values {
		g.P("            Self::", val.Name, " => write!(f, \"", val.ProtoName, "\"),")
	}
	g.P("        }")
	g.P("    }")
	g.P("}")
	g.P()
}

// generateRustOneofEnumFromIR generates a Rust enum for a oneof group from DomainOneof.
func generateRustOneofEnumFromIR(g *protogen.GeneratedFile, do *DomainOneof) {
	g.P("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
	g.P(`#[serde(tag = "kind", content = "value")]`)
	g.P("pub enum ", do.Name, " {")

	for _, v := range do.Variants {
		variantType := rustOneofVariantTypeFromIR(v)
		g.P("    #[serde(rename = \"", v.ProtoName, "\")]")
		g.P("    ", v.Name, "(", variantType, "),")
	}

	g.P("}")
	g.P()
}

// rustOneofVariantTypeFromIR returns the Rust type for a oneof variant.
func rustOneofVariantTypeFromIR(v *OneofVariant) string {
	switch v.Kind {
	case FieldKindTimestamp:
		return "DateTime<Utc>"
	case FieldKindDuration:
		return "i64"
	case FieldKindStruct:
		return "serde_json::Map<String, serde_json::Value>"
	case FieldKindValue:
		return "serde_json::Value"
	case FieldKindListValue:
		return "Vec<serde_json::Value>"
	case FieldKindFieldMask:
		return "Vec<String>"
	case FieldKindEmpty:
		return "()"
	case FieldKindMessage:
		return "Box<" + v.TypeName + ">"
	case FieldKindEnum:
		if v.EnumAsString {
			return "String"
		}
		return v.TypeName
	case FieldKindScalar:
		return rustType(v.ScalarKind)
	}

	// Wrapper types
	if v.Kind.IsWrapper() {
		return rustWrapperTypeFromIR(v.Kind)
	}

	return rustType(v.ScalarKind)
}

// generateRustDomainMessageFromIR generates a Rust domain struct from a DomainMessage.
func generateRustDomainMessageFromIR(g *protogen.GeneratedFile, dm *DomainMessage, opts *Options) error {
	if dm.Skip {
		return nil
	}

	name := dm.Name

	// Generate nested enums first
	for _, de := range dm.NestedEnums {
		generateRustEnumFromIR(g, de)
	}

	// Generate oneof enums before the struct
	for _, do := range dm.Oneofs {
		generateRustOneofEnumFromIR(g, do)
	}

	// Doc comment
	g.P("/// Domain representation of ", dm.FullName, ".")
	if dm.Comment != "" {
		g.P("///")
		for _, line := range strings.Split(dm.Comment, "\n") {
			g.P("/// ", strings.TrimPrefix(line, " "))
		}
	}

	// Derive attributes
	g.P("#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]")
	g.P("#[non_exhaustive]")
	g.P("pub struct ", name, " {")

	// Emit fields (including interleaved oneof placeholders)
	for _, f := range dm.Fields {
		if f.IsOneof {
			rustFieldName := escapeRustKeyword(toSnakeCase(f.Name))
			g.P("    #[serde(default, skip_serializing_if = \"Option::is_none\")]")
			g.P("    pub ", rustFieldName, ": Option<", f.OneofTypeName, ">,")
			continue
		}

		protoName := f.Name
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))
		fieldType := rustDomainFieldTypeFromIR(f)

		// Serde attributes
		attrs := []string{}

		// #[serde(rename = "...")] for name overrides
		if f.NameOverride != "" {
			attrs = append(attrs, fmt.Sprintf(`rename = "%s"`, f.NameOverride))
		} else if rustFieldName != protoName {
			// Fallback: rename if snake_case differs from proto name
			attrs = append(attrs, fmt.Sprintf(`rename = "%s"`, protoName))
		}

		// #[serde(default, skip_serializing_if = "Option::is_none")] for Option fields
		if strings.HasPrefix(fieldType, "Option<") {
			attrs = append(attrs, `default`)
			attrs = append(attrs, `skip_serializing_if = "Option::is_none"`)
		}

		// #[serde(default)] for fields that should have default values
		if f.Repeated || f.IsMap {
			attrs = append(attrs, `default`)
		}

		if len(attrs) > 0 {
			g.P("    #[serde(", strings.Join(attrs, ", "), ")]")
		}

		// Duration doc comment
		if f.Kind == FieldKindDuration {
			g.P("    /// Duration in milliseconds")
		}

		g.P("    pub ", rustFieldName, ": ", fieldType, ",")
	}

	g.P("}")
	g.P()

	// Generate nested messages
	for _, nested := range dm.NestedMessages {
		if err := generateRustDomainMessageFromIR(g, nested, opts); err != nil {
			return err
		}
	}

	return nil
}

// rustDomainFieldTypeFromIR returns the Rust type for a field using the IR.
func rustDomainFieldTypeFromIR(f *DomainField) string {
	// Handle repeated fields
	if f.Repeated {
		return "Vec<" + rustDomainListElementTypeFromIR(f) + ">"
	}

	// Handle map fields
	if f.IsMap {
		keyType := rustType(f.MapKey.ScalarKind)
		valType := rustMapValueTypeFromIR(f.MapValue, f.EnumAsString)
		return fmt.Sprintf("HashMap<%s, %s>", keyType, valType)
	}

	return rustDomainSingularTypeFromIR(f)
}

// rustDomainSingularTypeFromIR returns the Rust type for a singular field using the IR.
func rustDomainSingularTypeFromIR(f *DomainField) string {
	switch f.Kind {
	case FieldKindTimestamp:
		return "DateTime<Utc>"
	case FieldKindDuration:
		return "i64"
	case FieldKindStruct:
		return "serde_json::Map<String, serde_json::Value>"
	case FieldKindValue:
		return "serde_json::Value"
	case FieldKindListValue:
		return "Vec<serde_json::Value>"
	case FieldKindFieldMask:
		return "Vec<String>"
	case FieldKindEmpty:
		return "()"
	case FieldKindAny:
		return "serde_json::Value"
	case FieldKindMessage:
		return "Option<Box<" + f.MessageTypeName + ">>"
	case FieldKindEnum:
		if f.EnumAsString {
			return "String"
		}
		return f.EnumTypeName
	case FieldKindScalar:
		if f.Optional {
			return "Option<" + rustType(f.ScalarKind) + ">"
		}
		return rustType(f.ScalarKind)
	}

	// Wrapper types
	if f.Kind.IsWrapper() {
		return rustWrapperTypeFromIR(f.Kind)
	}

	return rustType(f.ScalarKind)
}

// rustDomainListElementTypeFromIR returns the Rust element type for repeated fields.
// Unlike rustDomainSingularTypeFromIR, messages are NOT wrapped in Option<Box<>> —
// they are stored directly in the Vec.
func rustDomainListElementTypeFromIR(f *DomainField) string {
	switch f.Kind {
	case FieldKindTimestamp:
		return "DateTime<Utc>"
	case FieldKindDuration:
		return "i64"
	case FieldKindStruct:
		return "serde_json::Map<String, serde_json::Value>"
	case FieldKindValue:
		return "serde_json::Value"
	case FieldKindListValue:
		return "Vec<serde_json::Value>"
	case FieldKindFieldMask:
		return "Vec<String>"
	case FieldKindEmpty:
		return "()"
	case FieldKindAny:
		return "serde_json::Value"
	case FieldKindMessage:
		return f.MessageTypeName
	case FieldKindEnum:
		if f.EnumAsString {
			return "String"
		}
		return f.EnumTypeName
	}

	// Wrapper types
	if f.Kind.IsWrapper() {
		return rustWrapperTypeFromIR(f.Kind)
	}

	return rustType(f.ScalarKind)
}

// rustWrapperTypeFromIR returns the Rust Option type for a wrapper FieldKind.
func rustWrapperTypeFromIR(kind FieldKind) string {
	switch kind {
	case FieldKindWrapperString:
		return "Option<String>"
	case FieldKindWrapperBool:
		return "Option<bool>"
	case FieldKindWrapperInt32:
		return "Option<i32>"
	case FieldKindWrapperInt64:
		return "Option<i64>"
	case FieldKindWrapperUInt32:
		return "Option<u32>"
	case FieldKindWrapperUInt64:
		return "Option<u64>"
	case FieldKindWrapperFloat:
		return "Option<f32>"
	case FieldKindWrapperDouble:
		return "Option<f64>"
	case FieldKindWrapperBytes:
		return "Option<Vec<u8>>"
	default:
		return "Option<serde_json::Value>"
	}
}

// rustMapValueTypeFromIR returns the Rust type for a map value using MapTypeInfo.
func rustMapValueTypeFromIR(mv *MapTypeInfo, enumAsString bool) string {
	switch mv.Kind {
	case FieldKindTimestamp:
		return "DateTime<Utc>"
	case FieldKindDuration:
		return "i64"
	case FieldKindStruct:
		return "serde_json::Map<String, serde_json::Value>"
	case FieldKindValue:
		return "serde_json::Value"
	case FieldKindListValue:
		return "Vec<serde_json::Value>"
	case FieldKindFieldMask:
		return "Vec<String>"
	case FieldKindEmpty:
		return "()"
	case FieldKindMessage:
		return mv.MessageTypeName
	case FieldKindEnum:
		if enumAsString {
			return "String"
		}
		return mv.EnumTypeName
	case FieldKindScalar:
		return rustType(mv.ScalarKind)
	}

	// Wrapper types
	if mv.Kind.IsWrapper() {
		return rustWrapperTypeFromIR(mv.Kind)
	}

	return rustType(mv.ScalarKind)
}
