package generator

import (
	"fmt"
	"slices"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateRust generates Rust output files for a proto file.
func generateRust(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	// Generate domain types if requested.
	if opts.Domain {
		if err := generateRustDomain(gen, file, opts); err != nil {
			return err
		}
	}

	// Generate storage types if a backend is specified.
	if opts.Backend != "" {
		switch opts.Backend {
		case "sqlite":
			return generateRustSqlite(gen, file, opts)
		default:
			return fmt.Errorf("proto2type: unsupported Rust backend %q (supported: sqlite)", opts.Backend)
		}
	}

	return nil
}

// generateRustDomain generates a Rust domain type file for a proto file.
func generateRustDomain(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, ".type.rs")

	g := gen.NewGeneratedFile(filename, "")

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()

	// Scan for what use statements are needed
	needsChrono := false
	needsHashMap := false
	needsSerde := false

	for _, msg := range file.Messages {
		if isMessageSkipped(msg) {
			continue
		}
		needsSerde = true
		scanRustImports(msg, &needsChrono, &needsHashMap)
	}

	// Emit use statements
	if needsSerde {
		g.P("use serde::{Deserialize, Serialize};")
	}
	if needsChrono {
		g.P("use chrono::{DateTime, Utc};")
	}
	if needsHashMap {
		g.P("use std::collections::HashMap;")
	}
	g.P()

	for _, msg := range file.Messages {
		if err := generateRustDomainMessage(g, msg, opts); err != nil {
			return err
		}
	}

	return nil
}

// scanRustImports scans a message (and its nested messages) for types that require imports.
func scanRustImports(msg *protogen.Message, needsChrono, needsHashMap *bool) {
	if isMessageSkipped(msg) {
		return
	}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		if isWellKnownTimestamp(field) {
			*needsChrono = true
		}
		if field.Desc.IsMap() {
			*needsHashMap = true
		}
	}
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		scanRustImports(nested, needsChrono, needsHashMap)
	}
}

// generateRustDomainMessage generates a Rust domain struct for a single message.
func generateRustDomainMessage(g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) error {
	if isMessageSkipped(msg) {
		return nil
	}

	name := rustMessageName(msg)

	// Doc comment
	g.P("/// Domain representation of ", msg.Desc.FullName(), ".")
	if msg.Comments.Leading != "" {
		g.P("///")
		for _, line := range strings.Split(strings.TrimSpace(string(msg.Comments.Leading)), "\n") {
			g.P("/// ", strings.TrimPrefix(line, " "))
		}
	}

	// Derive attributes
	g.P("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
	g.P("pub struct ", name, " {")

	// Collect skipped oneof names for warning comments (P0-2).
	var skippedOneofs []string

	for _, field := range msg.Fields {
		// Skip oneof synthetic fields (handle the oneof group instead)
		// TODO: real oneof fields are currently skipped. Implement Rust enum
		// generation for oneof groups to match the Go backend behavior.
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !slices.Contains(skippedOneofs, oneofName) {
				skippedOneofs = append(skippedOneofs, oneofName)
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))
		fieldType := rustDomainFieldType(field, opts)

		// P1-13: Honor (proto2type.field).name option via serde rename.
		// TODO: server_timestamp and inline options need design thought for Rust.
		nameOverride := fieldNameOverride(field)

		// Serde attributes
		attrs := []string{}

		// #[serde(rename = "...")] for name overrides (P1-13)
		if nameOverride != "" {
			attrs = append(attrs, fmt.Sprintf(`rename = "%s"`, nameOverride))
		} else if rustFieldName != protoName {
			// Fallback: rename if snake_case differs from proto name
			attrs = append(attrs, fmt.Sprintf(`rename = "%s"`, protoName))
		}

		// #[serde(default, skip_serializing_if = "Option::is_none")] for Option fields (P1-8)
		if strings.HasPrefix(fieldType, "Option<") {
			attrs = append(attrs, `default`)
			attrs = append(attrs, `skip_serializing_if = "Option::is_none"`)
		}

		// #[serde(default)] for fields that should have default values
		if shouldSerdeDefault(field) {
			attrs = append(attrs, `default`)
		}

		if len(attrs) > 0 {
			g.P("    #[serde(", strings.Join(attrs, ", "), ")]")
		}

		// P0-1: Duration doc comment
		if isWellKnownDuration(field) {
			g.P("    /// Duration in milliseconds")
		}

		g.P("    pub ", rustFieldName, ": ", fieldType, ",")
	}

	// Emit oneof warning comments (P0-2)
	for _, oneofName := range skippedOneofs {
		g.P("    // WARNING: oneof '", oneofName, "' is not yet supported — fields omitted")
	}

	g.P("}")
	g.P()

	// Generate nested messages
	for _, nested := range msg.Messages {
		// Skip map entry messages
		if nested.Desc.IsMapEntry() {
			continue
		}
		if err := generateRustDomainMessage(g, nested, opts); err != nil {
			return err
		}
	}

	return nil
}

// isOptionalRustField returns true if the field is represented as Option<T> in Rust.
func isOptionalRustField(field *protogen.Field, opts *Options) bool {
	if field.Desc.HasOptionalKeyword() {
		return true
	}
	if isWellKnownWrapper(field) {
		return true
	}
	// Nested messages are Option<Box<T>>
	if field.Desc.Kind() == protoreflect.MessageKind && !field.Desc.IsList() && !field.Desc.IsMap() &&
		!isWellKnownTimestamp(field) && !isWellKnownDuration(field) {
		return true
	}
	return false
}

// shouldSerdeDefault returns true if the field should have #[serde(default)].
func shouldSerdeDefault(field *protogen.Field) bool {
	// Vec and HashMap fields benefit from default
	if field.Desc.IsList() || field.Desc.IsMap() {
		return true
	}
	return false
}
