package generator

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateRustSqlite generates a Rust SQLite storage type file for a proto file.
func generateRustSqlite(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, "_sqlite.type.rs")

	g := gen.NewGeneratedFile(filename, "")

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// proto2type v", Version)
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: sqlite")
	g.P()

	// Scan for needed imports
	needsChrono := false

	for _, msg := range file.Messages {
		if isMessageSkipped(msg) {
			continue
		}
		scanRustSqliteImports(msg, &needsChrono)
	}

	// Emit use statements
	g.P("use super::*;")
	g.P("use serde::{Deserialize, Serialize};")
	if needsChrono {
		g.P("use chrono::{DateTime, Utc};")
	}
	g.P()

	// Emit ConversionError type (P1-9)
	generateRustConversionError(g, needsChrono)

	// Generate helper functions if chrono is needed
	if needsChrono {
		generateRustEpochMsHelpers(g)
	}

	for _, msg := range file.Messages {
		generateRustSqliteMessage(g, msg, opts)
	}

	return nil
}

// scanRustSqliteImports scans a message for SQLite-specific import needs.
func scanRustSqliteImports(msg *protogen.Message, needsChrono *bool) {
	if isMessageSkipped(msg) {
		return
	}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		if isDocumentID(field) {
			continue
		}
		if isWellKnownTimestamp(field) {
			*needsChrono = true
		}
	}
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		scanRustSqliteImports(nested, needsChrono)
	}
}

// generateRustConversionError emits a ConversionError enum type for SQLite conversion (P1-9).
func generateRustConversionError(g *protogen.GeneratedFile, needsChrono bool) {
	g.P("#[derive(Debug)]")
	g.P("pub enum ConversionError {")
	g.P("    Json(serde_json::Error),")
	if needsChrono {
		g.P("    InvalidTimestamp(i64),")
	}
	g.P("}")
	g.P()
	g.P("impl std::fmt::Display for ConversionError {")
	g.P("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
	g.P("        match self {")
	g.P(`            Self::Json(e) => write!(f, "json: {e}"),`)
	if needsChrono {
		g.P(`            Self::InvalidTimestamp(ms) => write!(f, "invalid timestamp: {ms}ms"),`)
	}
	g.P("        }")
	g.P("    }")
	g.P("}")
	g.P()
	g.P("impl std::error::Error for ConversionError {}")
	g.P()
	g.P("impl From<serde_json::Error> for ConversionError {")
	g.P("    fn from(e: serde_json::Error) -> Self {")
	g.P("        Self::Json(e)")
	g.P("    }")
	g.P("}")
	g.P()
}

// generateRustEpochMsHelpers generates epoch_ms conversion functions.
func generateRustEpochMsHelpers(g *protogen.GeneratedFile) {
	g.P("/// Converts epoch milliseconds to a chrono DateTime<Utc>.")
	g.P("#[allow(dead_code)]")
	g.P("fn epoch_ms_to_datetime(ms: i64) -> Result<DateTime<Utc>, ConversionError> {")
	g.P("    DateTime::from_timestamp_millis(ms).ok_or(ConversionError::InvalidTimestamp(ms))")
	g.P("}")
	g.P()
	g.P("/// Converts a chrono DateTime<Utc> to epoch milliseconds.")
	g.P("#[allow(dead_code)]")
	g.P("fn datetime_to_epoch_ms(dt: &DateTime<Utc>) -> i64 {")
	g.P("    dt.timestamp_millis()")
	g.P("}")
	g.P()
}

// generateRustSqliteMessage generates a SQLite Row struct and conversions for a message.
func generateRustSqliteMessage(g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) {
	if isMessageSkipped(msg) {
		return
	}

	name := rustMessageName(msg)
	rowName := name + "Row"
	domainName := name

	// Find document_id field
	var docIDField *protogen.Field
	for _, field := range msg.Fields {
		if isDocumentID(field) {
			docIDField = field
			break
		}
	}

	// Collect oneof groups
	seenOneofs := map[string]bool{}

	// Row struct
	g.P("/// SQLite storage representation of ", msg.Desc.FullName(), ".")
	g.P("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
	g.P("pub struct ", rowName, " {")

	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true

				// Oneof stored as JSON string
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))
				g.P("    pub ", rustFieldName, ": Option<String>,")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		// Document ID is excluded from the Row struct (passed separately)
		if isDocumentID(field) {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))
		fieldType := rustSqliteFieldType(field, opts)

		g.P("    pub ", rustFieldName, ": ", fieldType, ",")
	}

	g.P("}")
	g.P()

	// impl block
	g.P("impl ", rowName, " {")

	// from_row: construct from rusqlite::Row
	g.P("    /// Constructs a ", rowName, " from a rusqlite::Row using named column access.")
	g.P("    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {")
	g.P("        Ok(Self {")

	seenOneofs = map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))
				g.P("            ", rustFieldName, ": row.get(\"", oneofName, "\")?,")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		if isDocumentID(field) {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))

		g.P("            ", rustFieldName, ": row.get(\"", protoName, "\")?,")
	}

	g.P("        })")
	g.P("    }")
	g.P()

	// to_domain: convert Row to domain type
	g.P("    /// Converts this row to the domain type.")
	if docIDField != nil {
		docIDRustName := escapeRustKeyword(toSnakeCase(string(docIDField.Desc.Name())))
		g.P("    pub fn to_domain(&self, ", docIDRustName, ": String) -> Result<", domainName, ", ConversionError> {")
	} else {
		g.P("    pub fn to_domain(&self) -> Result<", domainName, ", ConversionError> {")
	}
	g.P("        Ok(", domainName, " {")

	seenOneofs = map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))
				g.P("            ", rustFieldName, ": match &self.", rustFieldName, " { Some(s) => Some(serde_json::from_str(s)?), None => None },")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))

		if isDocumentID(field) {
			// Inject from parameter
			g.P("            ", rustFieldName, ",")
			continue
		}

		conversion := rustSqliteToDomainConversion(field, rustFieldName, opts)
		g.P("            ", rustFieldName, ": ", conversion, ",")
	}

	g.P("        })")
	g.P("    }")
	g.P()

	// into_domain: consuming variant (P1-10)
	g.P("    /// Converts this row into the domain type, consuming self.")
	if docIDField != nil {
		docIDRustName := escapeRustKeyword(toSnakeCase(string(docIDField.Desc.Name())))
		g.P("    pub fn into_domain(self, ", docIDRustName, ": String) -> Result<", domainName, ", ConversionError> {")
	} else {
		g.P("    pub fn into_domain(self) -> Result<", domainName, ", ConversionError> {")
	}
	g.P("        Ok(", domainName, " {")

	seenOneofs = map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))
				g.P("            ", rustFieldName, ": match self.", rustFieldName, " { Some(s) => Some(serde_json::from_str(&s)?), None => None },")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))

		if isDocumentID(field) {
			// Inject from parameter
			g.P("            ", rustFieldName, ",")
			continue
		}

		conversion := rustSqliteIntoDomainConversion(field, rustFieldName, opts)
		g.P("            ", rustFieldName, ": ", conversion, ",")
	}

	g.P("        })")
	g.P("    }")
	g.P()

	// from_domain: convert domain type to Row
	g.P("    /// Constructs a row from the domain type.")
	g.P("    pub fn from_domain(d: &", domainName, ") -> Result<Self, ConversionError> {")
	g.P("        Ok(Self {")

	seenOneofs = map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))
				g.P("            ", rustFieldName, ": match &d.", rustFieldName, " { Some(v) => Some(serde_json::to_string(v)?), None => None },")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		if isDocumentID(field) {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))

		conversion := rustSqliteFromDomainConversion(field, rustFieldName, opts)
		g.P("            ", rustFieldName, ": ", conversion, ",")
	}

	g.P("        })")
	g.P("    }")

	g.P("}")
	g.P()

	// TryFrom impls
	// TryFrom<&DomainType> for RowType (always generated)
	g.P("impl TryFrom<&", domainName, "> for ", rowName, " {")
	g.P("    type Error = ConversionError;")
	g.P("    fn try_from(d: &", domainName, ") -> Result<Self, Self::Error> {")
	g.P("        Self::from_domain(d)")
	g.P("    }")
	g.P("}")
	g.P()

	// TryFrom<RowType> for DomainType (only when no document_id)
	if docIDField == nil {
		g.P("impl TryFrom<", rowName, "> for ", domainName, " {")
		g.P("    type Error = ConversionError;")
		g.P("    fn try_from(row: ", rowName, ") -> Result<Self, Self::Error> {")
		g.P("        row.into_domain()")
		g.P("    }")
		g.P("}")
		g.P()
	}

	// Nested messages
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		generateRustSqliteMessage(g, nested, opts)
	}
}

// rustSqliteFieldType returns the SQLite-appropriate Rust type for a field.
func rustSqliteFieldType(field *protogen.Field, opts *Options) string {
	// Timestamps -> i64 (epoch_ms)
	if isWellKnownTimestamp(field) {
		return "i64"
	}
	// Durations -> i64 (milliseconds)
	if isWellKnownDuration(field) {
		return "i64"
	}

	// Wrapper types -> Option<T> with underlying SQLite type
	if isWellKnownWrapper(field) {
		return rustSqliteWrapperType(field)
	}

	// WKT JSON types -> String (JSON serialized)
	if isWellKnownStruct(field) || isWellKnownValue(field) || isWellKnownListValue(field) || isWellKnownFieldMask(field) {
		return "String"
	}

	// Empty -> skip (unit type has no storage representation, but if present use String)
	if isWellKnownEmpty(field) {
		return "String"
	}

	// Any -> String (JSON)
	if isWellKnownAny(field) {
		// TODO: google.protobuf.Any is too complex for auto-mapping
		return "String"
	}

	// Nested messages -> Option<String> (JSON serialized, NULL for absent) (P1-12)
	if field.Desc.Kind() == protoreflect.MessageKind && !field.Desc.IsList() && !field.Desc.IsMap() {
		return "Option<String>"
	}

	// Repeated fields -> String (JSON serialized)
	if field.Desc.IsList() {
		return "String"
	}

	// Map fields -> String (JSON serialized)
	if field.Desc.IsMap() {
		return "String"
	}

	// Enum types -> i32 in the database
	if field.Desc.Kind() == protoreflect.EnumKind {
		if isEnumAsString(field, opts) {
			return "String"
		}
		return "i32"
	}

	// Optional scalars
	if field.Desc.HasOptionalKeyword() {
		return "Option<" + rustSqliteScalarType(field.Desc.Kind()) + ">"
	}

	return rustSqliteScalarType(field.Desc.Kind())
}

// rustSqliteScalarType returns the SQLite-compatible Rust type for a scalar kind.
func rustSqliteScalarType(kind protoreflect.Kind) string {
	switch kind {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "i32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "i64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "i64" // SQLite has no unsigned; i64 is safe for u32 range
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "i64" // SQLite has no unsigned; NOTE: u64 > i64::MAX will overflow
	case protoreflect.FloatKind:
		return "f32"
	case protoreflect.DoubleKind:
		return "f64"
	case protoreflect.StringKind:
		return "String"
	case protoreflect.BytesKind:
		return "Vec<u8>"
	default:
		return "String"
	}
}

// rustSqliteWrapperType returns the SQLite Option type for a well-known wrapper.
func rustSqliteWrapperType(field *protogen.Field) string {
	switch string(field.Desc.Message().FullName()) {
	case "google.protobuf.StringValue":
		return "Option<String>"
	case "google.protobuf.BoolValue":
		return "Option<bool>"
	case "google.protobuf.Int32Value":
		return "Option<i32>"
	case "google.protobuf.Int64Value":
		return "Option<i64>"
	case "google.protobuf.UInt32Value":
		return "Option<u32>"
	case "google.protobuf.UInt64Value":
		return "Option<u64>"
	case "google.protobuf.FloatValue":
		return "Option<f32>"
	case "google.protobuf.DoubleValue":
		return "Option<f64>"
	case "google.protobuf.BytesValue":
		return "Option<Vec<u8>>"
	default:
		return "Option<String>"
	}
}

// rustSqliteToDomainConversion returns the expression to convert a SQLite row field to a domain field.
func rustSqliteToDomainConversion(field *protogen.Field, fieldName string, opts *Options) string {
	if isWellKnownTimestamp(field) {
		return fmt.Sprintf("epoch_ms_to_datetime(self.%s)?", fieldName)
	}
	// P0-1: Duration is i64 in both domain and SQLite, just copy
	if isWellKnownDuration(field) {
		return fmt.Sprintf("self.%s", fieldName)
	}
	if isWellKnownWrapper(field) {
		return fmt.Sprintf("self.%s.clone()", fieldName)
	}
	// WKT JSON types: deserialize from String
	if isWellKnownStruct(field) || isWellKnownValue(field) || isWellKnownListValue(field) || isWellKnownFieldMask(field) {
		return fmt.Sprintf("serde_json::from_str(&self.%s)?", fieldName)
	}
	if isWellKnownEmpty(field) {
		return "()"
	}
	if isWellKnownAny(field) {
		return fmt.Sprintf("serde_json::from_str(&self.%s)?", fieldName)
	}
	// Nested message: deserialize from Option<String> (P1-12)
	if isNestedMessage(field) {
		return fmt.Sprintf("match &self.%s { Some(s) => Some(Box::new(serde_json::from_str(s)?)), None => None }", fieldName)
	}
	// Repeated: deserialize from JSON string
	if field.Desc.IsList() {
		return fmt.Sprintf("serde_json::from_str(&self.%s)?", fieldName)
	}
	// Map: deserialize from JSON string
	if field.Desc.IsMap() {
		return fmt.Sprintf("serde_json::from_str(&self.%s)?", fieldName)
	}
	// Enum types: convert from i32 to Rust enum
	if field.Desc.Kind() == protoreflect.EnumKind {
		if isEnumAsString(field, opts) {
			return fmt.Sprintf("self.%s.clone()", fieldName)
		}
		enumTypeName := rustEnumTypeName(field)
		return fmt.Sprintf("%s::from_i32(self.%s).unwrap_or_default()", enumTypeName, fieldName)
	}
	// P0-3: unsigned types need cast from i64
	if field.Desc.Kind() == protoreflect.Uint32Kind || field.Desc.Kind() == protoreflect.Fixed32Kind {
		return fmt.Sprintf("self.%s as u32", fieldName)
	}
	if field.Desc.Kind() == protoreflect.Uint64Kind || field.Desc.Kind() == protoreflect.Fixed64Kind {
		return fmt.Sprintf("self.%s as u64", fieldName)
	}
	// Bytes
	if field.Desc.Kind() == protoreflect.BytesKind {
		return fmt.Sprintf("self.%s.clone()", fieldName)
	}
	// String types need clone
	if field.Desc.Kind() == protoreflect.StringKind {
		return fmt.Sprintf("self.%s.clone()", fieldName)
	}
	// Optional scalars
	if field.Desc.HasOptionalKeyword() {
		return fmt.Sprintf("self.%s", fieldName)
	}
	return fmt.Sprintf("self.%s", fieldName)
}

// rustSqliteIntoDomainConversion returns the expression for consuming conversion (into_domain).
// Like rustSqliteToDomainConversion but moves String fields instead of cloning.
func rustSqliteIntoDomainConversion(field *protogen.Field, fieldName string, opts *Options) string {
	if isWellKnownTimestamp(field) {
		return fmt.Sprintf("epoch_ms_to_datetime(self.%s)?", fieldName)
	}
	if isWellKnownDuration(field) {
		return fmt.Sprintf("self.%s", fieldName)
	}
	if isWellKnownWrapper(field) {
		return fmt.Sprintf("self.%s", fieldName)
	}
	// WKT JSON types: deserialize from String
	if isWellKnownStruct(field) || isWellKnownValue(field) || isWellKnownListValue(field) || isWellKnownFieldMask(field) {
		return fmt.Sprintf("serde_json::from_str(&self.%s)?", fieldName)
	}
	if isWellKnownEmpty(field) {
		return "()"
	}
	if isWellKnownAny(field) {
		return fmt.Sprintf("serde_json::from_str(&self.%s)?", fieldName)
	}
	// Nested message: deserialize from Option<String>
	if isNestedMessage(field) {
		return fmt.Sprintf("match self.%s { Some(s) => Some(Box::new(serde_json::from_str(&s)?)), None => None }", fieldName)
	}
	// Repeated: deserialize from JSON string
	if field.Desc.IsList() {
		return fmt.Sprintf("serde_json::from_str(&self.%s)?", fieldName)
	}
	// Map: deserialize from JSON string
	if field.Desc.IsMap() {
		return fmt.Sprintf("serde_json::from_str(&self.%s)?", fieldName)
	}
	// Enum types: convert from i32 to Rust enum
	if field.Desc.Kind() == protoreflect.EnumKind {
		if isEnumAsString(field, opts) {
			return fmt.Sprintf("self.%s", fieldName)
		}
		enumTypeName := rustEnumTypeName(field)
		return fmt.Sprintf("%s::from_i32(self.%s).unwrap_or_default()", enumTypeName, fieldName)
	}
	// P0-3: unsigned types need cast from i64
	if field.Desc.Kind() == protoreflect.Uint32Kind || field.Desc.Kind() == protoreflect.Fixed32Kind {
		return fmt.Sprintf("self.%s as u32", fieldName)
	}
	if field.Desc.Kind() == protoreflect.Uint64Kind || field.Desc.Kind() == protoreflect.Fixed64Kind {
		return fmt.Sprintf("self.%s as u64", fieldName)
	}
	// Bytes (Vec<u8> can be moved)
	if field.Desc.Kind() == protoreflect.BytesKind {
		return fmt.Sprintf("self.%s", fieldName)
	}
	// String types are moved (no clone)
	if field.Desc.Kind() == protoreflect.StringKind {
		return fmt.Sprintf("self.%s", fieldName)
	}
	// Optional scalars
	if field.Desc.HasOptionalKeyword() {
		return fmt.Sprintf("self.%s", fieldName)
	}
	return fmt.Sprintf("self.%s", fieldName)
}

// rustSqliteFromDomainConversion returns the expression to convert a domain field to a SQLite row field.
func rustSqliteFromDomainConversion(field *protogen.Field, fieldName string, opts *Options) string {
	if isWellKnownTimestamp(field) {
		return fmt.Sprintf("datetime_to_epoch_ms(&d.%s)", fieldName)
	}
	// P0-1: Duration is i64 in both domain and SQLite, just copy
	if isWellKnownDuration(field) {
		return fmt.Sprintf("d.%s", fieldName)
	}
	if isWellKnownWrapper(field) {
		return fmt.Sprintf("d.%s.clone()", fieldName)
	}
	// WKT JSON types: serialize to String
	if isWellKnownStruct(field) || isWellKnownValue(field) || isWellKnownListValue(field) || isWellKnownFieldMask(field) {
		return fmt.Sprintf("serde_json::to_string(&d.%s)?", fieldName)
	}
	if isWellKnownEmpty(field) {
		return `"()".to_string()`
	}
	if isWellKnownAny(field) {
		return fmt.Sprintf("serde_json::to_string(&d.%s)?", fieldName)
	}
	// Nested message: serialize to Option<String> (P1-12)
	if isNestedMessage(field) {
		return fmt.Sprintf("match &d.%s { Some(v) => Some(serde_json::to_string(v.as_ref())?), None => None }", fieldName)
	}
	// Repeated: serialize to JSON string
	if field.Desc.IsList() {
		return fmt.Sprintf("serde_json::to_string(&d.%s)?", fieldName)
	}
	// Map: serialize to JSON string
	if field.Desc.IsMap() {
		return fmt.Sprintf("serde_json::to_string(&d.%s)?", fieldName)
	}
	// P0-3: unsigned types need cast to i64 for SQLite
	if field.Desc.Kind() == protoreflect.Uint32Kind || field.Desc.Kind() == protoreflect.Fixed32Kind {
		return fmt.Sprintf("d.%s as i64", fieldName)
	}
	if field.Desc.Kind() == protoreflect.Uint64Kind || field.Desc.Kind() == protoreflect.Fixed64Kind {
		return fmt.Sprintf("d.%s as i64", fieldName)
	}
	// Bytes
	if field.Desc.Kind() == protoreflect.BytesKind {
		return fmt.Sprintf("d.%s.clone()", fieldName)
	}
	// Strings need clone
	if field.Desc.Kind() == protoreflect.StringKind {
		return fmt.Sprintf("d.%s.clone()", fieldName)
	}
	// Optional scalars
	if field.Desc.HasOptionalKeyword() {
		return fmt.Sprintf("d.%s", fieldName)
	}
	// Enum types: store as i32
	if field.Desc.Kind() == protoreflect.EnumKind {
		if isEnumAsString(field, opts) {
			return fmt.Sprintf("d.%s.clone()", fieldName)
		}
		return fmt.Sprintf("d.%s as i32", fieldName)
	}
	return fmt.Sprintf("d.%s", fieldName)
}

