package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateRustPostgres generates a Rust PostgreSQL storage type file for a proto file.
func generateRustPostgres(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename, err := outputFilename(file.GeneratedFilenamePrefix, "_postgres.type.rs")
	if err != nil {
		return err
	}

	g := gen.NewGeneratedFile(filename, "")

	// Build IR for import scanning.
	df, err := BuildDomainFile(file, opts)
	if err != nil {
		return err
	}

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// proto2type v", Version)
	g.P("// source: ", file.Desc.Path())
	g.P("// backend: postgres")
	g.P()

	// Scan IR for needed imports.
	needsChrono := irNeedsChronoSqlite(df.Messages)

	// Emit use statements
	g.P("use super::*;")
	g.P("use serde::{Deserialize, Serialize};")
	if needsChrono {
		g.P("use chrono::{DateTime, Utc};")
	}
	g.P()

	// Build a lookup from FullName -> *protogen.Message for converter generation.
	protoMsgMap := buildProtoMessageMap(file.Messages)

	for _, dm := range df.Messages {
		msg := protoMsgMap[dm.FullName]
		if msg == nil {
			return fmt.Errorf("proto2type: no protogen.Message found for IR message %q", dm.FullName)
		}
		generateRustPostgresMessage(g, dm, msg, protoMsgMap, opts)
	}

	return nil
}

// generateRustPostgresMessage generates a PostgreSQL storage struct and conversions for a message.
func generateRustPostgresMessage(g *protogen.GeneratedFile, dm *DomainMessage, msg *protogen.Message, protoMsgMap map[string]*protogen.Message, opts *Options) {
	if dm.Skip {
		return
	}

	pgName := dm.Name + "Postgres"
	domainName := dm.Name

	// Find document_id field name from IR
	var docIDField *protogen.Field
	for _, f := range dm.Fields {
		if f.Computed != nil {
			continue
		}
		if f.DocID {
			for _, field := range msg.Fields {
				if isDocumentID(field) {
					docIDField = field
					break
				}
			}
			break
		}
	}

	// Build a lookup from proto field name to NeedsBox flag.
	needsBoxMap := make(map[string]bool)
	for _, f := range dm.Fields {
		if f.Computed != nil {
			continue
		}
		needsBoxMap[f.Name] = f.NeedsBox
	}

	// Postgres struct with sqlx::FromRow derive
	g.P("/// PostgreSQL storage representation of ", dm.FullName, ".")
	g.P("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, sqlx::FromRow)]")
	g.P("pub struct ", pgName, " {")

	for _, f := range dm.Fields {
		if f.Computed != nil {
			continue
		}
		if f.IsOneof {
			// Oneof stored as JSONB via sqlx::types::Json
			rustFieldName := escapeRustKeyword(toSnakeCase(f.Name))
			g.P("    pub ", rustFieldName, ": Option<sqlx::types::Json<serde_json::Value>>,")
			continue
		}
		if f.DocID {
			continue // Document ID passed separately
		}

		rustFieldName := escapeRustKeyword(toSnakeCase(f.Name))
		fieldType := rustPostgresFieldTypeFromIR(f)

		g.P("    pub ", rustFieldName, ": ", fieldType, ",")
	}

	g.P("}")
	g.P()

	// impl block with to_domain, into_domain, from_domain
	g.P("impl ", pgName, " {")

	// to_domain: convert Postgres struct to domain type
	g.P("    /// Converts this row to the domain type.")
	if docIDField != nil {
		docIDRustName := escapeRustKeyword(toSnakeCase(string(docIDField.Desc.Name())))
		g.P("    pub fn to_domain(&self, ", docIDRustName, ": String) -> Result<", domainName, ", ConversionError> {")
	} else {
		g.P("    pub fn to_domain(&self) -> Result<", domainName, ", ConversionError> {")
	}
	g.P("        Ok(", domainName, " {")

	seenOneofs := map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))
				g.P("            ", rustFieldName, ": match &self.", rustFieldName, " { Some(json) => Some(serde_json::from_value(json.0.clone())?), None => None },")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		if getComputedField(field) != nil {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))

		if isDocumentID(field) {
			g.P("            ", rustFieldName, ",")
			continue
		}

		conversion := rustPostgresToDomainConversion(field, rustFieldName, opts, needsBoxMap[protoName])
		g.P("            ", rustFieldName, ": ", conversion, ",")
	}

	g.P("        })")
	g.P("    }")
	g.P()

	// into_domain: consuming variant
	g.P("    /// Converts this row into the domain type, consuming self.")
	if docIDField != nil {
		docIDRustName := escapeRustKeyword(toSnakeCase(string(docIDField.Desc.Name())))
		g.P("    pub fn into_domain(self, ", docIDRustName, ": String) -> Result<", domainName, ", ConversionError> {")
	} else {
		g.P("    pub fn into_domain(self) -> Result<", domainName, ", ConversionError> {")
	}
	g.P("        Ok(", domainName, " {")

	seenOneofs = map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))
				g.P("            ", rustFieldName, ": match self.", rustFieldName, " { Some(json) => Some(serde_json::from_value(json.0)?), None => None },")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		if getComputedField(field) != nil {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))

		if isDocumentID(field) {
			g.P("            ", rustFieldName, ",")
			continue
		}

		conversion := rustPostgresIntoDomainConversion(field, rustFieldName, opts, needsBoxMap[protoName])
		g.P("            ", rustFieldName, ": ", conversion, ",")
	}

	g.P("        })")
	g.P("    }")
	g.P()

	// from_domain: convert domain type to Postgres struct
	g.P("    /// Constructs a row from the domain type.")
	g.P("    pub fn from_domain(d: &", domainName, ") -> Result<Self, ConversionError> {")
	g.P("        Ok(Self {")

	seenOneofs = map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))
				g.P("            ", rustFieldName, ": match &d.", rustFieldName, " { Some(v) => Some(sqlx::types::Json(serde_json::to_value(v)?)), None => None },")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		if getComputedField(field) != nil {
			continue
		}
		if isDocumentID(field) {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))

		conversion := rustPostgresFromDomainConversion(field, rustFieldName, opts, needsBoxMap[protoName])
		g.P("            ", rustFieldName, ": ", conversion, ",")
	}

	g.P("        })")
	g.P("    }")

	g.P("}")
	g.P()

	// TryFrom impls
	g.P("impl TryFrom<&", domainName, "> for ", pgName, " {")
	g.P("    type Error = ConversionError;")
	g.P("    fn try_from(d: &", domainName, ") -> Result<Self, Self::Error> {")
	g.P("        Self::from_domain(d)")
	g.P("    }")
	g.P("}")
	g.P()

	if docIDField == nil {
		g.P("impl TryFrom<", pgName, "> for ", domainName, " {")
		g.P("    type Error = ConversionError;")
		g.P("    fn try_from(row: ", pgName, ") -> Result<Self, Self::Error> {")
		g.P("        row.into_domain()")
		g.P("    }")
		g.P("}")
		g.P()
	}

	// Nested messages
	for _, nested := range dm.NestedMessages {
		nestedMsg := protoMsgMap[nested.FullName]
		if nestedMsg == nil {
			continue
		}
		generateRustPostgresMessage(g, nested, nestedMsg, protoMsgMap, opts)
	}
}

// rustPostgresFieldTypeFromIR returns the Postgres-appropriate Rust type for a field using the IR.
func rustPostgresFieldTypeFromIR(f *DomainField) string {
	// Repeated fields -> sqlx::types::Json<Vec<T>>
	if f.Repeated {
		inner := rustPostgresScalarOrMessageType(f)
		return "sqlx::types::Json<Vec<" + inner + ">>"
	}

	// Map fields -> sqlx::types::Json<HashMap<K,V>>
	if f.IsMap {
		keyType := rustPostgresMapKeyType(f)
		valType := "serde_json::Value" // generic JSON for complex map values
		if f.MapValue != nil {
			switch f.MapValue.Kind {
			case FieldKindScalar:
				valType = rustSqliteScalarType(f.MapValue.ScalarKind)
			case FieldKindEnum:
				valType = f.MapValue.EnumTypeName
			}
		}
		return "sqlx::types::Json<std::collections::HashMap<" + keyType + ", " + valType + ">>"
	}

	switch f.Kind {
	case FieldKindTimestamp:
		if f.Optional {
			return "Option<DateTime<Utc>>"
		}
		return "DateTime<Utc>"
	case FieldKindDuration:
		if f.Optional {
			return "Option<i64>"
		}
		return "i64"
	case FieldKindStruct, FieldKindValue, FieldKindListValue, FieldKindAny, FieldKindEmpty:
		return "sqlx::types::Json<serde_json::Value>"
	case FieldKindMessage:
		typeName := f.MessageTypeName + "Postgres"
		if f.NeedsBox {
			return "Option<Box<" + typeName + ">>"
		}
		return "Option<sqlx::types::Json<" + typeName + ">>"
	case FieldKindEnum:
		if f.Optional {
			return "Option<i32>"
		}
		return "i32"
	case FieldKindFieldMask:
		return "Vec<String>"
	}

	// Wrapper types -> Option<T>
	if f.Kind.IsWrapper() {
		return rustSqliteWrapperTypeFromIR(f.Kind)
	}

	// Scalars
	if f.Optional {
		return "Option<" + rustSqliteScalarType(f.ScalarKind) + ">"
	}
	return rustSqliteScalarType(f.ScalarKind)
}

// rustPostgresScalarOrMessageType returns the inner type for Vec/repeated fields.
func rustPostgresScalarOrMessageType(f *DomainField) string {
	switch f.Kind {
	case FieldKindMessage:
		return f.MessageTypeName
	case FieldKindEnum:
		return f.EnumTypeName
	case FieldKindTimestamp:
		return "DateTime<Utc>"
	default:
		return rustSqliteScalarType(f.ScalarKind)
	}
}

// rustPostgresMapKeyType returns the Rust type for a map key field.
func rustPostgresMapKeyType(f *DomainField) string {
	if f.MapKey == nil {
		return "String"
	}
	return rustSqliteScalarType(f.MapKey.ScalarKind)
}

// rustPostgresToDomainConversion generates the expression to convert a Postgres field to domain.
func rustPostgresToDomainConversion(field *protogen.Field, rustFieldName string, opts *Options, needsBox bool) string {
	// Repeated fields: unwrap Json wrapper
	if field.Desc.IsList() {
		return "self." + rustFieldName + ".0.clone()"
	}
	// Map fields: unwrap Json wrapper
	if field.Desc.IsMap() {
		return "self." + rustFieldName + ".0.clone()"
	}
	// Timestamps: DateTime<Utc> maps directly to domain
	if isWellKnownTimestamp(field) {
		if field.Desc.HasOptionalKeyword() {
			return "self." + rustFieldName + ".clone()"
		}
		return "self." + rustFieldName + ".clone()"
	}
	// Duration: i64 microseconds -> domain duration
	if isWellKnownDuration(field) {
		return "self." + rustFieldName
	}
	// WKT JSON types
	if isWellKnownStruct(field) || isWellKnownValue(field) || isWellKnownListValue(field) || isWellKnownFieldMask(field) || isWellKnownEmpty(field) || isWellKnownAny(field) {
		return "serde_json::from_value(self." + rustFieldName + ".0.clone())?"
	}
	// Wrapper types
	if isWellKnownWrapper(field) {
		return "self." + rustFieldName + ".clone()"
	}
	// Nested messages: unwrap Json wrapper
	if field.Desc.Kind() == protoreflect.MessageKind {
		if needsBox {
			return "self." + rustFieldName + ".as_ref().map(|b| *b.clone())"
		}
		return "self." + rustFieldName + ".as_ref().map(|j| j.0.clone())"
	}
	// Enums
	if field.Desc.Kind() == protoreflect.EnumKind {
		enumName := rustEnumTypeName(field)
		if isEnumAsString(field, opts) {
			if field.Desc.HasOptionalKeyword() {
				return "self." + rustFieldName + ".as_ref().map(|s| s.parse()).transpose().map_err(|_| ConversionError::InvalidEnumValue(0))?"
			}
			return "self." + rustFieldName + `.parse().map_err(|_| ConversionError::InvalidEnumValue(0))?`
		}
		if field.Desc.HasOptionalKeyword() {
			return "self." + rustFieldName + ".map(|v| " + enumName + "::try_from(v)).transpose()?"
		}
		return enumName + "::try_from(self." + rustFieldName + ")?"
	}
	// Scalars
	return "self." + rustFieldName + ".clone()"
}

// rustPostgresIntoDomainConversion generates the consuming conversion expression.
func rustPostgresIntoDomainConversion(field *protogen.Field, rustFieldName string, opts *Options, needsBox bool) string {
	// For consuming conversion, replace self. references and remove .clone() where possible
	conv := rustPostgresToDomainConversion(field, rustFieldName, opts, needsBox)
	// Replace &self. with self. for consuming variant
	conv = strings.ReplaceAll(conv, "&self.", "self.")
	// Remove .clone() for owned values
	conv = strings.ReplaceAll(conv, ".clone()", "")
	// Fix .as_ref() to work on owned values
	if field.Desc.Kind() == protoreflect.MessageKind && !field.Desc.IsList() && !field.Desc.IsMap() {
		if needsBox {
			return "self." + rustFieldName + ".map(|b| *b)"
		}
		return "self." + rustFieldName + ".map(|j| j.0)"
	}
	return conv
}

// rustPostgresFromDomainConversion generates the expression to convert from domain to Postgres.
func rustPostgresFromDomainConversion(field *protogen.Field, rustFieldName string, opts *Options, needsBox bool) string {
	// Repeated fields: wrap in Json
	if field.Desc.IsList() {
		return "sqlx::types::Json(d." + rustFieldName + ".clone())"
	}
	// Map fields: wrap in Json
	if field.Desc.IsMap() {
		return "sqlx::types::Json(d." + rustFieldName + ".clone())"
	}
	// Timestamps
	if isWellKnownTimestamp(field) {
		return "d." + rustFieldName + ".clone()"
	}
	// Duration
	if isWellKnownDuration(field) {
		return "d." + rustFieldName
	}
	// WKT JSON types
	if isWellKnownStruct(field) || isWellKnownValue(field) || isWellKnownListValue(field) || isWellKnownFieldMask(field) || isWellKnownEmpty(field) || isWellKnownAny(field) {
		return "sqlx::types::Json(serde_json::to_value(&d." + rustFieldName + ")?)"
	}
	// Wrapper types
	if isWellKnownWrapper(field) {
		return "d." + rustFieldName + ".clone()"
	}
	// Nested messages: wrap in Json
	if field.Desc.Kind() == protoreflect.MessageKind {
		if needsBox {
			return "d." + rustFieldName + ".as_ref().map(|v| Box::new((**v).clone()))"
		}
		return "d." + rustFieldName + ".as_ref().map(|v| sqlx::types::Json(v.clone()))"
	}
	// Enums
	if field.Desc.Kind() == protoreflect.EnumKind {
		if isEnumAsString(field, opts) {
			if field.Desc.HasOptionalKeyword() {
				return "d." + rustFieldName + ".as_ref().map(|e| e.to_string())"
			}
			return "d." + rustFieldName + ".to_string()"
		}
		if field.Desc.HasOptionalKeyword() {
			return "d." + rustFieldName + ".map(|e| e as i32)"
		}
		return "d." + rustFieldName + " as i32"
	}
	// Scalars
	return "d." + rustFieldName + ".clone()"
}
