package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateRust generates Rust output files for a proto file.
func generateRust(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	// Generate domain types if requested.
	if opts.Domain {
		if err := generateRustDomain(gen, file, opts); err != nil {
			return err
		}
	}

	// Generate storage types if a backend is specified.
	if opts.Backend != "" {
		switch opts.Backend {
		case "sqlite":
			return generateRustSqlite(gen, file, opts)
		default:
			return fmt.Errorf("proto2type: unsupported Rust backend %q (supported: sqlite)", opts.Backend)
		}
	}

	return nil
}

// generateRustDomain generates a Rust domain type file for a proto file.
func generateRustDomain(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	filename := outputFilename(file.GeneratedFilenamePrefix, ".type.rs")

	g := gen.NewGeneratedFile(filename, "")

	// Header
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// proto2type v", Version)
	g.P("// source: ", file.Desc.Path())
	g.P()

	// Scan for what use statements are needed
	needsChrono := false
	needsHashMap := false
	needsSerde := false
	needsSerdeJSON := false

	for _, msg := range file.Messages {
		if isMessageSkipped(msg) {
			continue
		}
		needsSerde = true
		scanRustImports(msg, &needsChrono, &needsHashMap, &needsSerdeJSON)
	}

	// Check if file has enums (need serde for oneof enums too)
	if len(file.Enums) > 0 {
		needsSerde = true
	}

	// Check for oneofs that would need serde
	for _, msg := range file.Messages {
		if isMessageSkipped(msg) {
			continue
		}
		if hasOneofFields(msg) {
			needsSerde = true
		}
	}

	// Emit use statements
	if needsSerde {
		g.P("use serde::{Deserialize, Serialize};")
	}
	if needsChrono {
		g.P("use chrono::{DateTime, Utc};")
	}
	if needsHashMap {
		g.P("use std::collections::HashMap;")
	}
	g.P()

	// Generate top-level enums
	for _, enum := range file.Enums {
		generateRustEnum(g, enum, "")
	}

	for _, msg := range file.Messages {
		if err := generateRustDomainMessage(g, msg, opts); err != nil {
			return err
		}
	}

	return nil
}

// scanRustImports scans a message (and its nested messages) for types that require imports.
func scanRustImports(msg *protogen.Message, needsChrono, needsHashMap, needsSerdeJSON *bool) {
	if isMessageSkipped(msg) {
		return
	}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}
		if isFieldSkipped(field) {
			continue
		}
		if isWellKnownTimestamp(field) {
			*needsChrono = true
		}
		if field.Desc.IsMap() {
			*needsHashMap = true
		}
		if isWellKnownStruct(field) || isWellKnownValue(field) || isWellKnownListValue(field) || isWellKnownAny(field) {
			*needsSerdeJSON = true
		}
	}
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		scanRustImports(nested, needsChrono, needsHashMap, needsSerdeJSON)
	}
}

// hasOneofFields returns true if the message has real (non-synthetic) oneof groups.
func hasOneofFields(msg *protogen.Message) bool {
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			return true
		}
	}
	return false
}

// generateRustEnum generates a Rust enum type for a proto enum.
// parentName is the parent message name (empty for top-level enums).
func generateRustEnum(g *protogen.GeneratedFile, enum *protogen.Enum, parentName string) {
	enumName := toPascalCase(string(enum.Desc.Name()))
	if parentName != "" {
		enumName = parentName + enumName
	}

	// Doc comment
	if enum.Comments.Leading != "" {
		for _, line := range strings.Split(strings.TrimSpace(string(enum.Comments.Leading)), "\n") {
			g.P("/// ", strings.TrimPrefix(line, " "))
		}
	}

	g.P("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]")
	g.P("#[repr(i32)]")
	g.P("pub enum ", enumName, " {")

	for i, val := range enum.Values {
		valName := stripEnumPrefix(enumName, string(val.Desc.Name()))
		valNum := val.Desc.Number()

		if val.Comments.Leading != "" {
			for _, line := range strings.Split(strings.TrimSpace(string(val.Comments.Leading)), "\n") {
				g.P("    /// ", strings.TrimPrefix(line, " "))
			}
		}

		// First value (index 0, number 0) gets #[default]
		if i == 0 && valNum == 0 {
			g.P("    #[default]")
		}
		g.P("    ", valName, " = ", valNum, ",")
	}

	g.P("}")
	g.P()

	// from_i32 impl
	g.P("impl ", enumName, " {")
	g.P("    pub fn from_i32(value: i32) -> Option<Self> {")
	g.P("        match value {")
	for _, val := range enum.Values {
		valName := stripEnumPrefix(enumName, string(val.Desc.Name()))
		g.P("            ", val.Desc.Number(), " => Some(Self::", valName, "),")
	}
	g.P("            _ => None,")
	g.P("        }")
	g.P("    }")
	g.P("}")
	g.P()

	// Display impl
	g.P("impl std::fmt::Display for ", enumName, " {")
	g.P("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {")
	g.P("        match self {")
	for _, val := range enum.Values {
		valName := stripEnumPrefix(enumName, string(val.Desc.Name()))
		// Display the original proto value name in UPPER_SNAKE
		g.P("            Self::", valName, " => write!(f, \"", string(val.Desc.Name()), "\"),")
	}
	g.P("        }")
	g.P("    }")
	g.P("}")
	g.P()
}

// generateRustOneofEnum generates a Rust enum for a oneof group.
func generateRustOneofEnum(g *protogen.GeneratedFile, msg *protogen.Message, oneof *protogen.Oneof, opts *Options) {
	msgName := rustMessageName(msg)
	oneofName := toPascalCase(string(oneof.Desc.Name()))
	enumName := msgName + oneofName

	g.P("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]")
	g.P(`#[serde(tag = "kind", content = "value")]`)
	g.P("pub enum ", enumName, " {")

	for _, field := range oneof.Fields {
		variantName := toPascalCase(string(field.Desc.Name()))
		variantType := rustOneofVariantType(field, opts)
		protoName := string(field.Desc.Name())
		g.P("    #[serde(rename = \"", protoName, "\")]")
		g.P("    ", variantName, "(", variantType, "),")
	}

	g.P("}")
	g.P()
}

// rustOneofVariantType returns the Rust type for a oneof variant field.
func rustOneofVariantType(field *protogen.Field, opts *Options) string {
	if isWellKnownTimestamp(field) {
		return "DateTime<Utc>"
	}
	if isWellKnownDuration(field) {
		return "i64"
	}
	if isWellKnownWrapper(field) {
		return rustWrapperType(field)
	}
	if isWellKnownStruct(field) {
		return "serde_json::Map<String, serde_json::Value>"
	}
	if isWellKnownValue(field) {
		return "serde_json::Value"
	}
	if isWellKnownListValue(field) {
		return "Vec<serde_json::Value>"
	}
	if isWellKnownFieldMask(field) {
		return "Vec<String>"
	}
	if isWellKnownEmpty(field) {
		return "()"
	}
	if field.Desc.Kind() == protoreflect.MessageKind {
		return "Box<" + rustMessageName(field.Message) + ">"
	}
	if field.Desc.Kind() == protoreflect.EnumKind {
		if isEnumAsString(field, opts) {
			return "String"
		}
		return rustEnumTypeName(field)
	}
	return rustType(field.Desc.Kind())
}

// generateRustDomainMessage generates a Rust domain struct for a single message.
func generateRustDomainMessage(g *protogen.GeneratedFile, msg *protogen.Message, opts *Options) error {
	if isMessageSkipped(msg) {
		return nil
	}

	name := rustMessageName(msg)

	// Generate nested enums first
	for _, enum := range msg.Enums {
		generateRustEnum(g, enum, name)
	}

	// Generate oneof enums before the struct
	seenOneofs := map[string]bool{}
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !seenOneofs[oneofName] {
				seenOneofs[oneofName] = true
				generateRustOneofEnum(g, msg, field.Oneof, opts)
			}
		}
	}

	// Doc comment
	g.P("/// Domain representation of ", msg.Desc.FullName(), ".")
	if msg.Comments.Leading != "" {
		g.P("///")
		for _, line := range strings.Split(strings.TrimSpace(string(msg.Comments.Leading)), "\n") {
			g.P("/// ", strings.TrimPrefix(line, " "))
		}
	}

	// Derive attributes
	g.P("#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]")
	g.P("#[non_exhaustive]")
	g.P("pub struct ", name, " {")

	// Track oneofs we've already emitted as fields
	emittedOneofs := map[string]bool{}

	for _, field := range msg.Fields {
		// Handle oneof fields: emit a single Option<EnumName> field per oneof group
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			oneofName := string(field.Oneof.Desc.Name())
			if !emittedOneofs[oneofName] {
				emittedOneofs[oneofName] = true

				oneofTypeName := name + toPascalCase(oneofName)
				rustFieldName := escapeRustKeyword(toSnakeCase(oneofName))

				g.P("    #[serde(default, skip_serializing_if = \"Option::is_none\")]")
				g.P("    pub ", rustFieldName, ": Option<", oneofTypeName, ">,")
			}
			continue
		}
		if isFieldSkipped(field) {
			continue
		}

		protoName := string(field.Desc.Name())
		rustFieldName := escapeRustKeyword(toSnakeCase(protoName))
		fieldType := rustDomainFieldType(field, opts)

		// P1-13: Honor (proto2type.field).name option via serde rename.
		// TODO: server_timestamp and inline options need design thought for Rust.
		nameOverride := fieldNameOverride(field)

		// Serde attributes
		attrs := []string{}

		// #[serde(rename = "...")] for name overrides (P1-13)
		if nameOverride != "" {
			attrs = append(attrs, fmt.Sprintf(`rename = "%s"`, nameOverride))
		} else if rustFieldName != protoName {
			// Fallback: rename if snake_case differs from proto name
			attrs = append(attrs, fmt.Sprintf(`rename = "%s"`, protoName))
		}

		// #[serde(default, skip_serializing_if = "Option::is_none")] for Option fields (P1-8)
		if strings.HasPrefix(fieldType, "Option<") {
			attrs = append(attrs, `default`)
			attrs = append(attrs, `skip_serializing_if = "Option::is_none"`)
		}

		// #[serde(default)] for fields that should have default values
		if shouldSerdeDefault(field) {
			attrs = append(attrs, `default`)
		}

		if len(attrs) > 0 {
			g.P("    #[serde(", strings.Join(attrs, ", "), ")]")
		}

		// P0-1: Duration doc comment
		if isWellKnownDuration(field) {
			g.P("    /// Duration in milliseconds")
		}

		g.P("    pub ", rustFieldName, ": ", fieldType, ",")
	}

	g.P("}")
	g.P()

	// Generate nested messages
	for _, nested := range msg.Messages {
		// Skip map entry messages
		if nested.Desc.IsMapEntry() {
			continue
		}
		if err := generateRustDomainMessage(g, nested, opts); err != nil {
			return err
		}
	}

	return nil
}

// shouldSerdeDefault returns true if the field should have #[serde(default)].
func shouldSerdeDefault(field *protogen.Field) bool {
	// Vec and HashMap fields benefit from default
	if field.Desc.IsList() || field.Desc.IsMap() {
		return true
	}
	return false
}
