package generator

import (
	"fmt"
	"path"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateTypeScript generates TypeScript/Zod output for a proto file.
func generateTypeScript(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	if opts.Backend != "" {
		return fmt.Errorf("proto2type: TypeScript does not support backend %q", opts.Backend)
	}
	if !opts.Domain {
		return nil
	}
	return generateTypeScriptDomain(gen, file, opts)
}

// generateTypeScriptDomain generates TypeScript/Zod output for a proto file.
func generateTypeScriptDomain(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	// NOTE: Cross-file imports are not yet supported. This is an existing
	// architectural limitation shared with Python and Kotlin backends. External
	// types referenced in message fields or oneof variants will compile only
	// when all generated files are in the same module scope.
	ir := BuildDomainFile(file, opts)
	ir.Messages = flattenMessages(ir.Messages)
	ir.Messages = topologicalSortMessages(ir.Messages)

	outFile := tsOutputFilename(file.Desc.Path(), opts)
	g := gen.NewGeneratedFile(outFile, "")

	writeTSFile(g, ir, opts)
	return nil
}

func writeTSFile(g *protogen.GeneratedFile, ir *DomainFile, opts *Options) {
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", ir.SourcePath)
	g.P("/* eslint-disable */")

	hasRegex := false
	for _, m := range ir.Messages {
		for _, f := range m.Fields {
			if f.ValidateConstraints != nil && f.ValidateConstraints.Pattern != "" {
				hasRegex = true
				break
			}
		}
	}

	if opts.TSInt64Style == "bigint" {
		g.P("// ⚠️  NOTE: BigInt values cannot be serialized with JSON.stringify() without a custom replacer.")
		g.P("// See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#use_within_json")
	}
	if hasRegex {
		g.P("// ⚠️  SECURITY: Regex patterns from buf.validate are designed for RE2 (non-backtracking).")
		g.P("// This generated code uses JavaScript's RegExp (backtracking). Review patterns for ReDoS.")
	}

	zodImport := "zod"
	if opts.TSZodImport != "" {
		zodImport = opts.TSZodImport
	}
	g.P(fmt.Sprintf(`import { z } from %s;`, strconv.Quote(zodImport)))

	// Cross-file imports: collect external type references and emit ESM imports.
	imports := collectTSImports(ir)
	for _, imp := range imports {
		g.P(fmt.Sprintf(`import { %s } from %s;`, strings.Join(imp.names, ", "), strconv.Quote(imp.path)))
	}
	g.P()

	// Enums.
	for _, e := range ir.Enums {
		writeTSEnum(g, e, opts)
		g.P()
	}

	// Messages (flattened and topologically sorted; nested enums emitted inline).
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		// Write nested enums before the message itself.
		for _, ne := range m.NestedEnums {
			writeTSEnum(g, ne, opts)
			g.P()
		}
		writeTSMessage(g, m, opts)
		g.P()
	}
}

func writeTSEnum(g *protogen.GeneratedFile, e *DomainEnum, opts *Options) {
	if e.Comment != "" {
		g.P("/** ", sanitizeJSDoc(e.Comment), " */")
	}

	if opts.TSEnumStyle == "native" {
		// Native enum: const object + z.nativeEnum.
		g.P("export const ", e.Name, " = {")
		for _, v := range e.Values {
			g.P(fmt.Sprintf("  %s: %q,", tsSafeKey(v.Name), v.Name))
		}
		g.P("} as const;")
		g.P("export const ", e.Name, "Schema = z.nativeEnum(", e.Name, ");")
		g.P("export type ", e.Name, " = z.infer<typeof ", e.Name, "Schema>;")
	} else {
		// Default: z.enum.
		vals := make([]string, 0, len(e.Values))
		for _, v := range e.Values {
			vals = append(vals, fmt.Sprintf(`"%s"`, v.Name))
		}
		if opts.TSExplicitTypes {
			g.P("export type ", e.Name, " = ", strings.Join(vals, " | "), " | (string & {});")
			g.P("export const ", e.Name, "Schema: z.ZodType<", e.Name, "> = z.enum([", strings.Join(vals, ", "), "]).or(z.string());")
		} else {
			g.P("export const ", e.Name, "Schema = z.enum([", strings.Join(vals, ", "), "]).or(z.string());")
			g.P("export type ", e.Name, " = z.infer<typeof ", e.Name, "Schema>;")
		}
	}
}

// isRecursive returns true when any field in the message requires boxing,
// indicating a recursive type cycle.
func isRecursive(m *DomainMessage) bool {
	for _, f := range m.Fields {
		if f.NeedsBox {
			return true
		}
	}
	for _, o := range m.Oneofs {
		for _, v := range o.Variants {
			if v.NeedsBox {
				return true
			}
		}
	}
	return false
}

func writeTSMessage(g *protogen.GeneratedFile, m *DomainMessage, opts *Options) {
	if m.Comment != "" {
		g.P("/** ", sanitizeJSDoc(m.Comment), " */")
	}

	recursive := isRecursive(m)

	// Determine which oneofs need exclusivity refinement (2+ variants).
	var exclusiveOneofs []*DomainOneof
	for _, o := range m.Oneofs {
		if len(o.Variants) >= 2 {
			exclusiveOneofs = append(exclusiveOneofs, o)
		}
	}

	if recursive {
		// For recursive types: emit a manual type alias first, then use z.lazy().
		g.P("export type ", m.Name, " = {")
		for _, f := range m.Fields {
			if f.FieldSkip {
				continue
			}
			optMark := ""
			if tsFieldNeedsOptional(f, opts) {
				optMark = "?"
			}
			g.P(fmt.Sprintf("  %s%s: %s;", f.CamelName, optMark, tsPlainType(f, opts)))
		}
		// Oneof variants in the type alias.
		for _, o := range m.Oneofs {
			for _, v := range o.Variants {
				tsType := tsPlainOneofVariantType(v, opts)
				g.P(fmt.Sprintf("  %s?: %s;", toCamelCase(v.ProtoName), tsType))
			}
		}
		g.P("};")
		g.P("export const ", m.Name, "Schema: z.ZodType<", m.Name, "> = z.lazy(() => z.object({")
	} else {
		if opts.TSExplicitTypes {
			writeTSExplicitInterface(g, m, opts)
			g.P("export const ", m.Name, "Schema: z.ZodType<", m.Name, "> = z.object({")
		} else {
			g.P("export const ", m.Name, "Schema = z.object({")
		}
	}

	// Emit regular fields.
	for _, f := range m.Fields {
		if f.FieldSkip || f.IsOneof {
			continue
		}
		zodExpr := tsFieldZodExpr(f, opts)
		g.P(fmt.Sprintf("  %s: %s,", tsSafeKey(f.CamelName), zodExpr))
	}

	// Oneof variants: emit each as an optional field.
	for _, o := range m.Oneofs {
		for _, v := range o.Variants {
			baseType := tsOneofVariantZodType(v, opts)
			if opts.ValidateEnabled() {
				baseType += tsOneofVariantZodConstraints(v, opts)
			}
			zodExpr := baseType + ".optional()"
			g.P(fmt.Sprintf("  %s: %s,", toCamelCase(v.ProtoName), zodExpr))
		}
	}

	if recursive {
		if len(exclusiveOneofs) > 0 {
			// Chain .superRefine() inside the z.lazy() thunk.
			g.P("}).superRefine((data, ctx) => {")
			emitOneofExclusivity(g, exclusiveOneofs)
			g.P("}));")
		} else {
			g.P("}));")
		}
	} else if len(exclusiveOneofs) > 0 {
		// Chain .superRefine() to enforce mutual exclusion of oneof variants.
		g.P("}).superRefine((data, ctx) => {")
		emitOneofExclusivity(g, exclusiveOneofs)
		g.P("});")
	} else {
		g.P("});")
	}

	if !recursive && !opts.TSExplicitTypes {
		g.P("export type ", m.Name, " = z.infer<typeof ", m.Name, "Schema>;")
	}
}

func emitOneofExclusivity(g *protogen.GeneratedFile, exclusiveOneofs []*DomainOneof) {
	for _, o := range exclusiveOneofs {
		varKeys := make([]string, 0, len(o.Variants))
		for _, v := range o.Variants {
			varKeys = append(varKeys, toCamelCase(v.ProtoName))
		}
		localVar := toCamelCase(o.FieldName)
		g.P(fmt.Sprintf("  const %sKeys = [%s] as const;",
			localVar, tsJoinQuoted(varKeys)))
		g.P(fmt.Sprintf("  const %sCount = %sKeys.filter(k => (data as Record<string, unknown>)[k] !== undefined).length;",
			localVar, localVar))
		g.P(fmt.Sprintf("  if (%sCount > 1) {", localVar))
		g.P("    ctx.addIssue({")
		g.P("      code: z.ZodIssueCode.custom,")
		g.P(fmt.Sprintf(`      message: "oneof %s: at most one of " + %sKeys.join(", ") + " may be set",`,
			o.FieldName, localVar))
		g.P("      path: [],")
		g.P("    });")
		g.P("  }")
	}
}

// tsFieldZodExpr builds the complete Zod expression for a field,
// including base type, validation constraints, container wrapping, and optionality.
func tsFieldZodExpr(f *DomainField, opts *Options) string {
	baseType := tsZodType(f, opts)

	hasNullable := false
	if strings.HasSuffix(baseType, ".nullable()") {
		baseType = strings.TrimSuffix(baseType, ".nullable()")
		hasNullable = true
	}

	// Apply validation constraints to the base type.
	if opts.ValidateEnabled() {
		baseType += tsZodConstraints(f, opts)
	}

	if hasNullable {
		baseType += ".nullable()"
	}

	zodExpr := baseType

	if f.IsMap {
		// Map field: z.record(key, value).default({})
		valType := tsMapValueZodType(f.MapValue, opts)
		zodExpr = fmt.Sprintf("z.record(z.string().refine(k => k !== '__proto__'), %s)", valType)
		// Map size constraints
		if opts.ValidateEnabled() && f.ValidateConstraints != nil {
			if f.ValidateConstraints.MinItems != nil {
				zodExpr += fmt.Sprintf(".refine(v => Object.keys(v).length >= %d, { message: 'Map must have at least %d entries' })", *f.ValidateConstraints.MinItems, *f.ValidateConstraints.MinItems)
			}
			if f.ValidateConstraints.MaxItems != nil {
				zodExpr += fmt.Sprintf(".refine(v => Object.keys(v).length <= %d, { message: 'Map must have at most %d entries' })", *f.ValidateConstraints.MaxItems, *f.ValidateConstraints.MaxItems)
			}
		}
		zodExpr += ".default(() => ({}))"
	} else if f.Repeated {
		// Repeated field: z.array(base).default([])
		zodExpr = fmt.Sprintf("z.array(%s)", baseType)
		// Apply array-level constraints (min/max items).
		if opts.ValidateEnabled() && f.ValidateConstraints != nil {
			if f.ValidateConstraints.MinItems != nil {
				zodExpr += fmt.Sprintf(".min(%d)", *f.ValidateConstraints.MinItems)
			}
			if f.ValidateConstraints.MaxItems != nil {
				zodExpr += fmt.Sprintf(".max(%d)", *f.ValidateConstraints.MaxItems)
			}
		}
		zodExpr += ".default(() => [])"
	} else {
		// Singular field: add .optional() if needed.
		if tsFieldNeedsOptional(f, opts) {
			zodExpr += ".optional()"
		} else if f.Kind == FieldKindScalar && !tsFieldIsRequired(f, opts) {
			zodExpr += ".default(" + tsScalarDefault(f.ScalarKind, opts) + ")"
		}
	}

	return zodExpr
}

// tsFieldNeedsOptional returns true when a singular field should be optional.
func tsFieldNeedsOptional(f *DomainField, opts *Options) bool {
	// Repeated and map fields use .default([]) / .default({}) instead.
	if f.Repeated || f.IsMap {
		return false
	}
	// Required fields (buf.validate) are never optional.
	if opts.ValidateEnabled() && f.ValidateConstraints != nil && f.ValidateConstraints.Required {
		return false
	}
	// All message-based types (messages, WKTs, wrappers) are optional in proto3.
	isMessageLike := f.Kind == FieldKindMessage || f.Kind == FieldKindTimestamp ||
		f.Kind == FieldKindDuration || f.Kind == FieldKindStruct ||
		f.Kind == FieldKindValue || f.Kind == FieldKindListValue ||
		f.Kind == FieldKindFieldMask || f.Kind == FieldKindEmpty ||
		f.Kind == FieldKindAny || f.Kind.IsWrapper()
	return isMessageLike || f.Optional || f.IsOneof || f.Kind == FieldKindEnum
}

func tsFieldIsRequired(f *DomainField, opts *Options) bool {
	return opts.ValidateEnabled() && f.ValidateConstraints != nil && f.ValidateConstraints.Required
}

// writeTSExplicitInterface emits a plain TypeScript interface alongside the Zod schema.
// This can improve IDE performance compared to z.infer in large codebases.
func writeTSExplicitInterface(g *protogen.GeneratedFile, m *DomainMessage, opts *Options) {
	g.P("export interface ", m.Name, " {")
	for _, f := range m.Fields {
		if f.FieldSkip || f.IsOneof {
			continue
		}
		tsType := tsPlainType(f, opts)
		optMark := ""
		if tsFieldNeedsOptional(f, opts) {
			optMark = "?"
		}
		g.P(fmt.Sprintf("  %s%s: %s;", f.CamelName, optMark, tsType))
	}
	for _, o := range m.Oneofs {
		if len(o.Variants) >= 2 {
			varNames := make([]string, 0, len(o.Variants))
			for _, v := range o.Variants {
				varNames = append(varNames, toCamelCase(v.ProtoName))
			}
			g.P(fmt.Sprintf("  /** @oneof %s — at most one of: %s */",
				o.FieldName, strings.Join(varNames, ", ")))
		}
		for _, v := range o.Variants {
			tsType := tsPlainOneofVariantType(v, opts)
			g.P(fmt.Sprintf("  %s?: %s;", toCamelCase(v.ProtoName), tsType))
		}
	}
	g.P("}")
}

// tsPlainType returns the plain TypeScript type for a field (used in explicit interfaces).
func tsPlainType(f *DomainField, opts *Options) string {
	base := tsPlainBaseType(f, opts)

	if f.IsMap {
		valType := "unknown"
		if f.MapValue != nil {
			valType = tsPlainBaseTypeFromMapInfo(f.MapValue, opts)
		}
		return fmt.Sprintf("Record<string, %s>", valType)
	}
	if f.Repeated {
		return base + "[]"
	}
	return base
}

// tsPlainBaseType returns the plain TS type for a field's base type.
func tsPlainBaseType(f *DomainField, opts *Options) string {
	switch {
	case f.Kind == FieldKindScalar:
		return tsPlainScalarType(f.ScalarKind, opts)
	case f.Kind == FieldKindEnum:
		return f.EnumTypeName
	case f.Kind == FieldKindMessage:
		return f.MessageTypeName
	case f.Kind == FieldKindTimestamp:
		return "string"
	case f.Kind == FieldKindDuration:
		return "string"
	case f.Kind.IsWrapper():
		return tsPlainWrapperType(f.Kind, opts) + " | null"
	case f.Kind == FieldKindStruct:
		return "Record<string, unknown>"
	case f.Kind == FieldKindValue:
		return "unknown"
	case f.Kind == FieldKindListValue:
		return "unknown[]"
	case f.Kind == FieldKindFieldMask:
		return "string[]"
	case f.Kind == FieldKindEmpty:
		return "Record<string, never>"
	case f.Kind == FieldKindAny:
		return "unknown"
	default:
		return "unknown"
	}
}

func tsPlainScalarType(k protoreflect.Kind, opts *Options) string {
	switch k {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind,
		protoreflect.FloatKind, protoreflect.DoubleKind:
		return "number"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		if opts.TSInt64Style == "bigint" {
			return "bigint"
		}
		return "string"
	case protoreflect.StringKind, protoreflect.BytesKind:
		return "string"
	default:
		return "unknown"
	}
}

func tsPlainWrapperType(k FieldKind, opts *Options) string {
	switch k {
	case FieldKindWrapperBool:
		return "boolean"
	case FieldKindWrapperInt32, FieldKindWrapperUInt32,
		FieldKindWrapperFloat, FieldKindWrapperDouble:
		return "number"
	case FieldKindWrapperInt64, FieldKindWrapperUInt64:
		if opts.TSInt64Style == "bigint" {
			return "bigint"
		}
		return "string"
	case FieldKindWrapperString, FieldKindWrapperBytes:
		return "string"
	default:
		return "unknown"
	}
}

func tsPlainBaseTypeFromMapInfo(info *MapTypeInfo, opts *Options) string {
	if info == nil {
		return "unknown"
	}
	switch info.Kind {
	case FieldKindTimestamp, FieldKindDuration:
		return "string"
	case FieldKindStruct:
		return "Record<string, unknown>"
	case FieldKindValue:
		return "unknown"
	case FieldKindListValue:
		return "unknown[]"
	case FieldKindFieldMask:
		return "string[]"
	case FieldKindEmpty:
		return "Record<string, never>"
	case FieldKindAny:
		return "unknown"
	}
	if info.Kind.IsWrapper() {
		return tsPlainWrapperType(info.Kind, opts) + " | null"
	}
	switch info.Kind {
	case FieldKindScalar:
		return tsPlainScalarType(info.ScalarKind, opts)
	case FieldKindEnum:
		return info.EnumTypeName
	case FieldKindMessage:
		return info.MessageTypeName
	default:
		return "unknown"
	}
}

// sanitizeJSDoc escapes JSDoc closing tags in comments.
func sanitizeJSDoc(s string) string {
	return strings.ReplaceAll(s, "*/", "* /")
}

// tsSafeKey wraps dangerous keys in computed property syntax.
func tsSafeKey(name string) string {
	if name == "__proto__" || name == "constructor" || name == "prototype" {
		return fmt.Sprintf("[%q]", name)
	}
	return name
}

// tsJoinQuoted returns a comma-separated list of double-quoted JS string literals.
// e.g. ["a", "b", "c"] → `"a", "b", "c"`.
func tsJoinQuoted(keys []string) string {
	quoted := make([]string, len(keys))
	for i, k := range keys {
		quoted[i] = strconv.Quote(k)
	}
	return strings.Join(quoted, ", ")
}

// tsScalarDefault returns the default value string for a scalar kind.
func tsScalarDefault(k protoreflect.Kind, opts *Options) string {
	switch k {
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind,
		protoreflect.FloatKind, protoreflect.DoubleKind:
		return "0"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		if opts.TSInt64Style == "bigint" {
			return "0n"
		}
		return `""`
	case protoreflect.StringKind:
		return `""`
	case protoreflect.BytesKind:
		return `""`
	default:
		return `""`
	}
}

// tsOneofVariantZodType returns the Zod type expression for a oneof variant.
func tsOneofVariantZodType(v *OneofVariant, opts *Options) string {
	switch v.Kind {
	case FieldKindScalar:
		return tsScalarZodType(v.ScalarKind, opts)
	case FieldKindMessage:
		if v.NeedsBox {
			return fmt.Sprintf("z.lazy(() => %sSchema)", v.TypeName)
		}
		return fmt.Sprintf("%sSchema", v.TypeName)
	case FieldKindEnum:
		if opts.TSEnumStyle == "native" {
			return fmt.Sprintf("z.nativeEnum(%s)", v.TypeName)
		}
		return fmt.Sprintf("%sSchema", v.TypeName)
	case FieldKindTimestamp:
		return "z.string().datetime({ offset: true })"
	case FieldKindDuration:
		return "z.string()"
	case FieldKindStruct:
		return "z.record(z.string(), z.unknown())"
	case FieldKindValue:
		return "z.unknown()"
	case FieldKindListValue:
		return "z.array(z.unknown())"
	case FieldKindFieldMask:
		return "z.array(z.string())"
	case FieldKindEmpty:
		return "z.record(z.string(), z.never())"
	case FieldKindAny:
		return "z.unknown()"
	default:
		if v.Kind.IsWrapper() {
			t, _ := tsWKTZodType(v.Kind, opts)
			return t
		}
		return "z.unknown()"
	}
}

// tsPlainOneofVariantType returns the plain TS type for a oneof variant.
func tsPlainOneofVariantType(v *OneofVariant, opts *Options) string {
	switch v.Kind {
	case FieldKindScalar:
		return tsPlainScalarType(v.ScalarKind, opts)
	case FieldKindMessage:
		return v.TypeName
	case FieldKindEnum:
		return v.TypeName
	case FieldKindTimestamp, FieldKindDuration:
		return "string"
	case FieldKindStruct:
		return "Record<string, unknown>"
	case FieldKindValue:
		return "unknown"
	case FieldKindListValue:
		return "unknown[]"
	case FieldKindFieldMask:
		return "string[]"
	case FieldKindEmpty:
		return "Record<string, never>"
	case FieldKindAny:
		return "unknown"
	default:
		if v.Kind.IsWrapper() {
			return tsPlainWrapperType(v.Kind, opts) + " | null"
		}
		return "unknown"
	}
}

// tsImportEntry represents a group of names to import from a single module.
type tsImportEntry struct {
	path  string   // relative ESM import path (e.g. "./other.type.js")
	names []string // sorted list of identifiers to import
}

// collectTSImports scans the IR for cross-file type references and returns
// grouped, deduplicated import entries sorted by path.
func collectTSImports(ir *DomainFile) []tsImportEntry {
	// Map from proto source path → set of type names needed.
	needed := make(map[string]map[string]bool)

	addRef := func(sourcePath, typeName string) {
		if sourcePath == "" || typeName == "" {
			return
		}
		if needed[sourcePath] == nil {
			needed[sourcePath] = make(map[string]bool)
		}
		needed[sourcePath][typeName+"Schema"] = true
		needed[sourcePath][typeName] = true
	}

	for _, m := range ir.Messages {
		for _, f := range m.Fields {
			if f.MessageSourcePath != "" {
				addRef(f.MessageSourcePath, f.MessageTypeName)
			}
			if f.EnumSourcePath != "" {
				addRef(f.EnumSourcePath, f.EnumTypeName)
			}
		}
		for _, o := range m.Oneofs {
			for _, v := range o.Variants {
				if v.SourcePath != "" {
					addRef(v.SourcePath, v.TypeName)
				}
			}
		}
	}

	if len(needed) == 0 {
		return nil
	}

	// Convert to sorted import entries.
	var entries []tsImportEntry
	for protoPath, nameSet := range needed {
		// Map proto path to relative .type.js import path.
		relPath := tsImportPath(ir.SourcePath, protoPath)
		var names []string
		for n := range nameSet {
			names = append(names, n)
		}
		sort.Strings(names)
		entries = append(entries, tsImportEntry{path: relPath, names: names})
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].path < entries[j].path
	})
	return entries
}

// tsImportPath computes the relative ESM import path from the current proto
// file to the referenced proto file, using .type.js extension.
func tsImportPath(fromProto, toProto string) string {
	fromDir := path.Dir(fromProto)
	// Strip .proto extension, add .type.js.
	toBase := strings.TrimSuffix(toProto, ".proto") + ".type.js"

	// Compute relative path using POSIX conventions (proto paths are always forward-slash).
	// Split both into components and find common prefix.
	fromParts := strings.Split(fromDir, "/")
	toParts := strings.Split(toBase, "/")

	if fromDir == "." {
		fromParts = nil
	}

	// Find common prefix length.
	common := 0
	for common < len(fromParts) && common < len(toParts) && fromParts[common] == toParts[common] {
		common++
	}

	// Build relative path: go up for remaining fromParts, then down for remaining toParts.
	var relParts []string
	for i := common; i < len(fromParts); i++ {
		relParts = append(relParts, "..")
	}
	relParts = append(relParts, toParts[common:]...)

	rel := strings.Join(relParts, "/")
	if !strings.HasPrefix(rel, ".") {
		rel = "./" + rel
	}
	return rel
}
