package generator

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// generateTypeScript generates TypeScript/Zod output for a proto file.
func generateTypeScript(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	if !opts.Domain {
		return nil
	}
	return generateTypeScriptDomain(gen, file, opts)
}

func generateTypeScriptDomain(gen *protogen.Plugin, file *protogen.File, opts *Options) error {
	ir := BuildDomainFile(file, opts)
	ir.Messages = flattenMessages(ir.Messages)
	ir.Messages = topologicalSortMessages(ir.Messages)

	outFile := tsOutputFilename(file.Desc.Path(), opts)
	g := gen.NewGeneratedFile(outFile, "")

	writeTSFile(g, ir, opts)
	return nil
}

func writeTSFile(g *protogen.GeneratedFile, ir *DomainFile, opts *Options) {
	g.P("// Code generated by proto2type. DO NOT EDIT.")
	g.P("// source: ", ir.SourcePath)
	g.P("/* eslint-disable */")

	zodImport := "zod"
	if opts.TSZodImport != "" {
		zodImport = opts.TSZodImport
	}
	g.P(fmt.Sprintf(`import { z } from "%s";`, zodImport))
	g.P()

	// Enums.
	for _, e := range ir.Enums {
		writeTSEnum(g, e, opts)
		g.P()
	}

	// Messages (flattened and topologically sorted; nested enums emitted inline).
	for _, m := range ir.Messages {
		if m.Skip {
			continue
		}
		// Write nested enums before the message itself.
		for _, ne := range m.NestedEnums {
			writeTSEnum(g, ne, opts)
			g.P()
		}
		writeTSMessage(g, m, opts)
		g.P()
	}
}

func writeTSEnum(g *protogen.GeneratedFile, e *DomainEnum, opts *Options) {
	if e.Comment != "" {
		g.P("/** ", e.Comment, " */")
	}

	if opts.TSEnumStyle == "native" {
		// Native enum: const object + z.nativeEnum.
		g.P("export const ", e.Name, " = {")
		for _, v := range e.Values {
			g.P(fmt.Sprintf(`  %s: "%s",`, v.Name, v.Name))
		}
		g.P("} as const;")
		g.P("export const ", e.Name, "Schema = z.nativeEnum(", e.Name, ");")
		g.P("export type ", e.Name, " = z.infer<typeof ", e.Name, "Schema>;")
	} else {
		// Default: z.enum.
		vals := make([]string, 0, len(e.Values))
		for _, v := range e.Values {
			vals = append(vals, fmt.Sprintf(`"%s"`, v.Name))
		}
		g.P("export const ", e.Name, "Schema = z.enum([", strings.Join(vals, ", "), "]);")
		g.P("export type ", e.Name, " = z.infer<typeof ", e.Name, "Schema>;")
	}
}

// isRecursive returns true when any field in the message requires boxing,
// indicating a recursive type cycle.
func isRecursive(m *DomainMessage) bool {
	for _, f := range m.Fields {
		if f.NeedsBox {
			return true
		}
	}
	return false
}

func writeTSMessage(g *protogen.GeneratedFile, m *DomainMessage, opts *Options) {
	if m.Comment != "" {
		g.P("/** ", m.Comment, " */")
	}

	recursive := isRecursive(m)

	if recursive {
		// For recursive types: emit a manual type alias first, then use z.lazy().
		g.P("export type ", m.Name, " = {")
		for _, f := range m.Fields {
			if f.FieldSkip {
				continue
			}
			optMark := ""
			if tsFieldNeedsOptional(f, opts) {
				optMark = "?"
			}
			// Use any for recursive field types; z.infer will resolve.
			g.P(fmt.Sprintf("  %s%s: any;", f.CamelName, optMark))
		}
		g.P("};")
		g.P("export const ", m.Name, "Schema: z.ZodType<", m.Name, "> = z.lazy(() => z.object({")
	} else {
		g.P("export const ", m.Name, "Schema = z.object({")
	}

	// Emit fields.
	for _, f := range m.Fields {
		if f.FieldSkip {
			continue
		}

		zodExpr := tsFieldZodExpr(f, opts)
		g.P(fmt.Sprintf("  %s: %s,", f.CamelName, zodExpr))
	}

	if recursive {
		g.P("}));")
	} else {
		g.P("});")
		g.P("export type ", m.Name, " = z.infer<typeof ", m.Name, "Schema>;")
	}

	// Emit explicit interface if requested and not recursive.
	if opts.TSExplicitTypes && !recursive {
		writeTSExplicitInterface(g, m, opts)
	}
}

// tsFieldZodExpr builds the complete Zod expression for a field,
// including base type, validation constraints, container wrapping, and optionality.
func tsFieldZodExpr(f *DomainField, opts *Options) string {
	baseType := tsZodType(f, opts)

	// Apply validation constraints to the base type.
	if opts.ValidateEnabled() {
		baseType += tsZodConstraints(f)
	}

	zodExpr := baseType

	if f.IsMap {
		// Map field: z.record(key, value).default({})
		valType := tsMapValueZodType(f.MapValue, opts)
		zodExpr = fmt.Sprintf("z.record(z.string(), %s)", valType)
		zodExpr += ".default({})"
	} else if f.Repeated {
		// Repeated field: z.array(base).default([])
		zodExpr = fmt.Sprintf("z.array(%s)", baseType)
		// Apply array-level constraints (min/max items).
		if opts.ValidateEnabled() && f.ValidateConstraints != nil {
			if f.ValidateConstraints.MinItems != nil {
				zodExpr += fmt.Sprintf(".min(%d)", *f.ValidateConstraints.MinItems)
			}
			if f.ValidateConstraints.MaxItems != nil {
				zodExpr += fmt.Sprintf(".max(%d)", *f.ValidateConstraints.MaxItems)
			}
		}
		zodExpr += ".default([])"
	} else {
		// Singular field: add .optional() if needed.
		if tsFieldNeedsOptional(f, opts) {
			zodExpr += ".optional()"
		}
	}

	return zodExpr
}

// tsFieldNeedsOptional returns true when a singular field should be optional.
func tsFieldNeedsOptional(f *DomainField, opts *Options) bool {
	// Repeated and map fields use .default([]) / .default({}) instead.
	if f.Repeated || f.IsMap {
		return false
	}
	// Required fields (buf.validate) are never optional.
	if opts.ValidateEnabled() && f.ValidateConstraints != nil && f.ValidateConstraints.Required {
		return false
	}
	// Message types, optional scalars, and oneof-collapsed fields are optional.
	return f.Kind == FieldKindMessage || f.Optional || f.IsOneof
}

// writeTSExplicitInterface emits a plain TypeScript interface alongside the Zod schema.
// This can improve IDE performance compared to z.infer in large codebases.
func writeTSExplicitInterface(g *protogen.GeneratedFile, m *DomainMessage, opts *Options) {
	g.P("export interface I", m.Name, " {")
	for _, f := range m.Fields {
		if f.FieldSkip {
			continue
		}
		tsType := tsPlainType(f, opts)
		optMark := ""
		if tsFieldNeedsOptional(f, opts) {
			optMark = "?"
		}
		g.P(fmt.Sprintf("  %s%s: %s;", f.CamelName, optMark, tsType))
	}
	g.P("}")
}

// tsPlainType returns the plain TypeScript type for a field (used in explicit interfaces).
func tsPlainType(f *DomainField, opts *Options) string {
	base := tsPlainBaseType(f, opts)

	if f.IsMap {
		valType := "unknown"
		if f.MapValue != nil {
			valType = tsPlainBaseTypeFromMapInfo(f.MapValue, opts)
		}
		return fmt.Sprintf("Record<string, %s>", valType)
	}
	if f.Repeated {
		return base + "[]"
	}
	return base
}

// tsPlainBaseType returns the plain TS type for a field's base type.
func tsPlainBaseType(f *DomainField, opts *Options) string {
	switch {
	case f.Kind == FieldKindScalar:
		return tsPlainScalarType(f.ScalarKind, opts)
	case f.Kind == FieldKindEnum:
		return f.EnumTypeName
	case f.Kind == FieldKindMessage:
		return f.MessageTypeName
	case f.Kind == FieldKindTimestamp:
		return "string"
	case f.Kind == FieldKindDuration:
		return "string"
	case f.Kind.IsWrapper():
		return tsPlainWrapperType(f.Kind, opts) + " | null"
	case f.Kind == FieldKindStruct:
		return "Record<string, unknown>"
	case f.Kind == FieldKindValue:
		return "unknown"
	case f.Kind == FieldKindListValue:
		return "unknown[]"
	case f.Kind == FieldKindFieldMask:
		return "string[]"
	case f.Kind == FieldKindEmpty:
		return "Record<string, never>"
	case f.Kind == FieldKindAny:
		return "unknown"
	default:
		return "unknown"
	}
}

func tsPlainScalarType(k protoreflect.Kind, opts *Options) string {
	switch k {
	case protoreflect.BoolKind:
		return "boolean"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Uint32Kind, protoreflect.Fixed32Kind,
		protoreflect.FloatKind, protoreflect.DoubleKind:
		return "number"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind,
		protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		if opts.TSInt64Style == "bigint" {
			return "bigint"
		}
		return "string"
	case protoreflect.StringKind, protoreflect.BytesKind:
		return "string"
	default:
		return "unknown"
	}
}

func tsPlainWrapperType(k FieldKind, opts *Options) string {
	switch k {
	case FieldKindWrapperBool:
		return "boolean"
	case FieldKindWrapperInt32, FieldKindWrapperUInt32,
		FieldKindWrapperFloat, FieldKindWrapperDouble:
		return "number"
	case FieldKindWrapperInt64, FieldKindWrapperUInt64:
		if opts.TSInt64Style == "bigint" {
			return "bigint"
		}
		return "string"
	case FieldKindWrapperString, FieldKindWrapperBytes:
		return "string"
	default:
		return "unknown"
	}
}

func tsPlainBaseTypeFromMapInfo(info *MapTypeInfo, opts *Options) string {
	switch info.Kind {
	case FieldKindScalar:
		return tsPlainScalarType(info.ScalarKind, opts)
	case FieldKindEnum:
		return info.EnumTypeName
	case FieldKindMessage:
		return info.MessageTypeName
	default:
		return "unknown"
	}
}
