// Code generated by proto2type. DO NOT EDIT.
// source: proto2type/options.proto

package proto2type

// MessageOptions is the domain representation of proto2type.MessageOptions.
type MessageOptions struct {
	Skip bool `json:"skip"`
}

// ToProto converts to the protobuf message.
func (d *MessageOptions) ToProto() *MessageOptions {
	if d == nil {
		return nil
	}
	pb := &MessageOptions{
		Skip: d.Skip,
	}
	return pb
}

// FromProto populates from a protobuf message.
func (d *MessageOptions) FromProto(pb *MessageOptions) {
	if pb == nil {
		return
	}
	d.Skip = pb.Skip
}

// ApplyFieldMaskMessageOptions copies fields from src to dst based on the given paths.
func ApplyFieldMaskMessageOptions(dst, src *MessageOptions, paths []string) {
	for _, path := range paths {
		switch path {
		case "skip":
			dst.Skip = src.Skip
		}
	}
}

// FieldOptions is the domain representation of proto2type.FieldOptions.
type FieldOptions struct {
	DocumentID      bool   `json:"document_id"`
	ServerTimestamp bool   `json:"server_timestamp"`
	Name            string `json:"name"`
	Skip            bool   `json:"skip"`
	Omitempty       int32  `json:"omitempty"`
	Inline          bool   `json:"inline"`
}

// ToProto converts to the protobuf message.
func (d *FieldOptions) ToProto() *FieldOptions {
	if d == nil {
		return nil
	}
	pb := &FieldOptions{
		DocumentId:      d.DocumentID,
		ServerTimestamp: d.ServerTimestamp,
		Name:            d.Name,
		Skip:            d.Skip,
		Omitempty:       d.Omitempty,
		Inline:          d.Inline,
	}
	return pb
}

// FromProto populates from a protobuf message.
func (d *FieldOptions) FromProto(pb *FieldOptions) {
	if pb == nil {
		return
	}
	d.DocumentID = pb.DocumentId
	d.ServerTimestamp = pb.ServerTimestamp
	d.Name = pb.Name
	d.Skip = pb.Skip
	d.Omitempty = pb.Omitempty
	d.Inline = pb.Inline
}

// ApplyFieldMaskFieldOptions copies fields from src to dst based on the given paths.
func ApplyFieldMaskFieldOptions(dst, src *FieldOptions, paths []string) {
	for _, path := range paths {
		switch path {
		case "document_id":
			dst.DocumentID = src.DocumentID
		case "server_timestamp":
			dst.ServerTimestamp = src.ServerTimestamp
		case "name":
			dst.Name = src.Name
		case "skip":
			dst.Skip = src.Skip
		case "omitempty":
			dst.Omitempty = src.Omitempty
		case "inline":
			dst.Inline = src.Inline
		}
	}
}
