// Code generated by proto2type. DO NOT EDIT.
// source: proto2type/options.proto
// backend: firestore

package proto2type

// MessageOptionsFirestore is the Firestore storage representation of proto2type.MessageOptions.
type MessageOptionsFirestore struct {
	Skip bool `firestore:"skip"`
}

// ToProto converts to the protobuf message.
func (d *MessageOptionsFirestore) ToProto() *MessageOptions {
	if d == nil {
		return nil
	}
	pb := &MessageOptions{
		Skip: d.Skip,
	}
	return pb
}

// FromProto populates from a protobuf message.
func (d *MessageOptionsFirestore) FromProto(pb *MessageOptions) {
	if pb == nil {
		return
	}
	d.Skip = pb.Skip
}

// ToDomain converts to the domain type.
func (s *MessageOptionsFirestore) ToDomain() *MessageOptions {
	if s == nil {
		return nil
	}
	d := &MessageOptions{
		Skip: s.Skip,
	}
	return d
}

// FromDomain populates from the domain type.
func (s *MessageOptionsFirestore) FromDomain(d *MessageOptions) {
	if d == nil {
		return
	}
	s.Skip = d.Skip
}

// FieldOptionsFirestore is the Firestore storage representation of proto2type.FieldOptions.
type FieldOptionsFirestore struct {
	DocumentID      bool   `firestore:"document_id"`
	ServerTimestamp bool   `firestore:"server_timestamp"`
	Name            string `firestore:"name"`
	Skip            bool   `firestore:"skip"`
	Omitempty       int32  `firestore:"omitempty"`
	Inline          bool   `firestore:"inline"`
}

// ToProto converts to the protobuf message.
func (d *FieldOptionsFirestore) ToProto() *FieldOptions {
	if d == nil {
		return nil
	}
	pb := &FieldOptions{
		DocumentId:      d.DocumentID,
		ServerTimestamp: d.ServerTimestamp,
		Name:            d.Name,
		Skip:            d.Skip,
		Omitempty:       d.Omitempty,
		Inline:          d.Inline,
	}
	return pb
}

// FromProto populates from a protobuf message.
func (d *FieldOptionsFirestore) FromProto(pb *FieldOptions) {
	if pb == nil {
		return
	}
	d.DocumentID = pb.DocumentId
	d.ServerTimestamp = pb.ServerTimestamp
	d.Name = pb.Name
	d.Skip = pb.Skip
	d.Omitempty = pb.Omitempty
	d.Inline = pb.Inline
}

// ToDomain converts to the domain type.
func (s *FieldOptionsFirestore) ToDomain() *FieldOptions {
	if s == nil {
		return nil
	}
	d := &FieldOptions{
		DocumentID:      s.DocumentID,
		ServerTimestamp: s.ServerTimestamp,
		Name:            s.Name,
		Skip:            s.Skip,
		Omitempty:       s.Omitempty,
		Inline:          s.Inline,
	}
	return d
}

// FromDomain populates from the domain type.
func (s *FieldOptionsFirestore) FromDomain(d *FieldOptions) {
	if d == nil {
		return
	}
	s.DocumentID = d.DocumentID
	s.ServerTimestamp = d.ServerTimestamp
	s.Name = d.Name
	s.Skip = d.Skip
	s.Omitempty = d.Omitempty
	s.Inline = d.Inline
}
