[package]
name = "proto2type-rust-integration"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.20", features = ["serde"] }
rusqlite = { version = "0.35", features = ["bundled"] }
validator = { version = "0.20", features = ["derive"] }
lazy_static = "1"
regex = "1"
