// Code generated by proto2type. DO NOT EDIT.
// source: fhir_patient.proto
// backend: postgres
// mode: search_index

package pb

import (
	"fmt"
	"strings"
	"time"

	proto "google.golang.org/protobuf/proto"
)

// SearchIndexes holds all extracted search parameter index rows for a resource.
type SearchIndexes struct {
	Tokens     []SpidxToken
	Strings    []SpidxString
	Dates      []SpidxDate
	Quantities []SpidxQuantity
	References []SpidxReference
	URIs       []SpidxURI
}

// SpidxToken represents a row in the spidx_token table.
type SpidxToken struct {
	TenantID string `db:"tenant_id"`
	ResType  string `db:"res_type"`
	ResID    string `db:"res_id"`
	SpName   string `db:"sp_name"`
	SpSystem string `db:"sp_system"`
	SpValue  string `db:"sp_value"`
}

// SpidxString represents a row in the spidx_string table.
type SpidxString struct {
	TenantID string `db:"tenant_id"`
	ResType  string `db:"res_type"`
	ResID    string `db:"res_id"`
	SpName   string `db:"sp_name"`
	SpValue  string `db:"sp_value"`
}

// SpidxDate represents a row in the spidx_date table.
type SpidxDate struct {
	TenantID string    `db:"tenant_id"`
	ResType  string    `db:"res_type"`
	ResID    string    `db:"res_id"`
	SpName   string    `db:"sp_name"`
	SpLow    time.Time `db:"sp_low"`
	SpHigh   time.Time `db:"sp_high"`
}

// SpidxQuantity represents a row in the spidx_quantity table.
type SpidxQuantity struct {
	TenantID string  `db:"tenant_id"`
	ResType  string  `db:"res_type"`
	ResID    string  `db:"res_id"`
	SpName   string  `db:"sp_name"`
	SpSystem string  `db:"sp_system"`
	SpCode   string  `db:"sp_code"`
	SpValue  float64 `db:"sp_value"`
}

// SpidxReference represents a row in the spidx_reference table.
type SpidxReference struct {
	TenantID   string `db:"tenant_id"`
	ResType    string `db:"res_type"`
	ResID      string `db:"res_id"`
	SpName     string `db:"sp_name"`
	TargetType string `db:"target_type"`
	TargetID   string `db:"target_id"`
}

// SpidxURI represents a row in the spidx_uri table.
type SpidxURI struct {
	TenantID string `db:"tenant_id"`
	ResType  string `db:"res_type"`
	ResID    string `db:"res_id"`
	SpName   string `db:"sp_name"`
	SpValue  string `db:"sp_value"`
}

var (
	_ = strings.ToLower
	_ = time.Now
	_ = proto.Marshal
	_ = fmt.Sprintf
)

// ExtractStringIndexes extracts HAPI-style search index rows from a String proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractStringIndexes(tenantID string, r *String) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractIdIndexes extracts HAPI-style search index rows from a Id proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractIdIndexes(tenantID string, r *Id) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractBooleanIndexes extracts HAPI-style search index rows from a Boolean proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractBooleanIndexes(tenantID string, r *Boolean) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractDateIndexes extracts HAPI-style search index rows from a Date proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractDateIndexes(tenantID string, r *Date) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractDateTimeIndexes extracts HAPI-style search index rows from a DateTime proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractDateTimeIndexes(tenantID string, r *DateTime) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractCodeIndexes extracts HAPI-style search index rows from a Code proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractCodeIndexes(tenantID string, r *Code) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractUriIndexes extracts HAPI-style search index rows from a Uri proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractUriIndexes(tenantID string, r *Uri) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractCodingIndexes extracts HAPI-style search index rows from a Coding proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractCodingIndexes(tenantID string, r *Coding) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractCodeableConceptIndexes extracts HAPI-style search index rows from a CodeableConcept proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractCodeableConceptIndexes(tenantID string, r *CodeableConcept) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractIdentifierIndexes extracts HAPI-style search index rows from a Identifier proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractIdentifierIndexes(tenantID string, r *Identifier) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractReferenceIndexes extracts HAPI-style search index rows from a Reference proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractReferenceIndexes(tenantID string, r *Reference) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractHumanNameIndexes extracts HAPI-style search index rows from a HumanName proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractHumanNameIndexes(tenantID string, r *HumanName) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractAddressIndexes extracts HAPI-style search index rows from a Address proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractAddressIndexes(tenantID string, r *Address) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractContactPointIndexes extracts HAPI-style search index rows from a ContactPoint proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractContactPointIndexes(tenantID string, r *ContactPoint) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractPatientIndexes extracts HAPI-style search index rows from a Patient proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractPatientIndexes(tenantID string, r *Patient) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	// Extract resource ID
	if r.GetId() != nil {
		resID = r.GetId().GetValue()
	}

	// SearchParameter: family (string)
	// FHIRPath: Patient.name.family
	for _, outer := range r.GetName() {
		if outer == nil {
			continue
		}
		if v := outer.GetFamily(); v != nil && v.GetValue() != "" {
			idx.Strings = append(idx.Strings, SpidxString{
				TenantID: tenantID,
				ResType:  "Patient",
				ResID:    resID,
				SpName:   "family",
				SpValue:  strings.ToLower(v.GetValue()),
			})
		}
	}

	// SearchParameter: given (string)
	// FHIRPath: Patient.name.given
	for _, outer := range r.GetName() {
		if outer == nil {
			continue
		}
		for _, v := range outer.GetGiven() {
			if v != nil && v.GetValue() != "" {
				idx.Strings = append(idx.Strings, SpidxString{
					TenantID: tenantID,
					ResType:  "Patient",
					ResID:    resID,
					SpName:   "given",
					SpValue:  strings.ToLower(v.GetValue()),
				})
			}
		}
	}

	// SearchParameter: address-city (string)
	// FHIRPath: Patient.address.city
	for _, outer := range r.GetAddress() {
		if outer == nil {
			continue
		}
		if v := outer.GetCity(); v != nil && v.GetValue() != "" {
			idx.Strings = append(idx.Strings, SpidxString{
				TenantID: tenantID,
				ResType:  "Patient",
				ResID:    resID,
				SpName:   "address-city",
				SpValue:  strings.ToLower(v.GetValue()),
			})
		}
	}

	// SearchParameter: birthdate (date)
	// FHIRPath: Patient.birthDate
	if d := r.GetBirthDate(); d != nil {
		t := time.UnixMicro(d.GetValueUs()).UTC()
		idx.Dates = append(idx.Dates, SpidxDate{
			TenantID: tenantID,
			ResType:  "Patient",
			ResID:    resID,
			SpName:   "birthdate",
			SpLow:    t,
			SpHigh:   t,
		})
	}

	// SearchParameter: gender (token)
	// FHIRPath: Patient.gender
	if r.GetGender() != nil && r.GetGender().GetValue() != "" {
		idx.Tokens = append(idx.Tokens, SpidxToken{
			TenantID: tenantID,
			ResType:  "Patient",
			ResID:    resID,
			SpName:   "gender",
			SpValue:  r.GetGender().GetValue(),
		})
	}

	// SearchParameter: identifier (token)
	// FHIRPath: Patient.identifier
	for _, ident := range r.GetIdentifier() {
		if ident == nil {
			continue
		}
		system := ""
		if ident.GetSystem() != nil {
			system = ident.GetSystem().GetValue()
		}
		value := ""
		if ident.GetValue() != nil {
			value = ident.GetValue().GetValue()
		}
		if value != "" {
			idx.Tokens = append(idx.Tokens, SpidxToken{
				TenantID: tenantID,
				ResType:  "Patient",
				ResID:    resID,
				SpName:   "identifier",
				SpSystem: system,
				SpValue:  value,
			})
		}
	}

	// SearchParameter: active (token)
	// FHIRPath: Patient.active
	if r.GetActive() != nil {
		idx.Tokens = append(idx.Tokens, SpidxToken{
			TenantID: tenantID,
			ResType:  "Patient",
			ResID:    resID,
			SpName:   "active",
			SpValue:  fmt.Sprintf("%v", r.GetActive().GetValue()),
		})
	}

	// SearchParameter: email (token)
	// FHIRPath: Patient.telecom.where(system='email')
	for _, item := range r.GetTelecom() {
		if item == nil {
			continue
		}
		if item.GetSystem() == nil || item.GetSystem().GetValue() != "email" {
			continue
		}
		if item.GetValue() != nil && item.GetValue().GetValue() != "" {
			idx.Tokens = append(idx.Tokens, SpidxToken{
				TenantID: tenantID,
				ResType:  "Patient",
				ResID:    resID,
				SpName:   "email",
				SpSystem: "email",
				SpValue:  item.GetValue().GetValue(),
			})
		}
	}

	// SearchParameter: phone (token)
	// FHIRPath: Patient.telecom.where(system='phone')
	for _, item := range r.GetTelecom() {
		if item == nil {
			continue
		}
		if item.GetSystem() == nil || item.GetSystem().GetValue() != "phone" {
			continue
		}
		if item.GetValue() != nil && item.GetValue().GetValue() != "" {
			idx.Tokens = append(idx.Tokens, SpidxToken{
				TenantID: tenantID,
				ResType:  "Patient",
				ResID:    resID,
				SpName:   "phone",
				SpSystem: "phone",
				SpValue:  item.GetValue().GetValue(),
			})
		}
	}

	// SearchParameter: organization (reference)
	// FHIRPath: Patient.managingOrganization
	// google/fhir Reference: try URI first, then typed reference ID
	if ref := r.GetManagingOrganization(); ref != nil {
		// URI-based reference: "Organization/org-123"
		if uri := ref.GetUri(); uri != nil && uri.GetValue() != "" {
			parts := strings.SplitN(uri.GetValue(), "/", 2)
			if len(parts) == 2 {
				idx.References = append(idx.References, SpidxReference{
					TenantID:   tenantID,
					ResType:    "Patient",
					ResID:      resID,
					SpName:     "organization",
					TargetType: parts[0],
					TargetID:   parts[1],
				})
			}
		}
	}

	// SearchParameter: general-practitioner (reference)
	// FHIRPath: Patient.generalPractitioner
	// google/fhir Reference: try URI first, then typed reference ID
	for _, ref := range r.GetGeneralPractitioner() {
		if ref == nil {
			continue
		}
		// URI-based reference: "Organization/org-123"
		if uri := ref.GetUri(); uri != nil && uri.GetValue() != "" {
			parts := strings.SplitN(uri.GetValue(), "/", 2)
			if len(parts) == 2 {
				idx.References = append(idx.References, SpidxReference{
					TenantID:   tenantID,
					ResType:    "Patient",
					ResID:      resID,
					SpName:     "general-practitioner",
					TargetType: parts[0],
					TargetID:   parts[1],
				})
			}
		}
	}

	// SearchParameter: deceased (token)
	// FHIRPath: Patient.deceased.exists() and Patient.deceased != false
	// exists() check — index whether field is present
	if r.GetDeceased() != nil {
		idx.Tokens = append(idx.Tokens, SpidxToken{
			TenantID: tenantID,
			ResType:  "Patient",
			ResID:    resID,
			SpName:   "deceased",
			SpValue:  "true",
		})
	}

	// SearchParameter: death-date (date)
	// FHIRPath: (Patient.deceased as dateTime)
	// Choice type: deceased as dateTime
	// TODO: handle oneof deceased — check for dateTime variant

	// SearchParameter: language (token)
	// FHIRPath: Patient.communication.language
	for _, outer := range r.GetCommunication() {
		if outer == nil {
			continue
		}
		if v := outer.GetLanguage(); v != nil {
			// CodeableConcept → extract codings
			for _, coding := range v.GetCoding() {
				if coding == nil {
					continue
				}
				system := ""
				if coding.GetSystem() != nil {
					system = coding.GetSystem().GetValue()
				}
				code := ""
				if coding.GetCode() != nil {
					code = coding.GetCode().GetValue()
				}
				if code != "" {
					idx.Tokens = append(idx.Tokens, SpidxToken{
						TenantID: tenantID,
						ResType:  "Patient",
						ResID:    resID,
						SpName:   "language",
						SpSystem: system,
						SpValue:  code,
					})
				}
			}
		}
	}

	return idx
}

// ExtractPatientLinkIndexes extracts HAPI-style search index rows from a PatientLink proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractPatientLinkIndexes(tenantID string, r *PatientLink) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}

// ExtractPatientCommunicationIndexes extracts HAPI-style search index rows from a PatientCommunication proto.
// Each SearchParameter expression is compiled to a direct proto field accessor.
func ExtractPatientCommunicationIndexes(tenantID string, r *PatientCommunication) *SearchIndexes {
	if r == nil {
		return &SearchIndexes{}
	}

	idx := &SearchIndexes{}
	resID := ""
	_ = resID

	return idx
}
