// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catalog.proto

package pb

import (
	_ "github.com/protocgen/proto2type/proto/proto2type"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ModelCatalogEntry represents a model in the catalog.
type ModelCatalogEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelId          string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Provider         string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	DisplayName      string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	InputPerMillion  float64                `protobuf:"fixed64,4,opt,name=input_per_million,json=inputPerMillion,proto3" json:"input_per_million,omitempty"`
	OutputPerMillion float64                `protobuf:"fixed64,5,opt,name=output_per_million,json=outputPerMillion,proto3" json:"output_per_million,omitempty"`
	Enabled          bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Category         string                 `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	ContextWindow    int64                  `protobuf:"varint,8,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	DiscountPercent  float64                `protobuf:"fixed64,9,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	Aliases          []string               `protobuf:"bytes,12,rep,name=aliases,proto3" json:"aliases,omitempty"`
	ProviderModelId  string                 `protobuf:"bytes,14,opt,name=provider_model_id,json=providerModelId,proto3" json:"provider_model_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Notes            string                 `protobuf:"bytes,16,opt,name=notes,proto3" json:"notes,omitempty"`
	Region           string                 `protobuf:"bytes,17,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelCatalogEntry) Reset() {
	*x = ModelCatalogEntry{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCatalogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCatalogEntry) ProtoMessage() {}

func (x *ModelCatalogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCatalogEntry.ProtoReflect.Descriptor instead.
func (*ModelCatalogEntry) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *ModelCatalogEntry) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelCatalogEntry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelCatalogEntry) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelCatalogEntry) GetInputPerMillion() float64 {
	if x != nil {
		return x.InputPerMillion
	}
	return 0
}

func (x *ModelCatalogEntry) GetOutputPerMillion() float64 {
	if x != nil {
		return x.OutputPerMillion
	}
	return 0
}

func (x *ModelCatalogEntry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ModelCatalogEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ModelCatalogEntry) GetContextWindow() int64 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *ModelCatalogEntry) GetDiscountPercent() float64 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *ModelCatalogEntry) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ModelCatalogEntry) GetProviderModelId() string {
	if x != nil {
		return x.ProviderModelId
	}
	return ""
}

func (x *ModelCatalogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModelCatalogEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ModelCatalogEntry) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ModelCatalogEntry) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\atest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto2type/options.proto\"\xd1\x04\n" +
	"\x11ModelCatalogEntry\x12!\n" +
	"\bmodel_id\x18\x01 \x01(\tB\x06\xa2\xff+\x02\b\x01R\amodelId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12*\n" +
	"\x11input_per_million\x18\x04 \x01(\x01R\x0finputPerMillion\x12,\n" +
	"\x12output_per_million\x18\x05 \x01(\x01R\x10outputPerMillion\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1a\n" +
	"\bcategory\x18\a \x01(\tR\bcategory\x12%\n" +
	"\x0econtext_window\x18\b \x01(\x03R\rcontextWindow\x12)\n" +
	"\x10discount_percent\x18\t \x01(\x01R\x0fdiscountPercent\x12\x18\n" +
	"\aaliases\x18\f \x03(\tR\aaliases\x12*\n" +
	"\x11provider_model_id\x18\x0e \x01(\tR\x0fproviderModelId\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampB\x06\xa2\xff+\x02\x10\x01R\tupdatedAt\x12\x1c\n" +
	"\x05notes\x18\x10 \x01(\tB\x06\xa2\xff+\x02(\x01R\x05notes\x12\x16\n" +
	"\x06region\x18\x11 \x01(\tR\x06regionB7Z5github.com/protocgen/proto2type/testdata/golden/go/pbb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_proto_goTypes = []any{
	(*ModelCatalogEntry)(nil),     // 0: test.v1.ModelCatalogEntry
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_catalog_proto_depIdxs = []int32{
	1, // 0: test.v1.ModelCatalogEntry.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: test.v1.ModelCatalogEntry.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
