// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: complex.proto

package pb

import (
	_ "github.com/protocgen/proto2type/proto/proto2type"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Non-contiguous enum values.
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_LOW         Priority = 10
	Priority_PRIORITY_MEDIUM      Priority = 20
	Priority_PRIORITY_HIGH        Priority = 30
	Priority_PRIORITY_CRITICAL    Priority = 100
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0:   "PRIORITY_UNSPECIFIED",
		10:  "PRIORITY_LOW",
		20:  "PRIORITY_MEDIUM",
		30:  "PRIORITY_HIGH",
		100: "PRIORITY_CRITICAL",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_LOW":         10,
		"PRIORITY_MEDIUM":      20,
		"PRIORITY_HIGH":        30,
		"PRIORITY_CRITICAL":    100,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_complex_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_complex_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{0}
}

type Settings_Theme int32

const (
	Settings_THEME_UNSPECIFIED Settings_Theme = 0
	Settings_THEME_LIGHT       Settings_Theme = 1
	Settings_THEME_DARK        Settings_Theme = 2
)

// Enum value maps for Settings_Theme.
var (
	Settings_Theme_name = map[int32]string{
		0: "THEME_UNSPECIFIED",
		1: "THEME_LIGHT",
		2: "THEME_DARK",
	}
	Settings_Theme_value = map[string]int32{
		"THEME_UNSPECIFIED": 0,
		"THEME_LIGHT":       1,
		"THEME_DARK":        2,
	}
)

func (x Settings_Theme) Enum() *Settings_Theme {
	p := new(Settings_Theme)
	*p = x
	return p
}

func (x Settings_Theme) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Settings_Theme) Descriptor() protoreflect.EnumDescriptor {
	return file_complex_proto_enumTypes[1].Descriptor()
}

func (Settings_Theme) Type() protoreflect.EnumType {
	return &file_complex_proto_enumTypes[1]
}

func (x Settings_Theme) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Settings_Theme.Descriptor instead.
func (Settings_Theme) EnumDescriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{0, 0}
}

// Message with a nested enum.
type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         Settings_Theme         `protobuf:"varint,1,opt,name=theme,proto3,enum=test.v1.Settings_Theme" json:"theme,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_complex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetTheme() Settings_Theme {
	if x != nil {
		return x.Theme
	}
	return Settings_THEME_UNSPECIFIED
}

func (x *Settings) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

// Deeply nested messages (3 levels).
type Organization struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Departments   []*Organization_Department `protobuf:"bytes,2,rep,name=departments,proto3" json:"departments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_complex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{1}
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetDepartments() []*Organization_Department {
	if x != nil {
		return x.Departments
	}
	return nil
}

// Multiple oneofs.
type Notification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Channel:
	//
	//	*Notification_Email
	//	*Notification_Sms
	//	*Notification_PushToken
	Channel isNotification_Channel `protobuf_oneof:"channel"`
	// Types that are valid to be assigned to Content:
	//
	//	*Notification_PlainText
	//	*Notification_Html
	Content       isNotification_Content `protobuf_oneof:"content"`
	Priority      Priority               `protobuf:"varint,7,opt,name=priority,proto3,enum=test.v1.Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_complex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetChannel() isNotification_Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Notification) GetEmail() string {
	if x != nil {
		if x, ok := x.Channel.(*Notification_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *Notification) GetSms() string {
	if x != nil {
		if x, ok := x.Channel.(*Notification_Sms); ok {
			return x.Sms
		}
	}
	return ""
}

func (x *Notification) GetPushToken() string {
	if x != nil {
		if x, ok := x.Channel.(*Notification_PushToken); ok {
			return x.PushToken
		}
	}
	return ""
}

func (x *Notification) GetContent() isNotification_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Notification) GetPlainText() string {
	if x != nil {
		if x, ok := x.Content.(*Notification_PlainText); ok {
			return x.PlainText
		}
	}
	return ""
}

func (x *Notification) GetHtml() string {
	if x != nil {
		if x, ok := x.Content.(*Notification_Html); ok {
			return x.Html
		}
	}
	return ""
}

func (x *Notification) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

type isNotification_Channel interface {
	isNotification_Channel()
}

type Notification_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type Notification_Sms struct {
	Sms string `protobuf:"bytes,3,opt,name=sms,proto3,oneof"`
}

type Notification_PushToken struct {
	PushToken string `protobuf:"bytes,4,opt,name=push_token,json=pushToken,proto3,oneof"`
}

func (*Notification_Email) isNotification_Channel() {}

func (*Notification_Sms) isNotification_Channel() {}

func (*Notification_PushToken) isNotification_Channel() {}

type isNotification_Content interface {
	isNotification_Content()
}

type Notification_PlainText struct {
	PlainText string `protobuf:"bytes,5,opt,name=plain_text,json=plainText,proto3,oneof"`
}

type Notification_Html struct {
	Html string `protobuf:"bytes,6,opt,name=html,proto3,oneof"`
}

func (*Notification_PlainText) isNotification_Content() {}

func (*Notification_Html) isNotification_Content() {}

// Map with message values and various WKTs.
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SettingsMap   map[string]*Settings   `protobuf:"bytes,2,rep,name=settings_map,json=settingsMap,proto3" json:"settings_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CodeNames     map[int32]string       `protobuf:"bytes,3,rep,name=code_names,json=codeNames,proto3" json:"code_names,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Extension     *anypb.Any             `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Archived      *wrapperspb.BoolValue  `protobuf:"bytes,7,opt,name=archived,proto3" json:"archived,omitempty"`
	ViewCount     *wrapperspb.Int64Value `protobuf:"bytes,8,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	Placeholders  []*emptypb.Empty       `protobuf:"bytes,9,rep,name=placeholders,proto3" json:"placeholders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_complex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{3}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetSettingsMap() map[string]*Settings {
	if x != nil {
		return x.SettingsMap
	}
	return nil
}

func (x *Document) GetCodeNames() map[int32]string {
	if x != nil {
		return x.CodeNames
	}
	return nil
}

func (x *Document) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Document) GetExtension() *anypb.Any {
	if x != nil {
		return x.Extension
	}
	return nil
}

func (x *Document) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *Document) GetArchived() *wrapperspb.BoolValue {
	if x != nil {
		return x.Archived
	}
	return nil
}

func (x *Document) GetViewCount() *wrapperspb.Int64Value {
	if x != nil {
		return x.ViewCount
	}
	return nil
}

func (x *Document) GetPlaceholders() []*emptypb.Empty {
	if x != nil {
		return x.Placeholders
	}
	return nil
}

// Recursive/self-referencing message.
type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Children      []*TreeNode            `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	Parent        *TreeNode              `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_complex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{4}
}

func (x *TreeNode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TreeNode) GetChildren() []*TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *TreeNode) GetParent() *TreeNode {
	if x != nil {
		return x.Parent
	}
	return nil
}

// Message with skipped field and name override.
type AuditLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	InternalNotes string                 `protobuf:"bytes,3,opt,name=internal_notes,json=internalNotes,proto3" json:"internal_notes,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_complex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{5}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetInternalNotes() string {
	if x != nil {
		return x.InternalNotes
	}
	return ""
}

func (x *AuditLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Organization_Department struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Name          string                          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Teams         []*Organization_Department_Team `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization_Department) Reset() {
	*x = Organization_Department{}
	mi := &file_complex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization_Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization_Department) ProtoMessage() {}

func (x *Organization_Department) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization_Department.ProtoReflect.Descriptor instead.
func (*Organization_Department) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Organization_Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization_Department) GetTeams() []*Organization_Department_Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type Organization_Department_Team struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Members       []string               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization_Department_Team) Reset() {
	*x = Organization_Department_Team{}
	mi := &file_complex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization_Department_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization_Department_Team) ProtoMessage() {}

func (x *Organization_Department_Team) ProtoReflect() protoreflect.Message {
	mi := &file_complex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization_Department_Team.ProtoReflect.Descriptor instead.
func (*Organization_Department_Team) Descriptor() ([]byte, []int) {
	return file_complex_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Organization_Department_Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization_Department_Team) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_complex_proto protoreflect.FileDescriptor

const file_complex_proto_rawDesc = "" +
	"\n" +
	"\rcomplex.proto\x12\atest.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x18proto2type/options.proto\"\x92\x01\n" +
	"\bSettings\x12-\n" +
	"\x05theme\x18\x01 \x01(\x0e2\x17.test.v1.Settings.ThemeR\x05theme\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"?\n" +
	"\x05Theme\x12\x15\n" +
	"\x11THEME_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTHEME_LIGHT\x10\x01\x12\x0e\n" +
	"\n" +
	"THEME_DARK\x10\x02\"\xfc\x01\n" +
	"\fOrganization\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\vdepartments\x18\x02 \x03(\v2 .test.v1.Organization.DepartmentR\vdepartments\x1a\x93\x01\n" +
	"\n" +
	"Department\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x05teams\x18\x02 \x03(\v2%.test.v1.Organization.Department.TeamR\x05teams\x1a4\n" +
	"\x04Team\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\"\xe7\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x12\n" +
	"\x03sms\x18\x03 \x01(\tH\x00R\x03sms\x12\x1f\n" +
	"\n" +
	"push_token\x18\x04 \x01(\tH\x00R\tpushToken\x12\x1f\n" +
	"\n" +
	"plain_text\x18\x05 \x01(\tH\x01R\tplainText\x12\x14\n" +
	"\x04html\x18\x06 \x01(\tH\x01R\x04html\x12-\n" +
	"\bpriority\x18\a \x01(\x0e2\x11.test.v1.PriorityR\bpriorityB\t\n" +
	"\achannelB\t\n" +
	"\acontent\"\x89\x05\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\fsettings_map\x18\x02 \x03(\v2\".test.v1.Document.SettingsMapEntryR\vsettingsMap\x12?\n" +
	"\n" +
	"code_names\x18\x03 \x03(\v2 .test.v1.Document.CodeNamesEntryR\tcodeNames\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x122\n" +
	"\textension\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\textension\x12;\n" +
	"\vupdate_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x126\n" +
	"\barchived\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\barchived\x12:\n" +
	"\n" +
	"view_count\x18\b \x01(\v2\x1b.google.protobuf.Int64ValueR\tviewCount\x12:\n" +
	"\fplaceholders\x18\t \x03(\v2\x16.google.protobuf.EmptyR\fplaceholders\x1aQ\n" +
	"\x10SettingsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.test.v1.SettingsR\x05value:\x028\x01\x1a<\n" +
	"\x0eCodeNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\bTreeNode\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12-\n" +
	"\bchildren\x18\x02 \x03(\v2\x11.test.v1.TreeNodeR\bchildren\x12)\n" +
	"\x06parent\x18\x03 \x01(\v2\x11.test.v1.TreeNodeR\x06parent\"\x8f\x01\n" +
	"\bAuditLog\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xa2\xff+\x02\b\x01R\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12-\n" +
	"\x0einternal_notes\x18\x03 \x01(\tB\x06\xa2\xff+\x02 \x01R\rinternalNotes\x12$\n" +
	"\auser_id\x18\x04 \x01(\tB\v\xa2\xff+\a\x1a\x05actorR\x06userId*u\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPRIORITY_LOW\x10\n" +
	"\x12\x13\n" +
	"\x0fPRIORITY_MEDIUM\x10\x14\x12\x11\n" +
	"\rPRIORITY_HIGH\x10\x1e\x12\x15\n" +
	"\x11PRIORITY_CRITICAL\x10dB7Z5github.com/protocgen/proto2type/testdata/golden/go/pbb\x06proto3"

var (
	file_complex_proto_rawDescOnce sync.Once
	file_complex_proto_rawDescData []byte
)

func file_complex_proto_rawDescGZIP() []byte {
	file_complex_proto_rawDescOnce.Do(func() {
		file_complex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_complex_proto_rawDesc), len(file_complex_proto_rawDesc)))
	})
	return file_complex_proto_rawDescData
}

var file_complex_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_complex_proto_goTypes = []any{
	(Priority)(0),                        // 0: test.v1.Priority
	(Settings_Theme)(0),                  // 1: test.v1.Settings.Theme
	(*Settings)(nil),                     // 2: test.v1.Settings
	(*Organization)(nil),                 // 3: test.v1.Organization
	(*Notification)(nil),                 // 4: test.v1.Notification
	(*Document)(nil),                     // 5: test.v1.Document
	(*TreeNode)(nil),                     // 6: test.v1.TreeNode
	(*AuditLog)(nil),                     // 7: test.v1.AuditLog
	(*Organization_Department)(nil),      // 8: test.v1.Organization.Department
	(*Organization_Department_Team)(nil), // 9: test.v1.Organization.Department.Team
	nil,                                  // 10: test.v1.Document.SettingsMapEntry
	nil,                                  // 11: test.v1.Document.CodeNamesEntry
	(*structpb.Struct)(nil),              // 12: google.protobuf.Struct
	(*anypb.Any)(nil),                    // 13: google.protobuf.Any
	(*fieldmaskpb.FieldMask)(nil),        // 14: google.protobuf.FieldMask
	(*wrapperspb.BoolValue)(nil),         // 15: google.protobuf.BoolValue
	(*wrapperspb.Int64Value)(nil),        // 16: google.protobuf.Int64Value
	(*emptypb.Empty)(nil),                // 17: google.protobuf.Empty
}
var file_complex_proto_depIdxs = []int32{
	1,  // 0: test.v1.Settings.theme:type_name -> test.v1.Settings.Theme
	8,  // 1: test.v1.Organization.departments:type_name -> test.v1.Organization.Department
	0,  // 2: test.v1.Notification.priority:type_name -> test.v1.Priority
	10, // 3: test.v1.Document.settings_map:type_name -> test.v1.Document.SettingsMapEntry
	11, // 4: test.v1.Document.code_names:type_name -> test.v1.Document.CodeNamesEntry
	12, // 5: test.v1.Document.metadata:type_name -> google.protobuf.Struct
	13, // 6: test.v1.Document.extension:type_name -> google.protobuf.Any
	14, // 7: test.v1.Document.update_mask:type_name -> google.protobuf.FieldMask
	15, // 8: test.v1.Document.archived:type_name -> google.protobuf.BoolValue
	16, // 9: test.v1.Document.view_count:type_name -> google.protobuf.Int64Value
	17, // 10: test.v1.Document.placeholders:type_name -> google.protobuf.Empty
	6,  // 11: test.v1.TreeNode.children:type_name -> test.v1.TreeNode
	6,  // 12: test.v1.TreeNode.parent:type_name -> test.v1.TreeNode
	9,  // 13: test.v1.Organization.Department.teams:type_name -> test.v1.Organization.Department.Team
	2,  // 14: test.v1.Document.SettingsMapEntry.value:type_name -> test.v1.Settings
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_complex_proto_init() }
func file_complex_proto_init() {
	if File_complex_proto != nil {
		return
	}
	file_complex_proto_msgTypes[2].OneofWrappers = []any{
		(*Notification_Email)(nil),
		(*Notification_Sms)(nil),
		(*Notification_PushToken)(nil),
		(*Notification_PlainText)(nil),
		(*Notification_Html)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_complex_proto_rawDesc), len(file_complex_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_complex_proto_goTypes,
		DependencyIndexes: file_complex_proto_depIdxs,
		EnumInfos:         file_complex_proto_enumTypes,
		MessageInfos:      file_complex_proto_msgTypes,
	}.Build()
	File_complex_proto = out.File
	file_complex_proto_goTypes = nil
	file_complex_proto_depIdxs = nil
}
