// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: edge_cases.proto

package pb

import (
	_ "github.com/protocgen/proto2type/proto/proto2type"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SingleValueEnum has only the UNSPECIFIED sentinel — tests that validators,
// defined_only checks, and type unions don't break on single-variant enums.
type SingleValueEnum int32

const (
	SingleValueEnum_SINGLE_VALUE_ENUM_UNSPECIFIED SingleValueEnum = 0
)

// Enum value maps for SingleValueEnum.
var (
	SingleValueEnum_name = map[int32]string{
		0: "SINGLE_VALUE_ENUM_UNSPECIFIED",
	}
	SingleValueEnum_value = map[string]int32{
		"SINGLE_VALUE_ENUM_UNSPECIFIED": 0,
	}
)

func (x SingleValueEnum) Enum() *SingleValueEnum {
	p := new(SingleValueEnum)
	*p = x
	return p
}

func (x SingleValueEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SingleValueEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_edge_cases_proto_enumTypes[0].Descriptor()
}

func (SingleValueEnum) Type() protoreflect.EnumType {
	return &file_edge_cases_proto_enumTypes[0]
}

func (x SingleValueEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SingleValueEnum.Descriptor instead.
func (SingleValueEnum) EnumDescriptor() ([]byte, []int) {
	return file_edge_cases_proto_rawDescGZIP(), []int{0}
}

// EmptyMessage has zero fields — tests that code generation produces valid
// types, Clone, Equal, ToProto, FromProto, and Validate without panicking.
type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_edge_cases_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_edge_cases_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_edge_cases_proto_rawDescGZIP(), []int{0}
}

// AllOptionalScalars has every field marked optional — tests pointer-heavy
// struct generation, all-nil instantiation, Clone independence, and JSON
// omitempty for every proto3 optional scalar type.
type AllOptionalScalars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptString     *string                `protobuf:"bytes,1,opt,name=opt_string,json=optString,proto3,oneof" json:"opt_string,omitempty"`
	OptInt32      *int32                 `protobuf:"varint,2,opt,name=opt_int32,json=optInt32,proto3,oneof" json:"opt_int32,omitempty"`
	OptInt64      *int64                 `protobuf:"varint,3,opt,name=opt_int64,json=optInt64,proto3,oneof" json:"opt_int64,omitempty"`
	OptBool       *bool                  `protobuf:"varint,4,opt,name=opt_bool,json=optBool,proto3,oneof" json:"opt_bool,omitempty"`
	OptDouble     *float64               `protobuf:"fixed64,5,opt,name=opt_double,json=optDouble,proto3,oneof" json:"opt_double,omitempty"`
	OptFloat      *float32               `protobuf:"fixed32,6,opt,name=opt_float,json=optFloat,proto3,oneof" json:"opt_float,omitempty"`
	OptBytes      []byte                 `protobuf:"bytes,7,opt,name=opt_bytes,json=optBytes,proto3,oneof" json:"opt_bytes,omitempty"`
	OptTimestamp  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=opt_timestamp,json=optTimestamp,proto3,oneof" json:"opt_timestamp,omitempty"`
	OptEnum       *SingleValueEnum       `protobuf:"varint,9,opt,name=opt_enum,json=optEnum,proto3,enum=test.v1.SingleValueEnum,oneof" json:"opt_enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllOptionalScalars) Reset() {
	*x = AllOptionalScalars{}
	mi := &file_edge_cases_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllOptionalScalars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOptionalScalars) ProtoMessage() {}

func (x *AllOptionalScalars) ProtoReflect() protoreflect.Message {
	mi := &file_edge_cases_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOptionalScalars.ProtoReflect.Descriptor instead.
func (*AllOptionalScalars) Descriptor() ([]byte, []int) {
	return file_edge_cases_proto_rawDescGZIP(), []int{1}
}

func (x *AllOptionalScalars) GetOptString() string {
	if x != nil && x.OptString != nil {
		return *x.OptString
	}
	return ""
}

func (x *AllOptionalScalars) GetOptInt32() int32 {
	if x != nil && x.OptInt32 != nil {
		return *x.OptInt32
	}
	return 0
}

func (x *AllOptionalScalars) GetOptInt64() int64 {
	if x != nil && x.OptInt64 != nil {
		return *x.OptInt64
	}
	return 0
}

func (x *AllOptionalScalars) GetOptBool() bool {
	if x != nil && x.OptBool != nil {
		return *x.OptBool
	}
	return false
}

func (x *AllOptionalScalars) GetOptDouble() float64 {
	if x != nil && x.OptDouble != nil {
		return *x.OptDouble
	}
	return 0
}

func (x *AllOptionalScalars) GetOptFloat() float32 {
	if x != nil && x.OptFloat != nil {
		return *x.OptFloat
	}
	return 0
}

func (x *AllOptionalScalars) GetOptBytes() []byte {
	if x != nil {
		return x.OptBytes
	}
	return nil
}

func (x *AllOptionalScalars) GetOptTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.OptTimestamp
	}
	return nil
}

func (x *AllOptionalScalars) GetOptEnum() SingleValueEnum {
	if x != nil && x.OptEnum != nil {
		return *x.OptEnum
	}
	return SingleValueEnum_SINGLE_VALUE_ENUM_UNSPECIFIED
}

// OneofOnly has zero regular fields and a single oneof — tests that
// generators don't assume at least one standard field exists.
type OneofOnly struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OneofOnly_Text
	//	*OneofOnly_Number
	//	*OneofOnly_Flag
	Payload       isOneofOnly_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofOnly) Reset() {
	*x = OneofOnly{}
	mi := &file_edge_cases_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOnly) ProtoMessage() {}

func (x *OneofOnly) ProtoReflect() protoreflect.Message {
	mi := &file_edge_cases_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOnly.ProtoReflect.Descriptor instead.
func (*OneofOnly) Descriptor() ([]byte, []int) {
	return file_edge_cases_proto_rawDescGZIP(), []int{2}
}

func (x *OneofOnly) GetPayload() isOneofOnly_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OneofOnly) GetText() string {
	if x != nil {
		if x, ok := x.Payload.(*OneofOnly_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *OneofOnly) GetNumber() int32 {
	if x != nil {
		if x, ok := x.Payload.(*OneofOnly_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *OneofOnly) GetFlag() bool {
	if x != nil {
		if x, ok := x.Payload.(*OneofOnly_Flag); ok {
			return x.Flag
		}
	}
	return false
}

type isOneofOnly_Payload interface {
	isOneofOnly_Payload()
}

type OneofOnly_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type OneofOnly_Number struct {
	Number int32 `protobuf:"varint,2,opt,name=number,proto3,oneof"`
}

type OneofOnly_Flag struct {
	Flag bool `protobuf:"varint,3,opt,name=flag,proto3,oneof"`
}

func (*OneofOnly_Text) isOneofOnly_Payload() {}

func (*OneofOnly_Number) isOneofOnly_Payload() {}

func (*OneofOnly_Flag) isOneofOnly_Payload() {}

// MapOnly contains only map fields — tests nil-map vs empty-map semantics,
// map cloning, and equality without any scalar anchors.
type MapOnly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StringMap     map[string]string      `protobuf:"bytes,1,rep,name=string_map,json=stringMap,proto3" json:"string_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntMap        map[int32]string       `protobuf:"bytes,2,rep,name=int_map,json=intMap,proto3" json:"int_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapOnly) Reset() {
	*x = MapOnly{}
	mi := &file_edge_cases_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapOnly) ProtoMessage() {}

func (x *MapOnly) ProtoReflect() protoreflect.Message {
	mi := &file_edge_cases_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapOnly.ProtoReflect.Descriptor instead.
func (*MapOnly) Descriptor() ([]byte, []int) {
	return file_edge_cases_proto_rawDescGZIP(), []int{3}
}

func (x *MapOnly) GetStringMap() map[string]string {
	if x != nil {
		return x.StringMap
	}
	return nil
}

func (x *MapOnly) GetIntMap() map[int32]string {
	if x != nil {
		return x.IntMap
	}
	return nil
}

// RepeatedOnly contains only repeated fields — tests nil-slice vs
// empty-slice semantics, slice cloning, and equality.
type RepeatedOnly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Numbers       []int32                `protobuf:"varint,2,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedOnly) Reset() {
	*x = RepeatedOnly{}
	mi := &file_edge_cases_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedOnly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedOnly) ProtoMessage() {}

func (x *RepeatedOnly) ProtoReflect() protoreflect.Message {
	mi := &file_edge_cases_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedOnly.ProtoReflect.Descriptor instead.
func (*RepeatedOnly) Descriptor() ([]byte, []int) {
	return file_edge_cases_proto_rawDescGZIP(), []int{4}
}

func (x *RepeatedOnly) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RepeatedOnly) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

var File_edge_cases_proto protoreflect.FileDescriptor

const file_edge_cases_proto_rawDesc = "" +
	"\n" +
	"\x10edge_cases.proto\x12\atest.v1\x1a\x18proto2type/options.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fEmptyMessage\"\x86\x04\n" +
	"\x12AllOptionalScalars\x12\"\n" +
	"\n" +
	"opt_string\x18\x01 \x01(\tH\x00R\toptString\x88\x01\x01\x12 \n" +
	"\topt_int32\x18\x02 \x01(\x05H\x01R\boptInt32\x88\x01\x01\x12 \n" +
	"\topt_int64\x18\x03 \x01(\x03H\x02R\boptInt64\x88\x01\x01\x12\x1e\n" +
	"\bopt_bool\x18\x04 \x01(\bH\x03R\aoptBool\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_double\x18\x05 \x01(\x01H\x04R\toptDouble\x88\x01\x01\x12 \n" +
	"\topt_float\x18\x06 \x01(\x02H\x05R\boptFloat\x88\x01\x01\x12 \n" +
	"\topt_bytes\x18\a \x01(\fH\x06R\boptBytes\x88\x01\x01\x12D\n" +
	"\ropt_timestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\aR\foptTimestamp\x88\x01\x01\x128\n" +
	"\bopt_enum\x18\t \x01(\x0e2\x18.test.v1.SingleValueEnumH\bR\aoptEnum\x88\x01\x01B\r\n" +
	"\v_opt_stringB\f\n" +
	"\n" +
	"_opt_int32B\f\n" +
	"\n" +
	"_opt_int64B\v\n" +
	"\t_opt_boolB\r\n" +
	"\v_opt_doubleB\f\n" +
	"\n" +
	"_opt_floatB\f\n" +
	"\n" +
	"_opt_bytesB\x10\n" +
	"\x0e_opt_timestampB\v\n" +
	"\t_opt_enum\"\\\n" +
	"\tOneofOnly\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\x02 \x01(\x05H\x00R\x06number\x12\x14\n" +
	"\x04flag\x18\x03 \x01(\bH\x00R\x04flagB\t\n" +
	"\apayload\"\xf9\x01\n" +
	"\aMapOnly\x12>\n" +
	"\n" +
	"string_map\x18\x01 \x03(\v2\x1f.test.v1.MapOnly.StringMapEntryR\tstringMap\x125\n" +
	"\aint_map\x18\x02 \x03(\v2\x1c.test.v1.MapOnly.IntMapEntryR\x06intMap\x1a<\n" +
	"\x0eStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vIntMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\fRepeatedOnly\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\x12\x18\n" +
	"\anumbers\x18\x02 \x03(\x05R\anumbers*4\n" +
	"\x0fSingleValueEnum\x12!\n" +
	"\x1dSINGLE_VALUE_ENUM_UNSPECIFIED\x10\x00B7Z5github.com/protocgen/proto2type/testdata/golden/go/pbb\x06proto3"

var (
	file_edge_cases_proto_rawDescOnce sync.Once
	file_edge_cases_proto_rawDescData []byte
)

func file_edge_cases_proto_rawDescGZIP() []byte {
	file_edge_cases_proto_rawDescOnce.Do(func() {
		file_edge_cases_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_cases_proto_rawDesc), len(file_edge_cases_proto_rawDesc)))
	})
	return file_edge_cases_proto_rawDescData
}

var file_edge_cases_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_edge_cases_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_edge_cases_proto_goTypes = []any{
	(SingleValueEnum)(0),          // 0: test.v1.SingleValueEnum
	(*EmptyMessage)(nil),          // 1: test.v1.EmptyMessage
	(*AllOptionalScalars)(nil),    // 2: test.v1.AllOptionalScalars
	(*OneofOnly)(nil),             // 3: test.v1.OneofOnly
	(*MapOnly)(nil),               // 4: test.v1.MapOnly
	(*RepeatedOnly)(nil),          // 5: test.v1.RepeatedOnly
	nil,                           // 6: test.v1.MapOnly.StringMapEntry
	nil,                           // 7: test.v1.MapOnly.IntMapEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_edge_cases_proto_depIdxs = []int32{
	8, // 0: test.v1.AllOptionalScalars.opt_timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: test.v1.AllOptionalScalars.opt_enum:type_name -> test.v1.SingleValueEnum
	6, // 2: test.v1.MapOnly.string_map:type_name -> test.v1.MapOnly.StringMapEntry
	7, // 3: test.v1.MapOnly.int_map:type_name -> test.v1.MapOnly.IntMapEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_edge_cases_proto_init() }
func file_edge_cases_proto_init() {
	if File_edge_cases_proto != nil {
		return
	}
	file_edge_cases_proto_msgTypes[1].OneofWrappers = []any{}
	file_edge_cases_proto_msgTypes[2].OneofWrappers = []any{
		(*OneofOnly_Text)(nil),
		(*OneofOnly_Number)(nil),
		(*OneofOnly_Flag)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_cases_proto_rawDesc), len(file_edge_cases_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edge_cases_proto_goTypes,
		DependencyIndexes: file_edge_cases_proto_depIdxs,
		EnumInfos:         file_edge_cases_proto_enumTypes,
		MessageInfos:      file_edge_cases_proto_msgTypes,
	}.Build()
	File_edge_cases_proto = out.File
	file_edge_cases_proto_goTypes = nil
	file_edge_cases_proto_depIdxs = nil
}
