// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserStatus represents the user's account status.
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_SUSPENDED   UserStatus = 2
	UserStatus_USER_STATUS_DELETED     UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_SUSPENDED",
		3: "USER_STATUS_DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_SUSPENDED":   2,
		"USER_STATUS_DELETED":     3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

// User represents a user account.
type User struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName    string                  `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Active         bool                    `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Age            int32                   `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Roles          []string                `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Metadata       map[string]string       `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Address        *Address                `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt      *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SessionTimeout *durationpb.Duration    `protobuf:"bytes,10,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	Phone          *string                 `protobuf:"bytes,11,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Avatar         []byte                  `protobuf:"bytes,12,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname       *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status         UserStatus              `protobuf:"varint,14,opt,name=status,proto3,enum=test.v1.UserStatus" json:"status,omitempty"`
	// Types that are valid to be assigned to ContactMethod:
	//
	//	*User_ContactEmail
	//	*User_ContactPhone
	ContactMethod  isUser_ContactMethod   `protobuf_oneof:"contact_method"`
	Tags           []*Tag                 `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	PreviousStatus *UserStatus            `protobuf:"varint,19,opt,name=previous_status,json=previousStatus,proto3,enum=test.v1.UserStatus,oneof" json:"previous_status,omitempty"`
	// WKT reference types
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,20,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	ExtraMetadata *structpb.Struct       `protobuf:"bytes,21,opt,name=extra_metadata,json=extraMetadata,proto3" json:"extra_metadata,omitempty"`
	Preferences   *structpb.ListValue    `protobuf:"bytes,22,opt,name=preferences,proto3" json:"preferences,omitempty"`
	// Optional bytes
	AvatarThumbnail []byte `protobuf:"bytes,23,opt,name=avatar_thumbnail,json=avatarThumbnail,proto3,oneof" json:"avatar_thumbnail,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetSessionTimeout() *durationpb.Duration {
	if x != nil {
		return x.SessionTimeout
	}
	return nil
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *User) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetNickname() *wrapperspb.StringValue {
	if x != nil {
		return x.Nickname
	}
	return nil
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetContactMethod() isUser_ContactMethod {
	if x != nil {
		return x.ContactMethod
	}
	return nil
}

func (x *User) GetContactEmail() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*User_ContactEmail); ok {
			return x.ContactEmail
		}
	}
	return ""
}

func (x *User) GetContactPhone() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*User_ContactPhone); ok {
			return x.ContactPhone
		}
	}
	return ""
}

func (x *User) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetPreviousStatus() UserStatus {
	if x != nil && x.PreviousStatus != nil {
		return *x.PreviousStatus
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *User) GetExtraMetadata() *structpb.Struct {
	if x != nil {
		return x.ExtraMetadata
	}
	return nil
}

func (x *User) GetPreferences() *structpb.ListValue {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *User) GetAvatarThumbnail() []byte {
	if x != nil {
		return x.AvatarThumbnail
	}
	return nil
}

type isUser_ContactMethod interface {
	isUser_ContactMethod()
}

type User_ContactEmail struct {
	ContactEmail string `protobuf:"bytes,15,opt,name=contact_email,json=contactEmail,proto3,oneof"`
}

type User_ContactPhone struct {
	ContactPhone string `protobuf:"bytes,16,opt,name=contact_phone,json=contactPhone,proto3,oneof"`
}

func (*User_ContactEmail) isUser_ContactMethod() {}

func (*User_ContactPhone) isUser_ContactMethod() {}

// Address is a nested message.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// Tag is a label with a key-value pair.
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\atest.v1\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xfc\b\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\x127\n" +
	"\bmetadata\x18\a \x03(\v2\x1b.test.v1.User.MetadataEntryR\bmetadata\x12*\n" +
	"\aaddress\x18\b \x01(\v2\x10.test.v1.AddressR\aaddress\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12B\n" +
	"\x0fsession_timeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x0esessionTimeout\x12\x19\n" +
	"\x05phone\x18\v \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x16\n" +
	"\x06avatar\x18\f \x01(\fR\x06avatar\x128\n" +
	"\bnickname\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\bnickname\x12+\n" +
	"\x06status\x18\x0e \x01(\x0e2\x13.test.v1.UserStatusR\x06status\x12%\n" +
	"\rcontact_email\x18\x0f \x01(\tH\x00R\fcontactEmail\x12%\n" +
	"\rcontact_phone\x18\x10 \x01(\tH\x00R\fcontactPhone\x12 \n" +
	"\x04tags\x18\x11 \x03(\v2\f.test.v1.TagR\x04tags\x12>\n" +
	"\n" +
	"deleted_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tdeletedAt\x88\x01\x01\x12A\n" +
	"\x0fprevious_status\x18\x13 \x01(\x0e2\x13.test.v1.UserStatusH\x03R\x0epreviousStatus\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x14 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12>\n" +
	"\x0eextra_metadata\x18\x15 \x01(\v2\x17.google.protobuf.StructR\rextraMetadata\x12<\n" +
	"\vpreferences\x18\x16 \x01(\v2\x1a.google.protobuf.ListValueR\vpreferences\x12.\n" +
	"\x10avatar_thumbnail\x18\x17 \x01(\fH\x04R\x0favatarThumbnail\x88\x01\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0econtact_methodB\b\n" +
	"\x06_phoneB\r\n" +
	"\v_deleted_atB\x12\n" +
	"\x10_previous_statusB\x13\n" +
	"\x11_avatar_thumbnail\"w\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x04 \x01(\tR\x03zip\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*u\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x02\x12\x17\n" +
	"\x13USER_STATUS_DELETED\x10\x03B7Z5github.com/protocgen/proto2type/testdata/golden/go/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_goTypes = []any{
	(UserStatus)(0),                // 0: test.v1.UserStatus
	(*User)(nil),                   // 1: test.v1.User
	(*Address)(nil),                // 2: test.v1.Address
	(*Tag)(nil),                    // 3: test.v1.Tag
	nil,                            // 4: test.v1.User.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 6: google.protobuf.Duration
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
	(*fieldmaskpb.FieldMask)(nil),  // 8: google.protobuf.FieldMask
	(*structpb.Struct)(nil),        // 9: google.protobuf.Struct
	(*structpb.ListValue)(nil),     // 10: google.protobuf.ListValue
}
var file_user_proto_depIdxs = []int32{
	4,  // 0: test.v1.User.metadata:type_name -> test.v1.User.MetadataEntry
	2,  // 1: test.v1.User.address:type_name -> test.v1.Address
	5,  // 2: test.v1.User.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: test.v1.User.session_timeout:type_name -> google.protobuf.Duration
	7,  // 4: test.v1.User.nickname:type_name -> google.protobuf.StringValue
	0,  // 5: test.v1.User.status:type_name -> test.v1.UserStatus
	3,  // 6: test.v1.User.tags:type_name -> test.v1.Tag
	5,  // 7: test.v1.User.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 8: test.v1.User.previous_status:type_name -> test.v1.UserStatus
	8,  // 9: test.v1.User.update_mask:type_name -> google.protobuf.FieldMask
	9,  // 10: test.v1.User.extra_metadata:type_name -> google.protobuf.Struct
	10, // 11: test.v1.User.preferences:type_name -> google.protobuf.ListValue
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[0].OneofWrappers = []any{
		(*User_ContactEmail)(nil),
		(*User_ContactPhone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
