// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: user.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/protocgen/proto2type/proto/proto2type"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserStatus represents the user's account status.
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_SUSPENDED   UserStatus = 2
	UserStatus_USER_STATUS_DELETED     UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_SUSPENDED",
		3: "USER_STATUS_DELETED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_SUSPENDED":   2,
		"USER_STATUS_DELETED":     3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

// User represents a user account.
type User struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Id             string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName    string                  `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Active         bool                    `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Age            int32                   `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Roles          []string                `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Metadata       map[string]string       `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Address        *Address                `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt      *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SessionTimeout *durationpb.Duration    `protobuf:"bytes,10,opt,name=session_timeout,json=sessionTimeout,proto3" json:"session_timeout,omitempty"`
	Phone          *string                 `protobuf:"bytes,11,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Avatar         []byte                  `protobuf:"bytes,12,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Nickname       *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Status         UserStatus              `protobuf:"varint,14,opt,name=status,proto3,enum=test.v1.UserStatus" json:"status,omitempty"`
	// Types that are valid to be assigned to ContactMethod:
	//
	//	*User_ContactEmail
	//	*User_ContactPhone
	ContactMethod  isUser_ContactMethod   `protobuf_oneof:"contact_method"`
	Tags           []*Tag                 `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	PreviousStatus *UserStatus            `protobuf:"varint,19,opt,name=previous_status,json=previousStatus,proto3,enum=test.v1.UserStatus,oneof" json:"previous_status,omitempty"`
	// WKT reference types
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,20,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	ExtraMetadata *structpb.Struct       `protobuf:"bytes,21,opt,name=extra_metadata,json=extraMetadata,proto3" json:"extra_metadata,omitempty"`
	Preferences   *structpb.ListValue    `protobuf:"bytes,22,opt,name=preferences,proto3" json:"preferences,omitempty"`
	// Optional bytes
	AvatarThumbnail []byte `protobuf:"bytes,23,opt,name=avatar_thumbnail,json=avatarThumbnail,proto3,oneof" json:"avatar_thumbnail,omitempty"`
	// Repeated WKT reference types (Issue #52)
	FieldMasks []*fieldmaskpb.FieldMask `protobuf:"bytes,24,rep,name=field_masks,json=fieldMasks,proto3" json:"field_masks,omitempty"`
	Structs    []*structpb.Struct       `protobuf:"bytes,25,rep,name=structs,proto3" json:"structs,omitempty"`
	Lists      []*structpb.ListValue    `protobuf:"bytes,26,rep,name=lists,proto3" json:"lists,omitempty"`
	// WKT map values (Issue #53)
	EventTimes map[string]*timestamppb.Timestamp `protobuf:"bytes,27,rep,name=event_times,json=eventTimes,proto3" json:"event_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Configs    map[string]*structpb.Struct       `protobuf:"bytes,28,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Value type coverage (Issue #116)
	SingleValue *structpb.Value            `protobuf:"bytes,29,opt,name=single_value,json=singleValue,proto3" json:"single_value,omitempty"`
	Values      []*structpb.Value          `protobuf:"bytes,30,rep,name=values,proto3" json:"values,omitempty"`
	ValueMap    map[string]*structpb.Value `protobuf:"bytes,31,rep,name=value_map,json=valueMap,proto3" json:"value_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Wrapper map values (Issue #116)
	Labels map[string]*wrapperspb.StringValue `protobuf:"bytes,32,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Scores map[string]*wrapperspb.Int64Value  `protobuf:"bytes,33,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Deprecated: Marked as deprecated in user.proto.
	OldField     string `protobuf:"bytes,34,opt,name=old_field,json=oldField,proto3" json:"old_field,omitempty"`
	OptionalName string `protobuf:"bytes,35,opt,name=optional_name,json=optionalName,proto3" json:"optional_name,omitempty"`
	BigNumber    int64  `protobuf:"varint,36,opt,name=big_number,json=bigNumber,proto3" json:"big_number,omitempty"`
	// IgnoreEmpty parity test: skip validation when field is zero-value (empty string).
	Handle string `protobuf:"bytes,37,opt,name=handle,proto3" json:"handle,omitempty"`
	// Computed field: lowercase display_name for case-insensitive Firestore queries.
	DisplayNameLower string `protobuf:"bytes,38,opt,name=display_name_lower,json=displayNameLower,proto3" json:"display_name_lower,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetSessionTimeout() *durationpb.Duration {
	if x != nil {
		return x.SessionTimeout
	}
	return nil
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *User) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *User) GetNickname() *wrapperspb.StringValue {
	if x != nil {
		return x.Nickname
	}
	return nil
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetContactMethod() isUser_ContactMethod {
	if x != nil {
		return x.ContactMethod
	}
	return nil
}

func (x *User) GetContactEmail() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*User_ContactEmail); ok {
			return x.ContactEmail
		}
	}
	return ""
}

func (x *User) GetContactPhone() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*User_ContactPhone); ok {
			return x.ContactPhone
		}
	}
	return ""
}

func (x *User) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *User) GetPreviousStatus() UserStatus {
	if x != nil && x.PreviousStatus != nil {
		return *x.PreviousStatus
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *User) GetExtraMetadata() *structpb.Struct {
	if x != nil {
		return x.ExtraMetadata
	}
	return nil
}

func (x *User) GetPreferences() *structpb.ListValue {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *User) GetAvatarThumbnail() []byte {
	if x != nil {
		return x.AvatarThumbnail
	}
	return nil
}

func (x *User) GetFieldMasks() []*fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMasks
	}
	return nil
}

func (x *User) GetStructs() []*structpb.Struct {
	if x != nil {
		return x.Structs
	}
	return nil
}

func (x *User) GetLists() []*structpb.ListValue {
	if x != nil {
		return x.Lists
	}
	return nil
}

func (x *User) GetEventTimes() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.EventTimes
	}
	return nil
}

func (x *User) GetConfigs() map[string]*structpb.Struct {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *User) GetSingleValue() *structpb.Value {
	if x != nil {
		return x.SingleValue
	}
	return nil
}

func (x *User) GetValues() []*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *User) GetValueMap() map[string]*structpb.Value {
	if x != nil {
		return x.ValueMap
	}
	return nil
}

func (x *User) GetLabels() map[string]*wrapperspb.StringValue {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *User) GetScores() map[string]*wrapperspb.Int64Value {
	if x != nil {
		return x.Scores
	}
	return nil
}

// Deprecated: Marked as deprecated in user.proto.
func (x *User) GetOldField() string {
	if x != nil {
		return x.OldField
	}
	return ""
}

func (x *User) GetOptionalName() string {
	if x != nil {
		return x.OptionalName
	}
	return ""
}

func (x *User) GetBigNumber() int64 {
	if x != nil {
		return x.BigNumber
	}
	return 0
}

func (x *User) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *User) GetDisplayNameLower() string {
	if x != nil {
		return x.DisplayNameLower
	}
	return ""
}

type isUser_ContactMethod interface {
	isUser_ContactMethod()
}

type User_ContactEmail struct {
	ContactEmail string `protobuf:"bytes,15,opt,name=contact_email,json=contactEmail,proto3,oneof"`
}

type User_ContactPhone struct {
	ContactPhone string `protobuf:"bytes,16,opt,name=contact_phone,json=contactPhone,proto3,oneof"`
}

func (*User_ContactEmail) isUser_ContactMethod() {}

func (*User_ContactPhone) isUser_ContactMethod() {}

// Address is a nested message.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

// Tag is a label with a key-value pair.
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Category is a recursive tree structure for testing z.lazy() generation.
type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent        *Category              `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`     // singular self-ref → z.lazy()
	Children      []*Category            `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"` // repeated self-ref → z.array(z.lazy())
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetParent() *Category {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Category) GetChildren() []*Category {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\atest.v1\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x18proto2type/options.proto\"\xc6\x13\n" +
	"\x04User\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x03R\x02id\x12 \n" +
	"\x05email\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02`\x01R\x05email\x120\n" +
	"\fdisplay_name\x18\x03 \x01(\tB\r\xe0A\x02\xbaH\ar\x05\x10\x01\x18\xff\x01R\vdisplayName\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x1c\n" +
	"\x03age\x18\x05 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\x96\x01(\x00R\x03age\x12 \n" +
	"\x05roles\x18\x06 \x03(\tB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10\n" +
	"R\x05roles\x127\n" +
	"\bmetadata\x18\a \x03(\v2\x1b.test.v1.User.MetadataEntryR\bmetadata\x12*\n" +
	"\aaddress\x18\b \x01(\v2\x10.test.v1.AddressR\aaddress\x12>\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12B\n" +
	"\x0fsession_timeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\x0esessionTimeout\x12:\n" +
	"\x05phone\x18\v \x01(\tB\x1f\xbaH\x17r\x15\x10\a\x18\x142\x0f^\\+?[0-9\\-\\s]+$\xdaQ\x02@\x01H\x01R\x05phone\x88\x01\x01\x12\x16\n" +
	"\x06avatar\x18\f \x01(\fR\x06avatar\x128\n" +
	"\bnickname\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\bnickname\x125\n" +
	"\x06status\x18\x0e \x01(\x0e2\x13.test.v1.UserStatusB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06status\x12.\n" +
	"\rcontact_email\x18\x0f \x01(\tB\a\xbaH\x04r\x02`\x01H\x00R\fcontactEmail\x120\n" +
	"\rcontact_phone\x18\x10 \x01(\tB\t\xbaH\x06r\x04\x10\a\x18\x14H\x00R\fcontactPhone\x12 \n" +
	"\x04tags\x18\x11 \x03(\v2\f.test.v1.TagR\x04tags\x12C\n" +
	"\n" +
	"deleted_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03H\x02R\tdeletedAt\x88\x01\x01\x12K\n" +
	"\x0fprevious_status\x18\x13 \x01(\x0e2\x13.test.v1.UserStatusB\b\xbaH\x05\x82\x01\x02\x10\x01H\x03R\x0epreviousStatus\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x14 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12>\n" +
	"\x0eextra_metadata\x18\x15 \x01(\v2\x17.google.protobuf.StructR\rextraMetadata\x12<\n" +
	"\vpreferences\x18\x16 \x01(\v2\x1a.google.protobuf.ListValueR\vpreferences\x12.\n" +
	"\x10avatar_thumbnail\x18\x17 \x01(\fH\x04R\x0favatarThumbnail\x88\x01\x01\x12;\n" +
	"\vfield_masks\x18\x18 \x03(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"fieldMasks\x121\n" +
	"\astructs\x18\x19 \x03(\v2\x17.google.protobuf.StructR\astructs\x120\n" +
	"\x05lists\x18\x1a \x03(\v2\x1a.google.protobuf.ListValueR\x05lists\x12>\n" +
	"\vevent_times\x18\x1b \x03(\v2\x1d.test.v1.User.EventTimesEntryR\n" +
	"eventTimes\x124\n" +
	"\aconfigs\x18\x1c \x03(\v2\x1a.test.v1.User.ConfigsEntryR\aconfigs\x129\n" +
	"\fsingle_value\x18\x1d \x01(\v2\x16.google.protobuf.ValueR\vsingleValue\x12.\n" +
	"\x06values\x18\x1e \x03(\v2\x16.google.protobuf.ValueR\x06values\x128\n" +
	"\tvalue_map\x18\x1f \x03(\v2\x1b.test.v1.User.ValueMapEntryR\bvalueMap\x121\n" +
	"\x06labels\x18  \x03(\v2\x19.test.v1.User.LabelsEntryR\x06labels\x121\n" +
	"\x06scores\x18! \x03(\v2\x19.test.v1.User.ScoresEntryR\x06scores\x12\x1f\n" +
	"\told_field\x18\" \x01(\tB\x02\x18\x01R\boldField\x12#\n" +
	"\roptional_name\x18# \x01(\tR\foptionalName\x12\x1d\n" +
	"\n" +
	"big_number\x18$ \x01(\x03R\tbigNumber\x125\n" +
	"\x06handle\x18% \x01(\tB\x1d\xbaH\x1a\xd8\x01\x01r\x15\x10\x02\x1822\x0f^[a-zA-Z0-9_]+$R\x06handle\x12H\n" +
	"\x12display_name_lower\x18& \x01(\tB\x1a\xdaQ\x17J\x15\n" +
	"\fdisplay_name\x12\x05lowerR\x10displayNameLower\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aY\n" +
	"\x0fEventTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\x1aS\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value:\x028\x01\x1aS\n" +
	"\rValueMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\x1aW\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x05value:\x028\x01\x1aV\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05value:\x028\x01B\x10\n" +
	"\x0econtact_methodB\b\n" +
	"\x06_phoneB\r\n" +
	"\v_deleted_atB\x12\n" +
	"\x10_previous_statusB\x13\n" +
	"\x11_avatar_thumbnail\"\xb3\x01\n" +
	"\aAddress\x12\x1f\n" +
	"\x06street\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06street\x12\x1b\n" +
	"\x04city\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04city\x12\x1f\n" +
	"\x05state\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18\x02R\x05state\x12/\n" +
	"\x03zip\x18\x04 \x01(\tB\x1d\xbaH\x1ar\x182\x16^[0-9]{5}(-[0-9]{4})?$R\x03zip\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"x\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x06parent\x18\x02 \x01(\v2\x11.test.v1.CategoryR\x06parent\x12-\n" +
	"\bchildren\x18\x03 \x03(\v2\x11.test.v1.CategoryR\bchildren*u\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x02\x12\x17\n" +
	"\x13USER_STATUS_DELETED\x10\x03B7Z5github.com/protocgen/proto2type/testdata/golden/go/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_proto_goTypes = []any{
	(UserStatus)(0),                // 0: test.v1.UserStatus
	(*User)(nil),                   // 1: test.v1.User
	(*Address)(nil),                // 2: test.v1.Address
	(*Tag)(nil),                    // 3: test.v1.Tag
	(*Category)(nil),               // 4: test.v1.Category
	nil,                            // 5: test.v1.User.MetadataEntry
	nil,                            // 6: test.v1.User.EventTimesEntry
	nil,                            // 7: test.v1.User.ConfigsEntry
	nil,                            // 8: test.v1.User.ValueMapEntry
	nil,                            // 9: test.v1.User.LabelsEntry
	nil,                            // 10: test.v1.User.ScoresEntry
	(*timestamppb.Timestamp)(nil),  // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 12: google.protobuf.Duration
	(*wrapperspb.StringValue)(nil), // 13: google.protobuf.StringValue
	(*fieldmaskpb.FieldMask)(nil),  // 14: google.protobuf.FieldMask
	(*structpb.Struct)(nil),        // 15: google.protobuf.Struct
	(*structpb.ListValue)(nil),     // 16: google.protobuf.ListValue
	(*structpb.Value)(nil),         // 17: google.protobuf.Value
	(*wrapperspb.Int64Value)(nil),  // 18: google.protobuf.Int64Value
}
var file_user_proto_depIdxs = []int32{
	5,  // 0: test.v1.User.metadata:type_name -> test.v1.User.MetadataEntry
	2,  // 1: test.v1.User.address:type_name -> test.v1.Address
	11, // 2: test.v1.User.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: test.v1.User.session_timeout:type_name -> google.protobuf.Duration
	13, // 4: test.v1.User.nickname:type_name -> google.protobuf.StringValue
	0,  // 5: test.v1.User.status:type_name -> test.v1.UserStatus
	3,  // 6: test.v1.User.tags:type_name -> test.v1.Tag
	11, // 7: test.v1.User.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 8: test.v1.User.previous_status:type_name -> test.v1.UserStatus
	14, // 9: test.v1.User.update_mask:type_name -> google.protobuf.FieldMask
	15, // 10: test.v1.User.extra_metadata:type_name -> google.protobuf.Struct
	16, // 11: test.v1.User.preferences:type_name -> google.protobuf.ListValue
	14, // 12: test.v1.User.field_masks:type_name -> google.protobuf.FieldMask
	15, // 13: test.v1.User.structs:type_name -> google.protobuf.Struct
	16, // 14: test.v1.User.lists:type_name -> google.protobuf.ListValue
	6,  // 15: test.v1.User.event_times:type_name -> test.v1.User.EventTimesEntry
	7,  // 16: test.v1.User.configs:type_name -> test.v1.User.ConfigsEntry
	17, // 17: test.v1.User.single_value:type_name -> google.protobuf.Value
	17, // 18: test.v1.User.values:type_name -> google.protobuf.Value
	8,  // 19: test.v1.User.value_map:type_name -> test.v1.User.ValueMapEntry
	9,  // 20: test.v1.User.labels:type_name -> test.v1.User.LabelsEntry
	10, // 21: test.v1.User.scores:type_name -> test.v1.User.ScoresEntry
	4,  // 22: test.v1.Category.parent:type_name -> test.v1.Category
	4,  // 23: test.v1.Category.children:type_name -> test.v1.Category
	11, // 24: test.v1.User.EventTimesEntry.value:type_name -> google.protobuf.Timestamp
	15, // 25: test.v1.User.ConfigsEntry.value:type_name -> google.protobuf.Struct
	17, // 26: test.v1.User.ValueMapEntry.value:type_name -> google.protobuf.Value
	13, // 27: test.v1.User.LabelsEntry.value:type_name -> google.protobuf.StringValue
	18, // 28: test.v1.User.ScoresEntry.value:type_name -> google.protobuf.Int64Value
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	file_user_proto_msgTypes[0].OneofWrappers = []any{
		(*User_ContactEmail)(nil),
		(*User_ContactPhone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
